ARG OS_TYPE
ARG OS_TAG

FROM ${OS_TYPE}/cpp-env:base-${OS_TAG}

RUN apt-get update        && \
    apt-get install -y       \
      libfreetype-dev        \
      libglu1-mesa-dev       \
      freeglut3-dev          \
      mesa-common-dev        \
      libglew-dev            \
      python3-dev            \
      python3-matplotlib     \
      locales-all            \
      make                   \
      autoconf               \
      automake               \
      cmake                  \
      ninja-build            \
      dos2unix               \
      rsync                  \
      tar                    \
      git                    \
      catch2                 \
      ccache                 \
      build-essential        \
      gdb                    \
      gcc-12                 \
      g++-12              && \
    apt-get clean -y
