ARG OS_TAG

FROM clion/ubuntu/cpp-env:dev-tools-${OS_TAG}

ARG CLANG_VER=""

COPY "llvm.sh" /tmp/llvm.sh
WORKDIR /tmp

RUN apt-get update                                       && \
    apt-get install -y                                      \
      --no-install-recommends software-properties-common    \
      lsb-release                                           \
      wget

RUN if [ -n "${CLANG_VER}" ] ; then bash llvm.sh ${CLANG_VER} ; fi

RUN apt-get clean -y

ARG UID=1000
RUN useradd -m -u ${UID} -s /bin/bash builder
USER builder
