#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> ALGAE_13
{
  {   0.84314F,   0.97647F,   0.81569F },
  {   0.74118F,   0.90196F,   0.69412F },
  {   0.63529F,   0.83529F,   0.58431F },
  {   0.51765F,   0.76863F,   0.47843F },
  {   0.39216F,   0.70588F,   0.38824F },
  {   0.23137F,   0.65098F,   0.32941F },
  {   0.07059F,   0.58039F,   0.31373F },
  {   0.03137F,   0.50588F,   0.29804F },
  {   0.07059F,   0.43137F,   0.27059F },
  {   0.09412F,   0.35686F,   0.23137F },
  {   0.10196F,   0.28627F,   0.18824F },
  {   0.09020F,   0.21176F,   0.13333F },
  {   0.07059F,   0.14118F,   0.07843F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
