#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> BALANCE_11
{
  {   0.09412F,   0.10980F,   0.26275F },
  {   0.16078F,   0.24706F,   0.60392F },
  {   0.08627F,   0.43922F,   0.73725F },
  {   0.34902F,   0.61176F,   0.73333F },
  {   0.66667F,   0.76078F,   0.79608F },
  {   0.94510F,   0.92549F,   0.92157F },
  {   0.86275F,   0.69804F,   0.64314F },
  {   0.79216F,   0.47451F,   0.36471F },
  {   0.70196F,   0.21961F,   0.14902F },
  {   0.49412F,   0.05490F,   0.16078F },
  {   0.23529F,   0.03529F,   0.07059F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
