#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> BILBAO_11
{
  {   1.00000F,   1.00000F,   1.00000F },
  {   0.87059F,   0.87059F,   0.86275F },
  {   0.78431F,   0.76863F,   0.72157F },
  {   0.74118F,   0.70980F,   0.58824F },
  {   0.69804F,   0.62353F,   0.46275F },
  {   0.66667F,   0.52549F,   0.39608F },
  {   0.63922F,   0.43922F,   0.36078F },
  {   0.60784F,   0.34902F,   0.31765F },
  {   0.53333F,   0.23529F,   0.23137F },
  {   0.41961F,   0.12157F,   0.12157F },
  {   0.30196F,   0.00000F,   0.00392F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
