#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> BLUEDARKRED18_7
{
  {   0.14118F,   0.00000F,   0.84706F },
  {   0.23922F,   0.52941F,   1.00000F },
  {   0.60000F,   0.91765F,   1.00000F },
  {   0.91765F,   1.00000F,   1.00000F },
  {   1.00000F,   0.83922F,   0.60000F },
  {   1.00000F,   0.23922F,   0.23922F },
  {   0.64706F,   0.00000F,   0.12941F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
