#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> BLUEORANGE8_5
{
  {   0.00000F,   0.49804F,   1.00000F },
  {   0.60000F,   0.92941F,   1.00000F },
  {   1.00000F,   1.00000F,   0.80000F },
  {   1.00000F,   0.93333F,   0.60000F },
  {   1.00000F,   0.49804F,   0.00000F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
