#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> BLUEDARKORANGE18_15
{
  {   0.00000F,   0.40000F,   0.40000F },
  {   0.00000F,   0.60000F,   0.60000F },
  {   0.00000F,   0.80000F,   0.80000F },
  {   0.20000F,   1.00000F,   1.00000F },
  {   0.39608F,   1.00000F,   1.00000F },
  {   0.60000F,   1.00000F,   1.00000F },
  {   0.69804F,   1.00000F,   1.00000F },
  {   0.79608F,   1.00000F,   1.00000F },
  {   1.00000F,   0.89804F,   0.79608F },
  {   1.00000F,   0.79216F,   0.60000F },
  {   1.00000F,   0.67843F,   0.39608F },
  {   1.00000F,   0.55686F,   0.20000F },
  {   0.80000F,   0.33333F,   0.00000F },
  {   0.60000F,   0.23922F,   0.00000F },
  {   0.40000F,   0.15294F,   0.00000F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
