#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> BRBG_5
{
  {   0.65098F,   0.38039F,   0.10196F },
  {   0.87451F,   0.76078F,   0.49020F },
  {   0.96078F,   0.96078F,   0.96078F },
  {   0.50196F,   0.80392F,   0.75686F },
  {   0.00392F,   0.52157F,   0.44314F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
