#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> BUDA_8
{
  {   0.70196F,   0.00392F,   0.70196F },
  {   0.70588F,   0.20000F,   0.60392F },
  {   0.74510F,   0.33725F,   0.55294F },
  {   0.78824F,   0.45882F,   0.51373F },
  {   0.81961F,   0.58431F,   0.47843F },
  {   0.85098F,   0.70980F,   0.44706F },
  {   0.88627F,   0.84314F,   0.41569F },
  {   1.00000F,   1.00000F,   0.40000F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
