#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> BUDA_6
{
  {   0.70196F,   0.00392F,   0.70196F },
  {   0.72157F,   0.25882F,   0.58039F },
  {   0.78039F,   0.43529F,   0.52157F },
  {   0.82745F,   0.60784F,   0.47451F },
  {   0.87059F,   0.78824F,   0.42745F },
  {   1.00000F,   1.00000F,   0.40000F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
