#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> CORK_10
{
  {   0.17255F,   0.10196F,   0.29804F },
  {   0.16471F,   0.26275F,   0.45882F },
  {   0.28235F,   0.44706F,   0.61961F },
  {   0.51765F,   0.63137F,   0.74510F },
  {   0.76471F,   0.82353F,   0.87451F },
  {   0.80392F,   0.88235F,   0.81176F },
  {   0.58431F,   0.75686F,   0.60000F },
  {   0.36863F,   0.62353F,   0.38431F },
  {   0.25098F,   0.43922F,   0.15294F },
  {   0.25882F,   0.30196F,   0.01176F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
