#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> CUBEYF_6
{
  {   0.48235F,   0.00784F,   0.56471F },
  {   0.45098F,   0.34118F,   0.97255F },
  {   0.29804F,   0.61961F,   0.85098F },
  {   0.27843F,   0.80392F,   0.52157F },
  {   0.46275F,   0.91373F,   0.30196F },
  {   0.81961F,   0.92157F,   0.35686F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
