#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> DAVOS_11
{
  {   0.00000F,   0.01961F,   0.29020F },
  {   0.06275F,   0.16471F,   0.43529F },
  {   0.13725F,   0.29020F,   0.54902F },
  {   0.22745F,   0.40392F,   0.60784F },
  {   0.32941F,   0.49020F,   0.61176F },
  {   0.42353F,   0.55686F,   0.57647F },
  {   0.51765F,   0.61961F,   0.53725F },
  {   0.64314F,   0.71373F,   0.54118F },
  {   0.83137F,   0.85882F,   0.65882F },
  {   0.96078F,   0.96078F,   0.84314F },
  {   0.99608F,   0.99608F,   0.99608F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
