#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> DEEP_8
{
  {   0.99216F,   0.99608F,   0.80000F },
  {   0.69804F,   0.89020F,   0.66667F },
  {   0.41569F,   0.77255F,   0.64314F },
  {   0.30980F,   0.63137F,   0.63529F },
  {   0.25882F,   0.48627F,   0.60392F },
  {   0.24314F,   0.34118F,   0.56863F },
  {   0.23922F,   0.20784F,   0.38431F },
  {   0.15686F,   0.10196F,   0.17255F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
