#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> DENSE_10
{
  {   0.90196F,   0.94510F,   0.94510F },
  {   0.71765F,   0.85490F,   0.89412F },
  {   0.55686F,   0.75294F,   0.88627F },
  {   0.46275F,   0.64314F,   0.89804F },
  {   0.45882F,   0.51373F,   0.87451F },
  {   0.47451F,   0.38039F,   0.78431F },
  {   0.46275F,   0.25882F,   0.64706F },
  {   0.41961F,   0.15686F,   0.47843F },
  {   0.33725F,   0.08627F,   0.29412F },
  {   0.21176F,   0.05490F,   0.14118F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
