#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> DEVON_10
{
  {   0.17255F,   0.10196F,   0.29804F },
  {   0.16078F,   0.20392F,   0.40392F },
  {   0.15294F,   0.31765F,   0.52549F },
  {   0.21176F,   0.41176F,   0.67843F },
  {   0.38039F,   0.50588F,   0.81569F },
  {   0.59608F,   0.60784F,   0.90588F },
  {   0.72941F,   0.70196F,   0.94510F },
  {   0.81569F,   0.80000F,   0.96078F },
  {   0.90980F,   0.89804F,   0.98039F },
  {   1.00000F,   1.00000F,   1.00000F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
