#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> GRAY_12
{
  {   0.00000F,   0.00000F,   0.00000F },
  {   0.06667F,   0.06275F,   0.06275F },
  {   0.15294F,   0.14902F,   0.14902F },
  {   0.23922F,   0.23529F,   0.23529F },
  {   0.31765F,   0.31765F,   0.31373F },
  {   0.40000F,   0.40000F,   0.39608F },
  {   0.48627F,   0.48627F,   0.48235F },
  {   0.57647F,   0.57255F,   0.57255F },
  {   0.67059F,   0.66667F,   0.66275F },
  {   0.77255F,   0.77255F,   0.76863F },
  {   0.88235F,   0.88235F,   0.87451F },
  {   1.00000F,   1.00000F,   0.99216F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
