#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> ICE_12
{
  {   0.01569F,   0.02353F,   0.07451F },
  {   0.09804F,   0.09804F,   0.20392F },
  {   0.17255F,   0.16863F,   0.34118F },
  {   0.23137F,   0.24314F,   0.49804F },
  {   0.24706F,   0.32941F,   0.62745F },
  {   0.24706F,   0.43137F,   0.69804F },
  {   0.28235F,   0.52941F,   0.73725F },
  {   0.35294F,   0.62353F,   0.76863F },
  {   0.44706F,   0.72157F,   0.80784F },
  {   0.58431F,   0.81569F,   0.84706F },
  {   0.75294F,   0.90196F,   0.90980F },
  {   0.91765F,   0.99216F,   0.99216F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
