#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> INFERNO_10
{
  {   0.00000F,   0.00000F,   0.01569F },
  {   0.10588F,   0.04706F,   0.25490F },
  {   0.29804F,   0.04706F,   0.41961F },
  {   0.47059F,   0.10980F,   0.42745F },
  {   0.64706F,   0.17255F,   0.37647F },
  {   0.81176F,   0.26667F,   0.27451F },
  {   0.92941F,   0.41176F,   0.14510F },
  {   0.98431F,   0.60000F,   0.02353F },
  {   0.96863F,   0.81961F,   0.23922F },
  {   0.98824F,   1.00000F,   0.64314F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
