#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> LISBON_10
{
  {   0.90196F,   0.89804F,   1.00000F },
  {   0.60784F,   0.68627F,   0.82745F },
  {   0.31765F,   0.46667F,   0.64314F },
  {   0.11765F,   0.26275F,   0.40784F },
  {   0.06667F,   0.11765F,   0.17255F },
  {   0.15294F,   0.14510F,   0.10196F },
  {   0.34118F,   0.31765F,   0.20392F },
  {   0.55294F,   0.52157F,   0.33725F },
  {   0.78824F,   0.76471F,   0.56471F },
  {   1.00000F,   1.00000F,   0.85098F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
