#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> MOONRISE6_5
{
  {   0.74902F,   0.31765F,   0.23922F },
  {   0.78824F,   0.63529F,   0.58824F },
  {   0.77255F,   0.75686F,   0.53333F },
  {   0.48235F,   0.69412F,   0.56863F },
  {   0.85098F,   0.68235F,   0.18824F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
