#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> NUUK_13
{
  {   0.01961F,   0.34902F,   0.54902F },
  {   0.13333F,   0.37647F,   0.52157F },
  {   0.21961F,   0.41176F,   0.50980F },
  {   0.32549F,   0.46667F,   0.52157F },
  {   0.43529F,   0.52941F,   0.55294F },
  {   0.54118F,   0.59216F,   0.58431F },
  {   0.63137F,   0.65098F,   0.59608F },
  {   0.69020F,   0.69412F,   0.58039F },
  {   0.72941F,   0.72549F,   0.55294F },
  {   0.76471F,   0.76078F,   0.52157F },
  {   0.81961F,   0.81569F,   0.51765F },
  {   0.90980F,   0.90980F,   0.58431F },
  {   0.99608F,   0.99608F,   0.69804F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
