#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> PASTEL1
{
  {   0.98431F,   0.70588F,   0.68235F },
  {   0.70196F,   0.80392F,   0.89020F },
  {   0.80000F,   0.92157F,   0.77255F },
  {   0.87059F,   0.79608F,   0.89412F },
  {   0.99608F,   0.85098F,   0.65098F },
  {   1.00000F,   1.00000F,   0.80000F },
  {   0.89804F,   0.84706F,   0.74118F },
  {   0.99216F,   0.85490F,   0.92549F },
  {   0.94902F,   0.94902F,   0.94902F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
