#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> PEACH_6
{
  {   0.99216F,   0.87843F,   0.77255F },
  {   0.98039F,   0.79608F,   0.65098F },
  {   0.97255F,   0.70980F,   0.54510F },
  {   0.94902F,   0.52157F,   0.36471F },
  {   0.93725F,   0.41569F,   0.29804F },
  {   0.92157F,   0.29020F,   0.25098F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
