#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> PIYG_3
{
  {   0.91373F,   0.63922F,   0.78824F },
  {   0.96863F,   0.96863F,   0.96863F },
  {   0.63137F,   0.84314F,   0.41569F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
