#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> PURD_8
{
  {   0.96863F,   0.95686F,   0.97647F },
  {   0.90588F,   0.88235F,   0.93725F },
  {   0.83137F,   0.72549F,   0.85490F },
  {   0.78824F,   0.58039F,   0.78039F },
  {   0.87451F,   0.39608F,   0.69020F },
  {   0.90588F,   0.16078F,   0.54118F },
  {   0.80784F,   0.07059F,   0.33725F },
  {   0.56863F,   0.00000F,   0.24706F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
