#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> PURPLES_6
{
  {   0.94902F,   0.94118F,   0.96863F },
  {   0.85490F,   0.85490F,   0.92157F },
  {   0.73725F,   0.74118F,   0.86275F },
  {   0.61961F,   0.60392F,   0.78431F },
  {   0.45882F,   0.41961F,   0.69412F },
  {   0.32941F,   0.15294F,   0.56078F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
