#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> SOLAR_7
{
  {   0.20000F,   0.07843F,   0.09412F },
  {   0.40784F,   0.13725F,   0.14510F },
  {   0.59216F,   0.23137F,   0.10980F },
  {   0.71373F,   0.39216F,   0.07451F },
  {   0.79608F,   0.57255F,   0.10196F },
  {   0.85490F,   0.76863F,   0.18431F },
  {   0.88235F,   0.99216F,   0.29412F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
