#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> TABLEAUMEDIUM_10
{
  {   0.44706F,   0.61961F,   0.80784F },
  {   1.00000F,   0.61961F,   0.29020F },
  {   0.40392F,   0.74902F,   0.36078F },
  {   0.92941F,   0.40000F,   0.36471F },
  {   0.67843F,   0.54510F,   0.78824F },
  {   0.65882F,   0.47059F,   0.43137F },
  {   0.92941F,   0.59216F,   0.79216F },
  {   0.63529F,   0.63529F,   0.63529F },
  {   0.80392F,   0.80000F,   0.36471F },
  {   0.42745F,   0.80000F,   0.85490F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
