#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> TEMPO_6
{
  {   1.00000F,   0.96471F,   0.95686F },
  {   0.71373F,   0.79608F,   0.68627F },
  {   0.36471F,   0.65490F,   0.52549F },
  {   0.06667F,   0.49020F,   0.47451F },
  {   0.10980F,   0.30196F,   0.38039F },
  {   0.08235F,   0.11373F,   0.26667F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
