#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> THERMAL_9
{
  {   0.01569F,   0.13725F,   0.20000F },
  {   0.09804F,   0.20000F,   0.48627F },
  {   0.33725F,   0.23137F,   0.61176F },
  {   0.51373F,   0.31373F,   0.56078F },
  {   0.69412F,   0.37255F,   0.50980F },
  {   0.87059F,   0.43922F,   0.39608F },
  {   0.97647F,   0.57255F,   0.25882F },
  {   0.97647F,   0.76863F,   0.25490F },
  {   0.90980F,   0.98039F,   0.35686F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
