#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> TOFINO_14
{
  {   0.87059F,   0.85098F,   1.00000F },
  {   0.65882F,   0.70196F,   0.90980F },
  {   0.46275F,   0.56078F,   0.81569F },
  {   0.27843F,   0.40392F,   0.65490F },
  {   0.18039F,   0.27843F,   0.46275F },
  {   0.10980F,   0.16471F,   0.27451F },
  {   0.06275F,   0.08627F,   0.11765F },
  {   0.06275F,   0.10980F,   0.07059F },
  {   0.10196F,   0.21961F,   0.11373F },
  {   0.16471F,   0.35294F,   0.18039F },
  {   0.23922F,   0.49020F,   0.25490F },
  {   0.40392F,   0.65098F,   0.36863F },
  {   0.62745F,   0.77647F,   0.48627F },
  {   0.85882F,   0.90196F,   0.60784F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
