#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> TURKU_19
{
  {   0.00000F,   0.00000F,   0.00000F },
  {   0.08627F,   0.08627F,   0.07843F },
  {   0.14118F,   0.14118F,   0.12549F },
  {   0.20000F,   0.19608F,   0.16863F },
  {   0.25882F,   0.25882F,   0.20784F },
  {   0.31765F,   0.31373F,   0.23922F },
  {   0.37255F,   0.37255F,   0.26667F },
  {   0.43137F,   0.42745F,   0.29412F },
  {   0.49412F,   0.48627F,   0.32157F },
  {   0.57647F,   0.54902F,   0.35686F },
  {   0.66275F,   0.60000F,   0.39608F },
  {   0.74510F,   0.63529F,   0.43922F },
  {   0.81176F,   0.65098F,   0.48627F },
  {   0.86667F,   0.65882F,   0.53333F },
  {   0.91765F,   0.67843F,   0.59608F },
  {   0.96078F,   0.72157F,   0.67843F },
  {   0.98824F,   0.78039F,   0.76471F },
  {   0.99608F,   0.84314F,   0.83529F },
  {   1.00000F,   0.90196F,   0.90196F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
