#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> TURKU_13
{
  {   0.00000F,   0.00000F,   0.00000F },
  {   0.11373F,   0.11373F,   0.10196F },
  {   0.20000F,   0.19608F,   0.16863F },
  {   0.28627F,   0.28627F,   0.22745F },
  {   0.37255F,   0.37255F,   0.26667F },
  {   0.46275F,   0.45490F,   0.30588F },
  {   0.57647F,   0.54902F,   0.35686F },
  {   0.70196F,   0.61961F,   0.41961F },
  {   0.81176F,   0.65098F,   0.48627F },
  {   0.89412F,   0.66667F,   0.56078F },
  {   0.96078F,   0.72157F,   0.67843F },
  {   0.99608F,   0.81176F,   0.80000F },
  {   1.00000F,   0.90196F,   0.90196F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
