#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> VIK_8
{
  {   0.00000F,   0.07059F,   0.38039F },
  {   0.01176F,   0.29020F,   0.52157F },
  {   0.29412F,   0.56471F,   0.70196F },
  {   0.74118F,   0.83922F,   0.89020F },
  {   0.90588F,   0.77647F,   0.69804F },
  {   0.79216F,   0.50980F,   0.34510F },
  {   0.61176F,   0.21569F,   0.03529F },
  {   0.34902F,   0.00000F,   0.03137F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
