#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> VIRIDIS_12
{
  {   0.26667F,   0.00392F,   0.32941F },
  {   0.28235F,   0.12941F,   0.45098F },
  {   0.26275F,   0.24314F,   0.52157F },
  {   0.21961F,   0.34902F,   0.54902F },
  {   0.17647F,   0.43922F,   0.55686F },
  {   0.14510F,   0.52157F,   0.55686F },
  {   0.11765F,   0.60784F,   0.54118F },
  {   0.16471F,   0.69020F,   0.49804F },
  {   0.31373F,   0.76863F,   0.41569F },
  {   0.52549F,   0.83529F,   0.28627F },
  {   0.76078F,   0.87451F,   0.13725F },
  {   0.99216F,   0.90588F,   0.14510F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
