#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> YLGN_7
{
  {   1.00000F,   1.00000F,   0.80000F },
  {   0.85098F,   0.94118F,   0.63922F },
  {   0.67843F,   0.86667F,   0.55686F },
  {   0.47059F,   0.77647F,   0.47451F },
  {   0.25490F,   0.67059F,   0.36471F },
  {   0.13725F,   0.51765F,   0.26275F },
  {   0.00000F,   0.35294F,   0.19608F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
