#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> YLORBR_5
{
  {   1.00000F,   1.00000F,   0.83137F },
  {   0.99608F,   0.85098F,   0.55686F },
  {   0.99608F,   0.60000F,   0.16078F },
  {   0.85098F,   0.37255F,   0.05490F },
  {   0.60000F,   0.20392F,   0.01569F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
