#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> BATLOW_11
{
  {   0.00392F,   0.09804F,   0.34902F },
  {   0.05098F,   0.20392F,   0.36863F },
  {   0.09412F,   0.30980F,   0.38039F },
  {   0.19608F,   0.40000F,   0.35686F },
  {   0.34118F,   0.46275F,   0.27843F },
  {   0.50588F,   0.50980F,   0.20000F },
  {   0.69804F,   0.55294F,   0.19608F },
  {   0.89020F,   0.59608F,   0.33725F },
  {   0.98824F,   0.65490F,   0.55294F },
  {   0.99216F,   0.72549F,   0.76863F },
  {   0.98039F,   0.80000F,   0.98039F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
