#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> COLORBLIND_10
{
  {   0.00000F,   0.41961F,   0.64314F },
  {   1.00000F,   0.50196F,   0.05490F },
  {   0.67059F,   0.67059F,   0.67059F },
  {   0.34902F,   0.34902F,   0.34902F },
  {   0.37255F,   0.61961F,   0.81961F },
  {   0.78431F,   0.32157F,   0.00000F },
  {   0.53725F,   0.53725F,   0.53725F },
  {   0.63529F,   0.78431F,   0.92549F },
  {   1.00000F,   0.73725F,   0.47451F },
  {   0.81176F,   0.81176F,   0.81176F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
