#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> CUBE1_10
{
  {   0.47059F,   0.00000F,   0.52157F },
  {   0.50588F,   0.17647F,   0.82353F },
  {   0.40784F,   0.43529F,   0.98431F },
  {   0.29804F,   0.61961F,   0.85098F },
  {   0.24314F,   0.76078F,   0.62745F },
  {   0.32549F,   0.85882F,   0.36471F },
  {   0.52157F,   0.92157F,   0.31373F },
  {   0.76471F,   0.92549F,   0.34902F },
  {   0.90196F,   0.82353F,   0.36471F },
  {   0.97647F,   0.58824F,   0.35686F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
