#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> CURL_6
{
  {   0.08235F,   0.11373F,   0.26667F },
  {   0.06667F,   0.49020F,   0.47451F },
  {   0.71373F,   0.79608F,   0.68627F },
  {   0.90196F,   0.71765F,   0.63529F },
  {   0.68235F,   0.25098F,   0.37647F },
  {   0.20392F,   0.05098F,   0.20784F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
