#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> GRAYC_9
{
  {   1.00000F,   1.00000F,   1.00000F },
  {   0.85882F,   0.85882F,   0.85882F },
  {   0.72157F,   0.72157F,   0.72157F },
  {   0.59216F,   0.59216F,   0.59216F },
  {   0.46275F,   0.46275F,   0.46275F },
  {   0.34902F,   0.34902F,   0.34902F },
  {   0.23529F,   0.23529F,   0.23529F },
  {   0.12941F,   0.12941F,   0.12941F },
  {   0.00000F,   0.00000F,   0.00000F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
