#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> GREENMAGENTA_7
{
  {   0.00000F,   0.31373F,   0.00000F },
  {   0.00000F,   0.73333F,   0.00000F },
  {   0.52549F,   1.00000F,   0.52549F },
  {   1.00000F,   0.94510F,   1.00000F },
  {   1.00000F,   0.52549F,   1.00000F },
  {   0.94510F,   0.00000F,   0.94510F },
  {   0.31373F,   0.00000F,   0.31373F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
