#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> MARGOT1_5
{
  {   0.53725F,   0.46667F,   0.07059F },
  {   0.95294F,   0.76078F,   0.64314F },
  {   0.96471F,   0.62353F,   0.59216F },
  {   0.99608F,   0.83922F,   0.54902F },
  {   0.38431F,   0.56471F,   0.45882F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
