#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> ROMA_14
{
  {   0.49804F,   0.09804F,   0.00000F },
  {   0.58431F,   0.28627F,   0.06667F },
  {   0.65882F,   0.43529F,   0.12941F },
  {   0.73333F,   0.59216F,   0.20784F },
  {   0.81961F,   0.75686F,   0.34902F },
  {   0.88627F,   0.88235F,   0.56471F },
  {   0.85490F,   0.92157F,   0.73333F },
  {   0.71373F,   0.90980F,   0.82353F },
  {   0.49804F,   0.82745F,   0.84314F },
  {   0.34118F,   0.69412F,   0.80784F },
  {   0.26667F,   0.56471F,   0.75686F },
  {   0.21176F,   0.43529F,   0.70196F },
  {   0.16471F,   0.31765F,   0.65098F },
  {   0.10196F,   0.20000F,   0.60000F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
