#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> ROYAL2_5
{
  {   0.76078F,   0.67059F,   0.72941F },
  {   0.54902F,   0.23137F,   0.28627F },
  {   0.71373F,   0.67451F,   0.65098F },
  {   0.12941F,   0.12549F,   0.32549F },
  {   0.81961F,   0.82745F,   0.83529F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
