#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> TEMPO_17
{
  {   1.00000F,   0.96471F,   0.95686F },
  {   0.91373F,   0.90588F,   0.86667F },
  {   0.82353F,   0.85098F,   0.78039F },
  {   0.72941F,   0.80392F,   0.70196F },
  {   0.63137F,   0.75686F,   0.63137F },
  {   0.52549F,   0.71373F,   0.57647F },
  {   0.41176F,   0.67059F,   0.53725F },
  {   0.28627F,   0.62745F,   0.51373F },
  {   0.16471F,   0.57647F,   0.49804F },
  {   0.08627F,   0.52549F,   0.48627F },
  {   0.06667F,   0.46667F,   0.46667F },
  {   0.09020F,   0.40784F,   0.43922F },
  {   0.10588F,   0.34902F,   0.40784F },
  {   0.10980F,   0.29412F,   0.37255F },
  {   0.10588F,   0.23529F,   0.33725F },
  {   0.09412F,   0.17647F,   0.29804F },
  {   0.08235F,   0.11373F,   0.26667F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
