#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> TURBID_12
{
  {   0.91373F,   0.96471F,   0.67059F },
  {   0.86275F,   0.85882F,   0.54118F },
  {   0.82353F,   0.75686F,   0.42353F },
  {   0.78039F,   0.65490F,   0.32157F },
  {   0.73333F,   0.56078F,   0.26275F },
  {   0.67059F,   0.47843F,   0.23529F },
  {   0.59216F,   0.40784F,   0.22745F },
  {   0.50588F,   0.34510F,   0.22353F },
  {   0.41569F,   0.28627F,   0.20784F },
  {   0.31765F,   0.23137F,   0.18431F },
  {   0.22353F,   0.17647F,   0.14902F },
  {   0.13333F,   0.12157F,   0.10588F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
