#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> AQUATIC2_5
{
  {   0.54510F,   0.61176F,   0.72157F },
  {   0.91373F,   0.89804F,   0.25490F },
  {   0.34510F,   0.62353F,   0.76078F },
  {   0.62745F,   0.55294F,   0.36863F },
  {   0.74118F,   0.72549F,   0.80784F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
