#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> GRAYC_11
{
  {   1.00000F,   1.00000F,   1.00000F },
  {   0.88627F,   0.88627F,   0.88627F },
  {   0.77647F,   0.77647F,   0.77647F },
  {   0.67451F,   0.67451F,   0.67451F },
  {   0.56863F,   0.56863F,   0.56863F },
  {   0.46275F,   0.46275F,   0.46275F },
  {   0.36863F,   0.36863F,   0.36863F },
  {   0.27843F,   0.27843F,   0.27843F },
  {   0.18824F,   0.18824F,   0.18824F },
  {   0.10588F,   0.10588F,   0.10588F },
  {   0.00000F,   0.00000F,   0.00000F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
