#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> GREYS_5
{
  {   0.96863F,   0.96863F,   0.96863F },
  {   0.80000F,   0.80000F,   0.80000F },
  {   0.58824F,   0.58824F,   0.58824F },
  {   0.38824F,   0.38824F,   0.38824F },
  {   0.14510F,   0.14510F,   0.14510F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
