#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> IMOLA_17
{
  {   0.10196F,   0.20000F,   0.70196F },
  {   0.12549F,   0.24314F,   0.67843F },
  {   0.14510F,   0.28627F,   0.65882F },
  {   0.16863F,   0.32549F,   0.63529F },
  {   0.18824F,   0.36863F,   0.61569F },
  {   0.21569F,   0.40784F,   0.58824F },
  {   0.24706F,   0.44314F,   0.55686F },
  {   0.28235F,   0.48235F,   0.52549F },
  {   0.32941F,   0.52549F,   0.49804F },
  {   0.38039F,   0.57647F,   0.48235F },
  {   0.43922F,   0.63922F,   0.46667F },
  {   0.50196F,   0.70196F,   0.45098F },
  {   0.56863F,   0.76471F,   0.43529F },
  {   0.63922F,   0.83529F,   0.41961F },
  {   0.74118F,   0.90196F,   0.40392F },
  {   0.86667F,   0.95686F,   0.40000F },
  {   1.00000F,   1.00000F,   0.40000F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
