#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> LAPAZ_10
{
  {   0.10196F,   0.04706F,   0.39216F },
  {   0.13725F,   0.17647F,   0.48235F },
  {   0.16471F,   0.29804F,   0.56078F },
  {   0.21176F,   0.40392F,   0.61569F },
  {   0.29804F,   0.50196F,   0.63922F },
  {   0.43137F,   0.58431F,   0.63137F },
  {   0.58039F,   0.63529F,   0.59608F },
  {   0.74902F,   0.69412F,   0.60000F },
  {   0.93725F,   0.82745F,   0.75294F },
  {   0.99608F,   0.94902F,   0.95294F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
