#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> MAGENTA_6
{
  {   0.95294F,   0.79608F,   0.82745F },
  {   0.91765F,   0.66275F,   0.74118F },
  {   0.86667F,   0.53333F,   0.67451F },
  {   0.69412F,   0.30196F,   0.55686F },
  {   0.56863F,   0.20784F,   0.49020F },
  {   0.42353F,   0.12941F,   0.40392F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
