#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> PUBU_3
{
  {   0.92549F,   0.90588F,   0.94902F },
  {   0.65098F,   0.74118F,   0.85882F },
  {   0.16863F,   0.54902F,   0.74510F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
