#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> THERMAL_10
{
  {   0.01569F,   0.13725F,   0.20000F },
  {   0.07451F,   0.20000F,   0.44706F },
  {   0.29412F,   0.21569F,   0.62353F },
  {   0.45490F,   0.28627F,   0.57255F },
  {   0.60392F,   0.34510F,   0.53725F },
  {   0.77647F,   0.40000F,   0.46667F },
  {   0.92157F,   0.47451F,   0.34510F },
  {   0.98431F,   0.61176F,   0.24314F },
  {   0.97255F,   0.79608F,   0.26275F },
  {   0.90980F,   0.98039F,   0.35686F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
