#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> BILBAO_17
{
  {   1.00000F,   1.00000F,   1.00000F },
  {   0.91765F,   0.91765F,   0.91765F },
  {   0.84314F,   0.84314F,   0.82745F },
  {   0.79216F,   0.78039F,   0.73725F },
  {   0.76078F,   0.73725F,   0.65098F },
  {   0.73333F,   0.69804F,   0.56863F },
  {   0.70980F,   0.64706F,   0.48627F },
  {   0.68235F,   0.58431F,   0.42745F },
  {   0.66667F,   0.52549F,   0.39608F },
  {   0.65098F,   0.47451F,   0.37647F },
  {   0.63529F,   0.41961F,   0.34902F },
  {   0.61569F,   0.36078F,   0.32157F },
  {   0.57647F,   0.29412F,   0.27843F },
  {   0.51765F,   0.22353F,   0.21961F },
  {   0.45098F,   0.15294F,   0.14902F },
  {   0.37647F,   0.08235F,   0.08627F },
  {   0.30196F,   0.00000F,   0.00392F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
