#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> BRBG_7
{
  {   0.54902F,   0.31765F,   0.03922F },
  {   0.84706F,   0.70196F,   0.39608F },
  {   0.96471F,   0.90980F,   0.76471F },
  {   0.96078F,   0.96078F,   0.96078F },
  {   0.78039F,   0.91765F,   0.89804F },
  {   0.35294F,   0.70588F,   0.67451F },
  {   0.00392F,   0.40000F,   0.36863F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
