#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> BROC_11
{
  {   0.17255F,   0.10196F,   0.29804F },
  {   0.15686F,   0.25490F,   0.45490F },
  {   0.24706F,   0.41961F,   0.60000F },
  {   0.46275F,   0.59216F,   0.71765F },
  {   0.70196F,   0.77255F,   0.84314F },
  {   0.92157F,   0.93333F,   0.92549F },
  {   0.86275F,   0.85882F,   0.72157F },
  {   0.71373F,   0.71373F,   0.48627F },
  {   0.50588F,   0.50588F,   0.29804F },
  {   0.31373F,   0.31373F,   0.13725F },
  {   0.14902F,   0.14902F,   0.00000F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
