#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> BUDA_9
{
  {   0.70196F,   0.00392F,   0.70196F },
  {   0.70196F,   0.18431F,   0.61176F },
  {   0.73725F,   0.30588F,   0.56471F },
  {   0.77255F,   0.41569F,   0.52941F },
  {   0.80392F,   0.52157F,   0.49412F },
  {   0.83137F,   0.62745F,   0.46667F },
  {   0.85882F,   0.74118F,   0.43922F },
  {   0.89020F,   0.85882F,   0.41176F },
  {   1.00000F,   1.00000F,   0.40000F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
