#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> BUPU_9
{
  {   0.96863F,   0.98824F,   0.99216F },
  {   0.87843F,   0.92549F,   0.95686F },
  {   0.74902F,   0.82745F,   0.90196F },
  {   0.61961F,   0.73725F,   0.85490F },
  {   0.54902F,   0.58824F,   0.77647F },
  {   0.54902F,   0.41961F,   0.69412F },
  {   0.53333F,   0.25490F,   0.61569F },
  {   0.50588F,   0.05882F,   0.48627F },
  {   0.30196F,   0.00000F,   0.29412F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
