#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> CAVALCANTI_5
{
  {   0.81961F,   0.66667F,   0.00000F },
  {   0.03137F,   0.19608F,   0.07451F },
  {   0.57255F,   0.58039F,   0.37647F },
  {   0.43529F,   0.59608F,   0.47451F },
  {   0.51765F,   0.12941F,   0.06667F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
