#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> DAVOS_6
{
  {   0.00000F,   0.01961F,   0.29020F },
  {   0.13725F,   0.29020F,   0.54902F },
  {   0.32941F,   0.49020F,   0.61176F },
  {   0.51765F,   0.61961F,   0.53725F },
  {   0.83137F,   0.85882F,   0.65882F },
  {   0.99608F,   0.99608F,   0.99608F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
