#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> DEEP_13
{
  {   0.99216F,   0.99608F,   0.80000F },
  {   0.82353F,   0.93333F,   0.70980F },
  {   0.64706F,   0.87451F,   0.65490F },
  {   0.47059F,   0.80784F,   0.63922F },
  {   0.36471F,   0.72941F,   0.64314F },
  {   0.31373F,   0.64314F,   0.63529F },
  {   0.28235F,   0.55686F,   0.61961F },
  {   0.25882F,   0.47451F,   0.60000F },
  {   0.24314F,   0.39216F,   0.58431F },
  {   0.25098F,   0.30196F,   0.54902F },
  {   0.25098F,   0.22745F,   0.43137F },
  {   0.20784F,   0.16471F,   0.29020F },
  {   0.15686F,   0.10196F,   0.17255F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
