#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> DENSE_8
{
  {   0.90196F,   0.94510F,   0.94510F },
  {   0.67059F,   0.82745F,   0.89020F },
  {   0.49412F,   0.69020F,   0.89412F },
  {   0.45490F,   0.53333F,   0.88235F },
  {   0.47451F,   0.36078F,   0.76471F },
  {   0.45098F,   0.21569F,   0.57647F },
  {   0.36471F,   0.10196F,   0.34510F },
  {   0.21176F,   0.05490F,   0.14118F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
