#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> GRAY_15
{
  {   0.00000F,   0.00000F,   0.00000F },
  {   0.04314F,   0.04314F,   0.04314F },
  {   0.11373F,   0.11373F,   0.11373F },
  {   0.18431F,   0.18431F,   0.18039F },
  {   0.24706F,   0.24706F,   0.24706F },
  {   0.31373F,   0.30980F,   0.30980F },
  {   0.37647F,   0.37255F,   0.37255F },
  {   0.44706F,   0.44314F,   0.44314F },
  {   0.51373F,   0.50980F,   0.50980F },
  {   0.58431F,   0.58039F,   0.58039F },
  {   0.65490F,   0.65490F,   0.65098F },
  {   0.73333F,   0.73333F,   0.72941F },
  {   0.81961F,   0.81961F,   0.81569F },
  {   0.90588F,   0.90588F,   0.90196F },
  {   1.00000F,   1.00000F,   0.99216F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
