#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> GRAY_7
{
  {   0.00000F,   0.00000F,   0.00000F },
  {   0.13725F,   0.13725F,   0.13725F },
  {   0.29020F,   0.29020F,   0.28627F },
  {   0.44706F,   0.44314F,   0.44314F },
  {   0.60784F,   0.60392F,   0.60392F },
  {   0.78824F,   0.78431F,   0.78039F },
  {   1.00000F,   1.00000F,   0.99216F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
