#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> HAWAII_5
{
  {   0.54902F,   0.00784F,   0.45098F },
  {   0.59216F,   0.30588F,   0.24314F },
  {   0.61176F,   0.58824F,   0.10980F },
  {   0.42353F,   0.83137F,   0.54902F },
  {   0.70196F,   0.94902F,   0.99216F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
