#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> HAWAII_6
{
  {   0.54902F,   0.00784F,   0.45098F },
  {   0.58431F,   0.25490F,   0.27843F },
  {   0.61176F,   0.45882F,   0.14118F },
  {   0.56078F,   0.71373F,   0.23529F },
  {   0.38431F,   0.86275F,   0.66275F },
  {   0.70196F,   0.94902F,   0.99216F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
