#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> HAWAII_10
{
  {   0.54902F,   0.00784F,   0.45098F },
  {   0.57255F,   0.16471F,   0.34902F },
  {   0.58824F,   0.27843F,   0.25882F },
  {   0.60000F,   0.38824F,   0.18824F },
  {   0.61569F,   0.51373F,   0.11765F },
  {   0.59216F,   0.66275F,   0.16471F },
  {   0.50196F,   0.77255F,   0.37255F },
  {   0.40000F,   0.84706F,   0.61176F },
  {   0.42353F,   0.92157F,   0.85882F },
  {   0.70196F,   0.94902F,   0.99216F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
