#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> LAJOLLA_6
{
  {   1.00000F,   1.00000F,   0.80000F },
  {   0.96471F,   0.83137F,   0.43922F },
  {   0.90588F,   0.58039F,   0.32157F },
  {   0.76078F,   0.33333F,   0.29020F },
  {   0.40784F,   0.20784F,   0.16471F },
  {   0.10196F,   0.10196F,   0.00392F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
