#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> LISBON_12
{
  {   0.90196F,   0.89804F,   1.00000F },
  {   0.65882F,   0.72549F,   0.85490F },
  {   0.42745F,   0.55294F,   0.71373F },
  {   0.20392F,   0.36863F,   0.54118F },
  {   0.09020F,   0.21569F,   0.33725F },
  {   0.06667F,   0.10588F,   0.15294F },
  {   0.13725F,   0.12941F,   0.09412F },
  {   0.28235F,   0.26667F,   0.16863F },
  {   0.45098F,   0.42353F,   0.27059F },
  {   0.64314F,   0.61176F,   0.41176F },
  {   0.82745F,   0.80392F,   0.61569F },
  {   1.00000F,   1.00000F,   0.85098F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
