#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> LISBON_7
{
  {   0.90196F,   0.89804F,   1.00000F },
  {   0.46667F,   0.58039F,   0.74118F },
  {   0.11765F,   0.26275F,   0.40784F },
  {   0.09020F,   0.09804F,   0.09804F },
  {   0.34118F,   0.31765F,   0.20392F },
  {   0.67059F,   0.63529F,   0.43137F },
  {   1.00000F,   1.00000F,   0.85098F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
