#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> OLERON_6
{
  {   0.10196F,   0.14902F,   0.34902F },
  {   0.42353F,   0.47451F,   0.67451F },
  {   0.76863F,   0.81961F,   0.96471F },
  {   0.32549F,   0.36863F,   0.00784F },
  {   0.77255F,   0.64314F,   0.42353F },
  {   0.99216F,   0.99216F,   0.90196F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
