#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> OSLO_12
{
  {   0.00392F,   0.00392F,   0.00392F },
  {   0.05098F,   0.09020F,   0.13725F },
  {   0.06275F,   0.16078F,   0.25490F },
  {   0.09412F,   0.24314F,   0.39216F },
  {   0.14118F,   0.32941F,   0.53333F },
  {   0.23922F,   0.42353F,   0.67451F },
  {   0.38039F,   0.52941F,   0.77255F },
  {   0.49804F,   0.60784F,   0.79216F },
  {   0.60392F,   0.67451F,   0.78824F },
  {   0.72549F,   0.75686F,   0.80392F },
  {   0.85882F,   0.86667F,   0.87843F },
  {   1.00000F,   1.00000F,   1.00000F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
