#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> OXY_20
{
  {   0.25098F,   0.01961F,   0.01961F },
  {   0.33333F,   0.02745F,   0.04314F },
  {   0.42745F,   0.02353F,   0.05882F },
  {   0.51373F,   0.03137F,   0.04706F },
  {   0.32157F,   0.31765F,   0.31765F },
  {   0.37255F,   0.36863F,   0.36863F },
  {   0.41961F,   0.41961F,   0.41569F },
  {   0.47059F,   0.46667F,   0.46667F },
  {   0.52157F,   0.52157F,   0.51765F },
  {   0.57647F,   0.57647F,   0.57255F },
  {   0.63529F,   0.63137F,   0.62745F },
  {   0.69412F,   0.69020F,   0.68627F },
  {   0.75294F,   0.75294F,   0.74902F },
  {   0.81176F,   0.81176F,   0.80784F },
  {   0.87843F,   0.87843F,   0.87451F },
  {   0.94902F,   0.94902F,   0.94510F },
  {   0.91765F,   0.94510F,   0.27059F },
  {   0.90980F,   0.85098F,   0.18039F },
  {   0.89020F,   0.76471F,   0.13333F },
  {   0.86667F,   0.68627F,   0.09804F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
