#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> PHASE_7
{
  {   0.65882F,   0.47059F,   0.05098F },
  {   0.84314F,   0.28627F,   0.34118F },
  {   0.81569F,   0.18431F,   0.81569F },
  {   0.49020F,   0.45098F,   0.94118F },
  {   0.11765F,   0.57647F,   0.65882F },
  {   0.19216F,   0.60000F,   0.27451F },
  {   0.65882F,   0.47059F,   0.05098F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
