#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> PUBUGN_7
{
  {   0.96471F,   0.93725F,   0.96863F },
  {   0.81569F,   0.81961F,   0.90196F },
  {   0.65098F,   0.74118F,   0.85882F },
  {   0.40392F,   0.66275F,   0.81176F },
  {   0.21176F,   0.56471F,   0.75294F },
  {   0.00784F,   0.50588F,   0.54118F },
  {   0.00392F,   0.39216F,   0.31373F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
