#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> PUBU_9
{
  {   1.00000F,   0.96863F,   0.98431F },
  {   0.92549F,   0.90588F,   0.94902F },
  {   0.81569F,   0.81961F,   0.90196F },
  {   0.65098F,   0.74118F,   0.85882F },
  {   0.45490F,   0.66275F,   0.81176F },
  {   0.21176F,   0.56471F,   0.75294F },
  {   0.01961F,   0.43922F,   0.69020F },
  {   0.01569F,   0.35294F,   0.55294F },
  {   0.00784F,   0.21961F,   0.34510F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
