#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> RDBU_7
{
  {   0.69804F,   0.09412F,   0.16863F },
  {   0.93725F,   0.54118F,   0.38431F },
  {   0.99216F,   0.85882F,   0.78039F },
  {   0.96863F,   0.96863F,   0.96863F },
  {   0.81961F,   0.89804F,   0.94118F },
  {   0.40392F,   0.66275F,   0.81176F },
  {   0.12941F,   0.40000F,   0.67451F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
