#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> SOLAR_19
{
  {   0.20000F,   0.07843F,   0.09412F },
  {   0.27059F,   0.10196F,   0.11765F },
  {   0.33725F,   0.12157F,   0.13725F },
  {   0.40784F,   0.13725F,   0.14510F },
  {   0.47843F,   0.16078F,   0.14118F },
  {   0.54118F,   0.19216F,   0.12549F },
  {   0.59216F,   0.23137F,   0.10980F },
  {   0.63922F,   0.28235F,   0.09412F },
  {   0.67843F,   0.33333F,   0.08235F },
  {   0.71373F,   0.39216F,   0.07451F },
  {   0.74510F,   0.45098F,   0.07451F },
  {   0.77255F,   0.50980F,   0.08235F },
  {   0.79608F,   0.57255F,   0.10196F },
  {   0.81961F,   0.63529F,   0.12549F },
  {   0.83922F,   0.70196F,   0.15294F },
  {   0.85490F,   0.76863F,   0.18431F },
  {   0.86667F,   0.84314F,   0.21961F },
  {   0.87843F,   0.91765F,   0.25490F },
  {   0.88235F,   0.99216F,   0.29412F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
