#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> TEMPO_15
{
  {   1.00000F,   0.96471F,   0.95686F },
  {   0.90196F,   0.89804F,   0.85490F },
  {   0.80000F,   0.83922F,   0.75686F },
  {   0.69020F,   0.78431F,   0.67059F },
  {   0.57255F,   0.73333F,   0.60000F },
  {   0.44706F,   0.68627F,   0.54902F },
  {   0.31373F,   0.63529F,   0.51765F },
  {   0.16471F,   0.57647F,   0.49804F },
  {   0.07451F,   0.51765F,   0.48235F },
  {   0.07451F,   0.45098F,   0.45882F },
  {   0.09804F,   0.38431F,   0.42745F },
  {   0.10980F,   0.31765F,   0.38824F },
  {   0.10980F,   0.25098F,   0.34510F },
  {   0.09804F,   0.18431F,   0.30196F },
  {   0.08235F,   0.11373F,   0.26667F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
