#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> TROPIC_5
{
  {   0.00000F,   0.60784F,   0.61961F },
  {   0.65490F,   0.82745F,   0.83137F },
  {   0.94510F,   0.94510F,   0.94510F },
  {   0.89412F,   0.75686F,   0.85098F },
  {   0.78039F,   0.36471F,   0.67059F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
