#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY 'lib/goomutils/src/create_colormaps.py' - DO NOT EDIT

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace UTILS
{
namespace COLOR_DATA
{
#else
namespace GOOM::UTILS::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> TURBID_6
{
  {   0.91373F,   0.96471F,   0.67059F },
  {   0.81176F,   0.73725F,   0.40000F },
  {   0.70980F,   0.52941F,   0.25098F },
  {   0.54118F,   0.36863F,   0.22745F },
  {   0.33725F,   0.24314F,   0.18824F },
  {   0.13333F,   0.12157F,   0.10588F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace UTILS
} // namespace GOOM
#else
} // namespace GOOM::UTILS::COLOR_DATA
#endif
