#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// NOLINTNEXTLINE(cert-err58-cpp): Fix with C++20 and 'constexpr'.
inline const auto ACCENT_3 = std::vector<vivid::srgb_t>{
    {0.49804F, 0.78824F, 0.49804F},
    {0.74510F, 0.68235F, 0.83137F},
    {0.99216F, 0.75294F, 0.52549F},
};

} // namespace GOOM::COLOR::COLOR_DATA
