#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_ACCENT_5 = std::array{
    vivid::srgb_t{0.49804F, 0.78824F, 0.49804F},
    vivid::srgb_t{0.74510F, 0.68235F, 0.83137F},
    vivid::srgb_t{0.99216F, 0.75294F, 0.52549F},
    vivid::srgb_t{1.00000F, 1.00000F, 0.60000F},
    vivid::srgb_t{0.21961F, 0.42353F, 0.69020F},
};

} // namespace GOOM::COLOR::COLOR_DATA
