#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_ACTON_16 = std::array{
    vivid::srgb_t{0.18039F, 0.12941F, 0.30196F},
    vivid::srgb_t{0.24706F, 0.18824F, 0.36078F},
    vivid::srgb_t{0.32157F, 0.25098F, 0.42353F},
    vivid::srgb_t{0.40000F, 0.31373F, 0.48235F},
    vivid::srgb_t{0.49020F, 0.36078F, 0.53333F},
    vivid::srgb_t{0.57255F, 0.38824F, 0.56471F},
    vivid::srgb_t{0.65098F, 0.40000F, 0.58039F},
    vivid::srgb_t{0.72549F, 0.41176F, 0.59216F},
    vivid::srgb_t{0.80000F, 0.45882F, 0.63137F},
    vivid::srgb_t{0.83137F, 0.52549F, 0.67843F},
    vivid::srgb_t{0.83137F, 0.58431F, 0.72157F},
    vivid::srgb_t{0.82745F, 0.63922F, 0.76078F},
    vivid::srgb_t{0.83529F, 0.69804F, 0.80392F},
    vivid::srgb_t{0.85098F, 0.76471F, 0.84706F},
    vivid::srgb_t{0.87451F, 0.83137F, 0.89412F},
    vivid::srgb_t{0.90196F, 0.90196F, 0.94118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
