#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_ACTON_9 = std::array{
    vivid::srgb_t{0.18039F, 0.12941F, 0.30196F},
    vivid::srgb_t{0.31373F, 0.24314F, 0.41569F},
    vivid::srgb_t{0.46667F, 0.35294F, 0.52549F},
    vivid::srgb_t{0.62353F, 0.39608F, 0.57647F},
    vivid::srgb_t{0.76863F, 0.43137F, 0.60784F},
    vivid::srgb_t{0.83529F, 0.54902F, 0.69412F},
    vivid::srgb_t{0.83137F, 0.65098F, 0.76863F},
    vivid::srgb_t{0.85490F, 0.77255F, 0.85098F},
    vivid::srgb_t{0.90196F, 0.90196F, 0.94118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
