#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_ACTON_10 = std::array{
    vivid::srgb_t{0.18039F, 0.12941F, 0.30196F},
    vivid::srgb_t{0.29412F, 0.23137F, 0.40000F},
    vivid::srgb_t{0.43137F, 0.32941F, 0.50196F},
    vivid::srgb_t{0.57255F, 0.38824F, 0.56471F},
    vivid::srgb_t{0.69804F, 0.40392F, 0.58431F},
    vivid::srgb_t{0.81961F, 0.48235F, 0.64706F},
    vivid::srgb_t{0.83137F, 0.58431F, 0.72157F},
    vivid::srgb_t{0.83137F, 0.67843F, 0.78824F},
    vivid::srgb_t{0.85882F, 0.78824F, 0.86275F},
    vivid::srgb_t{0.90196F, 0.90196F, 0.94118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
