#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_ACTON_6 = std::array{
    vivid::srgb_t{0.18039F, 0.12941F, 0.30196F},
    vivid::srgb_t{0.40000F, 0.31373F, 0.48235F},
    vivid::srgb_t{0.65098F, 0.40000F, 0.58039F},
    vivid::srgb_t{0.83137F, 0.52549F, 0.67843F},
    vivid::srgb_t{0.83529F, 0.69804F, 0.80392F},
    vivid::srgb_t{0.90196F, 0.90196F, 0.94118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
