#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_ACTON_13 = std::array{
    vivid::srgb_t{0.18039F, 0.12941F, 0.30196F},
    vivid::srgb_t{0.26667F, 0.20392F, 0.37647F},
    vivid::srgb_t{0.35686F, 0.28235F, 0.45098F},
    vivid::srgb_t{0.46667F, 0.35294F, 0.52549F},
    vivid::srgb_t{0.57255F, 0.38824F, 0.56471F},
    vivid::srgb_t{0.66667F, 0.40000F, 0.58039F},
    vivid::srgb_t{0.76863F, 0.43137F, 0.60784F},
    vivid::srgb_t{0.83137F, 0.50980F, 0.66667F},
    vivid::srgb_t{0.83137F, 0.58431F, 0.72157F},
    vivid::srgb_t{0.83137F, 0.65098F, 0.76863F},
    vivid::srgb_t{0.84314F, 0.72941F, 0.82353F},
    vivid::srgb_t{0.87059F, 0.81569F, 0.88235F},
    vivid::srgb_t{0.90196F, 0.90196F, 0.94118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
