#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_ALGAE_17 = std::array{
    vivid::srgb_t{0.84314F, 0.97647F, 0.81569F},
    vivid::srgb_t{0.76471F, 0.92157F, 0.72549F},
    vivid::srgb_t{0.68627F, 0.86667F, 0.63529F},
    vivid::srgb_t{0.60392F, 0.81569F, 0.55294F},
    vivid::srgb_t{0.51765F, 0.76863F, 0.47843F},
    vivid::srgb_t{0.42353F, 0.72157F, 0.40784F},
    vivid::srgb_t{0.31373F, 0.67843F, 0.34902F},
    vivid::srgb_t{0.18039F, 0.63137F, 0.32157F},
    vivid::srgb_t{0.07059F, 0.58039F, 0.31373F},
    vivid::srgb_t{0.02745F, 0.52549F, 0.30196F},
    vivid::srgb_t{0.04706F, 0.47059F, 0.28627F},
    vivid::srgb_t{0.07843F, 0.41569F, 0.26275F},
    vivid::srgb_t{0.09412F, 0.35686F, 0.23137F},
    vivid::srgb_t{0.10196F, 0.30196F, 0.20000F},
    vivid::srgb_t{0.09804F, 0.25098F, 0.16078F},
    vivid::srgb_t{0.08627F, 0.19608F, 0.12157F},
    vivid::srgb_t{0.07059F, 0.14118F, 0.07843F},
};

} // namespace GOOM::COLOR::COLOR_DATA
