#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_AMP_15 = std::array{
    vivid::srgb_t{0.94510F, 0.92941F, 0.92549F},
    vivid::srgb_t{0.90980F, 0.84706F, 0.82745F},
    vivid::srgb_t{0.88235F, 0.76471F, 0.72549F},
    vivid::srgb_t{0.85490F, 0.67843F, 0.61961F},
    vivid::srgb_t{0.83137F, 0.59608F, 0.51765F},
    vivid::srgb_t{0.80784F, 0.51765F, 0.41569F},
    vivid::srgb_t{0.78039F, 0.43529F, 0.32157F},
    vivid::srgb_t{0.75294F, 0.34510F, 0.23137F},
    vivid::srgb_t{0.71765F, 0.25490F, 0.16471F},
    vivid::srgb_t{0.67059F, 0.16471F, 0.14118F},
    vivid::srgb_t{0.60392F, 0.08627F, 0.15294F},
    vivid::srgb_t{0.51765F, 0.05490F, 0.16078F},
    vivid::srgb_t{0.41961F, 0.05882F, 0.14510F},
    vivid::srgb_t{0.32549F, 0.05098F, 0.11373F},
    vivid::srgb_t{0.23529F, 0.03529F, 0.07059F},
};

} // namespace GOOM::COLOR::COLOR_DATA
