#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_AMP_12 = std::array{
    vivid::srgb_t{0.94510F, 0.92941F, 0.92549F},
    vivid::srgb_t{0.90196F, 0.82353F, 0.80000F},
    vivid::srgb_t{0.86667F, 0.71765F, 0.67059F},
    vivid::srgb_t{0.83529F, 0.61176F, 0.53333F},
    vivid::srgb_t{0.80392F, 0.50588F, 0.40784F},
    vivid::srgb_t{0.77255F, 0.40392F, 0.28627F},
    vivid::srgb_t{0.73333F, 0.29020F, 0.18824F},
    vivid::srgb_t{0.67843F, 0.17255F, 0.14118F},
    vivid::srgb_t{0.59216F, 0.07843F, 0.15686F},
    vivid::srgb_t{0.47059F, 0.05490F, 0.15686F},
    vivid::srgb_t{0.35294F, 0.05490F, 0.12157F},
    vivid::srgb_t{0.23529F, 0.03529F, 0.07059F},
};

} // namespace GOOM::COLOR::COLOR_DATA
