#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_AMP_19 = std::array{
    vivid::srgb_t{0.94510F, 0.92941F, 0.92549F},
    vivid::srgb_t{0.91765F, 0.86275F, 0.85098F},
    vivid::srgb_t{0.89412F, 0.80000F, 0.77255F},
    vivid::srgb_t{0.87451F, 0.73725F, 0.69020F},
    vivid::srgb_t{0.85098F, 0.66667F, 0.60784F},
    vivid::srgb_t{0.83529F, 0.60392F, 0.52941F},
    vivid::srgb_t{0.81569F, 0.54510F, 0.45098F},
    vivid::srgb_t{0.79608F, 0.47843F, 0.37647F},
    vivid::srgb_t{0.77647F, 0.41569F, 0.30196F},
    vivid::srgb_t{0.75294F, 0.34510F, 0.23137F},
    vivid::srgb_t{0.72549F, 0.27451F, 0.17647F},
    vivid::srgb_t{0.69412F, 0.20392F, 0.14510F},
    vivid::srgb_t{0.65098F, 0.13333F, 0.14510F},
    vivid::srgb_t{0.59608F, 0.08235F, 0.15294F},
    vivid::srgb_t{0.52941F, 0.05490F, 0.16078F},
    vivid::srgb_t{0.45490F, 0.05490F, 0.15686F},
    vivid::srgb_t{0.37647F, 0.05490F, 0.13333F},
    vivid::srgb_t{0.30588F, 0.05098F, 0.10196F},
    vivid::srgb_t{0.23529F, 0.03529F, 0.07059F},
};

} // namespace GOOM::COLOR::COLOR_DATA
