#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_AMP_6 = std::array{
    vivid::srgb_t{0.94510F, 0.92941F, 0.92549F},
    vivid::srgb_t{0.86275F, 0.69412F, 0.63922F},
    vivid::srgb_t{0.79216F, 0.46667F, 0.35686F},
    vivid::srgb_t{0.70196F, 0.21961F, 0.14902F},
    vivid::srgb_t{0.49804F, 0.05490F, 0.16078F},
    vivid::srgb_t{0.23529F, 0.03529F, 0.07059F},
};

} // namespace GOOM::COLOR::COLOR_DATA
