#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_AQUATIC1_5 = std::array{
    vivid::srgb_t{0.20392F, 0.14118F, 0.09804F},
    vivid::srgb_t{0.10980F, 0.25098F, 0.15294F},
    vivid::srgb_t{0.94510F, 0.78824F, 0.05490F},
    vivid::srgb_t{0.40000F, 0.34510F, 0.60000F},
    vivid::srgb_t{0.72157F, 0.57647F, 0.50980F},
};

} // namespace GOOM::COLOR::COLOR_DATA
