#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_ARMYROSE_4 = std::array{
    vivid::srgb_t{0.47451F, 0.50980F, 0.20392F},
    vivid::srgb_t{0.81569F, 0.82745F, 0.63529F},
    vivid::srgb_t{0.94118F, 0.77647F, 0.76471F},
    vivid::srgb_t{0.83137F, 0.40392F, 0.50196F},
};

} // namespace GOOM::COLOR::COLOR_DATA
