#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BALANCE_7 = std::array{
    vivid::srgb_t{0.09412F, 0.10980F, 0.26275F},
    vivid::srgb_t{0.04706F, 0.36863F, 0.74510F},
    vivid::srgb_t{0.45882F, 0.66667F, 0.74510F},
    vivid::srgb_t{0.94510F, 0.92549F, 0.92157F},
    vivid::srgb_t{0.81569F, 0.54510F, 0.45098F},
    vivid::srgb_t{0.65490F, 0.14118F, 0.14118F},
    vivid::srgb_t{0.23529F, 0.03529F, 0.07059F},
};

} // namespace GOOM::COLOR::COLOR_DATA
