#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BALANCE_19 = std::array{
    vivid::srgb_t{0.09412F, 0.10980F, 0.26275F},
    vivid::srgb_t{0.14510F, 0.18431F, 0.43529F},
    vivid::srgb_t{0.16078F, 0.25882F, 0.63529F},
    vivid::srgb_t{0.04706F, 0.36863F, 0.74510F},
    vivid::srgb_t{0.14902F, 0.48235F, 0.72941F},
    vivid::srgb_t{0.29412F, 0.58039F, 0.72941F},
    vivid::srgb_t{0.45882F, 0.66667F, 0.74510F},
    vivid::srgb_t{0.63137F, 0.74510F, 0.78431F},
    vivid::srgb_t{0.79216F, 0.83137F, 0.84706F},
    vivid::srgb_t{0.94510F, 0.92549F, 0.92157F},
    vivid::srgb_t{0.89412F, 0.79608F, 0.76863F},
    vivid::srgb_t{0.85490F, 0.67059F, 0.60784F},
    vivid::srgb_t{0.81569F, 0.54510F, 0.45098F},
    vivid::srgb_t{0.77647F, 0.41961F, 0.30196F},
    vivid::srgb_t{0.72941F, 0.28235F, 0.18039F},
    vivid::srgb_t{0.65490F, 0.14118F, 0.14118F},
    vivid::srgb_t{0.52549F, 0.05490F, 0.16078F},
    vivid::srgb_t{0.37647F, 0.05490F, 0.13333F},
    vivid::srgb_t{0.23529F, 0.03529F, 0.07059F},
};

} // namespace GOOM::COLOR::COLOR_DATA
