#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BALANCE_17 = std::array{
    vivid::srgb_t{0.09412F, 0.10980F, 0.26275F},
    vivid::srgb_t{0.14902F, 0.19608F, 0.46275F},
    vivid::srgb_t{0.14510F, 0.28235F, 0.69020F},
    vivid::srgb_t{0.05882F, 0.41569F, 0.74118F},
    vivid::srgb_t{0.21961F, 0.53333F, 0.72941F},
    vivid::srgb_t{0.39608F, 0.63529F, 0.73725F},
    vivid::srgb_t{0.59608F, 0.72941F, 0.77255F},
    vivid::srgb_t{0.78039F, 0.82353F, 0.84314F},
    vivid::srgb_t{0.94510F, 0.92549F, 0.92157F},
    vivid::srgb_t{0.89020F, 0.78824F, 0.75686F},
    vivid::srgb_t{0.84706F, 0.64314F, 0.57647F},
    vivid::srgb_t{0.80392F, 0.49804F, 0.39608F},
    vivid::srgb_t{0.75294F, 0.35294F, 0.23529F},
    vivid::srgb_t{0.68627F, 0.18824F, 0.14118F},
    vivid::srgb_t{0.56471F, 0.06275F, 0.16078F},
    vivid::srgb_t{0.39608F, 0.05882F, 0.14118F},
    vivid::srgb_t{0.23529F, 0.03529F, 0.07059F},
};

} // namespace GOOM::COLOR::COLOR_DATA
