#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> BAMAKO_14
{
  {   0.00000F,   0.25098F,   0.29804F },
  {   0.05490F,   0.28235F,   0.27059F },
  {   0.10196F,   0.30980F,   0.24314F },
  {   0.15294F,   0.34510F,   0.21176F },
  {   0.20784F,   0.38039F,   0.17647F },
  {   0.27059F,   0.41961F,   0.14118F },
  {   0.34118F,   0.46667F,   0.10196F },
  {   0.41961F,   0.51765F,   0.05490F },
  {   0.52157F,   0.55686F,   0.01176F },
  {   0.63137F,   0.58824F,   0.05882F },
  {   0.75686F,   0.67059F,   0.18039F },
  {   0.86275F,   0.76078F,   0.32941F },
  {   0.93333F,   0.83137F,   0.46275F },
  {   1.00000F,   0.89804F,   0.60000F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
