#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BAMAKO_3 = std::array{
    vivid::srgb_t{0.00000F, 0.25098F, 0.29804F},
    vivid::srgb_t{0.38039F, 0.49412F, 0.07843F},
    vivid::srgb_t{1.00000F, 0.89804F, 0.60000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
