#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BATLOW_20 = std::array{
    vivid::srgb_t{0.00392F, 0.09804F, 0.34902F},
    vivid::srgb_t{0.03137F, 0.15294F, 0.36078F},
    vivid::srgb_t{0.05490F, 0.20784F, 0.36863F},
    vivid::srgb_t{0.07451F, 0.26275F, 0.37647F},
    vivid::srgb_t{0.10196F, 0.32157F, 0.38039F},
    vivid::srgb_t{0.14902F, 0.37255F, 0.37255F},
    vivid::srgb_t{0.21961F, 0.41569F, 0.34510F},
    vivid::srgb_t{0.29412F, 0.44706F, 0.30588F},
    vivid::srgb_t{0.37255F, 0.47059F, 0.26275F},
    vivid::srgb_t{0.45882F, 0.49412F, 0.21961F},
    vivid::srgb_t{0.54510F, 0.52157F, 0.18431F},
    vivid::srgb_t{0.65882F, 0.54510F, 0.18431F},
    vivid::srgb_t{0.76471F, 0.56863F, 0.23137F},
    vivid::srgb_t{0.86275F, 0.58824F, 0.30980F},
    vivid::srgb_t{0.94510F, 0.61569F, 0.41961F},
    vivid::srgb_t{0.98039F, 0.64706F, 0.52941F},
    vivid::srgb_t{0.99216F, 0.68627F, 0.64314F},
    vivid::srgb_t{0.99216F, 0.72157F, 0.74902F},
    vivid::srgb_t{0.98824F, 0.76078F, 0.86667F},
    vivid::srgb_t{0.98039F, 0.80000F, 0.98039F},
};

} // namespace GOOM::COLOR::COLOR_DATA
