#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BATLOW_12 = std::array{
    vivid::srgb_t{0.00392F, 0.09804F, 0.34902F},
    vivid::srgb_t{0.04706F, 0.19216F, 0.36471F},
    vivid::srgb_t{0.08235F, 0.29020F, 0.38039F},
    vivid::srgb_t{0.16471F, 0.38039F, 0.36863F},
    vivid::srgb_t{0.29020F, 0.44314F, 0.30980F},
    vivid::srgb_t{0.42745F, 0.48627F, 0.23529F},
    vivid::srgb_t{0.58431F, 0.52941F, 0.18039F},
    vivid::srgb_t{0.77255F, 0.56863F, 0.23529F},
    vivid::srgb_t{0.92941F, 0.60784F, 0.39608F},
    vivid::srgb_t{0.99216F, 0.66667F, 0.59608F},
    vivid::srgb_t{0.99216F, 0.73333F, 0.78431F},
    vivid::srgb_t{0.98039F, 0.80000F, 0.98039F},
};

} // namespace GOOM::COLOR::COLOR_DATA
