#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BATLOW_6 = std::array{
    vivid::srgb_t{0.00392F, 0.09804F, 0.34902F},
    vivid::srgb_t{0.09412F, 0.30980F, 0.38039F},
    vivid::srgb_t{0.34118F, 0.46275F, 0.27843F},
    vivid::srgb_t{0.69804F, 0.55294F, 0.19608F},
    vivid::srgb_t{0.98824F, 0.65490F, 0.55294F},
    vivid::srgb_t{0.98039F, 0.80000F, 0.98039F},
};

} // namespace GOOM::COLOR::COLOR_DATA
