#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BATLOW_17 = std::array{
    vivid::srgb_t{0.00392F, 0.09804F, 0.34902F},
    vivid::srgb_t{0.03529F, 0.16471F, 0.36078F},
    vivid::srgb_t{0.05882F, 0.23137F, 0.37255F},
    vivid::srgb_t{0.08627F, 0.29804F, 0.38039F},
    vivid::srgb_t{0.13725F, 0.36078F, 0.37647F},
    vivid::srgb_t{0.21569F, 0.41176F, 0.34510F},
    vivid::srgb_t{0.30588F, 0.45098F, 0.29804F},
    vivid::srgb_t{0.40000F, 0.47843F, 0.24706F},
    vivid::srgb_t{0.50588F, 0.50980F, 0.20000F},
    vivid::srgb_t{0.61569F, 0.53725F, 0.18039F},
    vivid::srgb_t{0.74902F, 0.56471F, 0.21961F},
    vivid::srgb_t{0.87059F, 0.58824F, 0.31765F},
    vivid::srgb_t{0.95686F, 0.61961F, 0.44314F},
    vivid::srgb_t{0.98824F, 0.66275F, 0.58039F},
    vivid::srgb_t{0.99216F, 0.70588F, 0.70980F},
    vivid::srgb_t{0.98824F, 0.75294F, 0.84314F},
    vivid::srgb_t{0.98039F, 0.80000F, 0.98039F},
};

} // namespace GOOM::COLOR::COLOR_DATA
