#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BERLIN_10 = std::array{
    vivid::srgb_t{0.61961F, 0.69020F, 1.00000F},
    vivid::srgb_t{0.35686F, 0.64314F, 0.85882F},
    vivid::srgb_t{0.17647F, 0.45882F, 0.59216F},
    vivid::srgb_t{0.10196F, 0.25882F, 0.33725F},
    vivid::srgb_t{0.06667F, 0.09804F, 0.11765F},
    vivid::srgb_t{0.15686F, 0.05098F, 0.00392F},
    vivid::srgb_t{0.31373F, 0.09412F, 0.01176F},
    vivid::srgb_t{0.54118F, 0.24706F, 0.16471F},
    vivid::srgb_t{0.76863F, 0.45882F, 0.41569F},
    vivid::srgb_t{1.00000F, 0.67843F, 0.67843F},
};

} // namespace GOOM::COLOR::COLOR_DATA
