#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> BERLIN_6
{
  {   0.61961F,   0.69020F,   1.00000F },
  {   0.19608F,   0.50196F,   0.65098F },
  {   0.06667F,   0.15294F,   0.19608F },
  {   0.21569F,   0.06275F,   0.00000F },
  {   0.58824F,   0.29020F,   0.21176F },
  {   1.00000F,   0.67843F,   0.67843F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
