#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BERLIN_18 = std::array{
    vivid::srgb_t{0.61961F, 0.69020F, 1.00000F},
    vivid::srgb_t{0.48235F, 0.67451F, 0.93333F},
    vivid::srgb_t{0.33725F, 0.63529F, 0.84314F},
    vivid::srgb_t{0.22353F, 0.54510F, 0.70588F},
    vivid::srgb_t{0.16863F, 0.43529F, 0.56078F},
    vivid::srgb_t{0.12549F, 0.32941F, 0.42353F},
    vivid::srgb_t{0.09020F, 0.22745F, 0.29412F},
    vivid::srgb_t{0.06667F, 0.13725F, 0.17255F},
    vivid::srgb_t{0.07059F, 0.07059F, 0.07843F},
    vivid::srgb_t{0.12941F, 0.04314F, 0.01176F},
    vivid::srgb_t{0.20000F, 0.05882F, 0.00000F},
    vivid::srgb_t{0.28235F, 0.08235F, 0.00784F},
    vivid::srgb_t{0.38824F, 0.12941F, 0.04706F},
    vivid::srgb_t{0.51765F, 0.22353F, 0.14118F},
    vivid::srgb_t{0.63529F, 0.33333F, 0.26667F},
    vivid::srgb_t{0.75294F, 0.44314F, 0.39608F},
    vivid::srgb_t{0.87451F, 0.56078F, 0.53725F},
    vivid::srgb_t{1.00000F, 0.67843F, 0.67843F},
};

} // namespace GOOM::COLOR::COLOR_DATA
