#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BERLIN_5 = std::array{
    vivid::srgb_t{0.61961F, 0.69020F, 1.00000F},
    vivid::srgb_t{0.15686F, 0.40784F, 0.52549F},
    vivid::srgb_t{0.09804F, 0.04706F, 0.03529F},
    vivid::srgb_t{0.48235F, 0.19608F, 0.10980F},
    vivid::srgb_t{1.00000F, 0.67843F, 0.67843F},
};

} // namespace GOOM::COLOR::COLOR_DATA
