#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BILBAO_17 = std::array{
    vivid::srgb_t{1.00000F, 1.00000F, 1.00000F},
    vivid::srgb_t{0.91765F, 0.91765F, 0.91765F},
    vivid::srgb_t{0.84314F, 0.84314F, 0.82745F},
    vivid::srgb_t{0.79216F, 0.78039F, 0.73725F},
    vivid::srgb_t{0.76078F, 0.73725F, 0.65098F},
    vivid::srgb_t{0.73333F, 0.69804F, 0.56863F},
    vivid::srgb_t{0.70980F, 0.64706F, 0.48627F},
    vivid::srgb_t{0.68235F, 0.58431F, 0.42745F},
    vivid::srgb_t{0.66667F, 0.52549F, 0.39608F},
    vivid::srgb_t{0.65098F, 0.47451F, 0.37647F},
    vivid::srgb_t{0.63529F, 0.41961F, 0.34902F},
    vivid::srgb_t{0.61569F, 0.36078F, 0.32157F},
    vivid::srgb_t{0.57647F, 0.29412F, 0.27843F},
    vivid::srgb_t{0.51765F, 0.22353F, 0.21961F},
    vivid::srgb_t{0.45098F, 0.15294F, 0.14902F},
    vivid::srgb_t{0.37647F, 0.08235F, 0.08627F},
    vivid::srgb_t{0.30196F, 0.00000F, 0.00392F},
};

} // namespace GOOM::COLOR::COLOR_DATA
