#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> BILBAO_5
{
  {   1.00000F,   1.00000F,   1.00000F },
  {   0.76078F,   0.73725F,   0.65098F },
  {   0.66667F,   0.52549F,   0.39608F },
  {   0.57647F,   0.29412F,   0.27843F },
  {   0.30196F,   0.00000F,   0.00392F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
