#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> BLUEORANGERED_5
{
  {   0.02745F,   0.35294F,   1.00000F },
  {   0.54902F,   0.69804F,   1.00000F },
  {   0.96863F,   0.97647F,   1.00000F },
  {   1.00000F,   0.80000F,   0.00000F },
  {   1.00000F,   0.00000F,   0.00000F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
