#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BLUES_3 = std::array{
    vivid::srgb_t{0.87059F, 0.92157F, 0.96863F},
    vivid::srgb_t{0.61961F, 0.79216F, 0.88235F},
    vivid::srgb_t{0.19216F, 0.50980F, 0.74118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
