#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BLUEDARKORANGE18_2 = std::array{
    vivid::srgb_t{0.00000F, 0.40000F, 0.40000F},
    vivid::srgb_t{0.40000F, 0.15294F, 0.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
