#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BLUEDARKRED18_17 = std::array{
    vivid::srgb_t{0.14118F, 0.00000F, 0.84706F},
    vivid::srgb_t{0.09412F, 0.10980F, 0.96863F},
    vivid::srgb_t{0.15686F, 0.34118F, 1.00000F},
    vivid::srgb_t{0.23922F, 0.52941F, 1.00000F},
    vivid::srgb_t{0.33725F, 0.69020F, 1.00000F},
    vivid::srgb_t{0.45882F, 0.82745F, 1.00000F},
    vivid::srgb_t{0.60000F, 0.91765F, 1.00000F},
    vivid::srgb_t{0.73725F, 0.97647F, 1.00000F},
    vivid::srgb_t{0.91765F, 1.00000F, 1.00000F},
    vivid::srgb_t{1.00000F, 0.94510F, 0.73725F},
    vivid::srgb_t{1.00000F, 0.83922F, 0.60000F},
    vivid::srgb_t{1.00000F, 0.67451F, 0.45882F},
    vivid::srgb_t{1.00000F, 0.47059F, 0.33725F},
    vivid::srgb_t{1.00000F, 0.23922F, 0.23922F},
    vivid::srgb_t{0.96863F, 0.15294F, 0.20784F},
    vivid::srgb_t{0.84706F, 0.08235F, 0.18431F},
    vivid::srgb_t{0.64706F, 0.00000F, 0.12941F},
};

} // namespace GOOM::COLOR::COLOR_DATA
