#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BLUES7_5 = std::array{
    vivid::srgb_t{1.00000F, 1.00000F, 1.00000F},
    vivid::srgb_t{0.60000F, 0.97255F, 1.00000F},
    vivid::srgb_t{0.40000F, 0.93725F, 1.00000F},
    vivid::srgb_t{0.20000F, 0.89020F, 1.00000F},
    vivid::srgb_t{0.00000F, 0.47843F, 0.60000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
