#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// NOLINTNEXTLINE(cert-err58-cpp): Fix with C++20 and 'constexpr'.
inline const auto BLUEGREEN_14 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.00000F, 1.00000F},
    {0.20000F, 0.20000F, 1.00000F},
    {0.39608F, 0.39608F, 1.00000F},
    {0.60000F, 0.60000F, 1.00000F},
    {0.69804F, 0.69804F, 1.00000F},
    {0.79608F, 0.79608F, 1.00000F},
    {0.89804F, 0.89804F, 1.00000F},
    {0.89804F, 1.00000F, 0.89804F},
    {0.79608F, 1.00000F, 0.79608F},
    {0.69804F, 1.00000F, 0.69804F},
    {0.60000F, 1.00000F, 0.60000F},
    {0.39608F, 1.00000F, 0.39608F},
    {0.20000F, 1.00000F, 0.20000F},
    {0.00000F, 1.00000F, 0.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
