#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BLUERED_12 = std::array{
    vivid::srgb_t{0.17255F, 0.41176F, 0.69020F},
    vivid::srgb_t{0.70980F, 0.78431F, 0.88627F},
    vivid::srgb_t{0.94118F, 0.15294F, 0.12549F},
    vivid::srgb_t{1.00000F, 0.71373F, 0.69020F},
    vivid::srgb_t{0.67451F, 0.38039F, 0.23529F},
    vivid::srgb_t{0.91373F, 0.76471F, 0.60784F},
    vivid::srgb_t{0.41961F, 0.63922F, 0.83922F},
    vivid::srgb_t{0.70980F, 0.87451F, 0.99216F},
    vivid::srgb_t{0.67451F, 0.52941F, 0.38824F},
    vivid::srgb_t{0.86667F, 0.78824F, 0.70588F},
    vivid::srgb_t{0.74118F, 0.03922F, 0.21176F},
    vivid::srgb_t{0.95686F, 0.45098F, 0.47843F},
};

} // namespace GOOM::COLOR::COLOR_DATA
