#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BLUES_6 = std::array{
    vivid::srgb_t{0.93725F, 0.95294F, 1.00000F},
    vivid::srgb_t{0.77647F, 0.85882F, 0.93725F},
    vivid::srgb_t{0.61961F, 0.79216F, 0.88235F},
    vivid::srgb_t{0.41961F, 0.68235F, 0.83922F},
    vivid::srgb_t{0.19216F, 0.50980F, 0.74118F},
    vivid::srgb_t{0.03137F, 0.31765F, 0.61176F},
};

} // namespace GOOM::COLOR::COLOR_DATA
