#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BLUEDARKRED12_2 = std::array{
    vivid::srgb_t{0.16078F, 0.03922F, 0.84706F},
    vivid::srgb_t{0.64706F, 0.00000F, 0.12941F},
};

} // namespace GOOM::COLOR::COLOR_DATA
