#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> BLUGRN_3
{
  {   0.76863F,   0.90196F,   0.76471F },
  {   0.30196F,   0.63529F,   0.51765F },
  {   0.11373F,   0.30980F,   0.37647F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
