#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> BLUYL_6
{
  {   0.96863F,   0.99608F,   0.68235F },
  {   0.71765F,   0.90196F,   0.64706F },
  {   0.48627F,   0.79608F,   0.63529F },
  {   0.03137F,   0.56471F,   0.60000F },
  {   0.00000F,   0.44314F,   0.54510F },
  {   0.01569F,   0.32157F,   0.45882F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
