#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// NOLINTNEXTLINE(cert-err58-cpp): Fix with C++20 and 'constexpr'.
inline const auto BRBG_4 = std::vector<vivid::srgb_t>{
    {0.65098F, 0.38039F, 0.10196F},
    {0.87451F, 0.76078F, 0.49020F},
    {0.50196F, 0.80392F, 0.75686F},
    {0.00392F, 0.52157F, 0.44314F},
};

} // namespace GOOM::COLOR::COLOR_DATA
