#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> BRBG_4
{
  {   0.65098F,   0.38039F,   0.10196F },
  {   0.87451F,   0.76078F,   0.49020F },
  {   0.50196F,   0.80392F,   0.75686F },
  {   0.00392F,   0.52157F,   0.44314F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
