#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BRBG_11 = std::array{
    vivid::srgb_t{0.32941F, 0.18824F, 0.01961F},
    vivid::srgb_t{0.54902F, 0.31765F, 0.03922F},
    vivid::srgb_t{0.74902F, 0.50588F, 0.17647F},
    vivid::srgb_t{0.87451F, 0.76078F, 0.49020F},
    vivid::srgb_t{0.96471F, 0.90980F, 0.76471F},
    vivid::srgb_t{0.96078F, 0.96078F, 0.96078F},
    vivid::srgb_t{0.78039F, 0.91765F, 0.89804F},
    vivid::srgb_t{0.50196F, 0.80392F, 0.75686F},
    vivid::srgb_t{0.20784F, 0.59216F, 0.56078F},
    vivid::srgb_t{0.00392F, 0.40000F, 0.36863F},
    vivid::srgb_t{0.00000F, 0.23529F, 0.18824F},
};

} // namespace GOOM::COLOR::COLOR_DATA
