#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BRBG_5 = std::array{
    vivid::srgb_t{0.65098F, 0.38039F, 0.10196F},
    vivid::srgb_t{0.87451F, 0.76078F, 0.49020F},
    vivid::srgb_t{0.96078F, 0.96078F, 0.96078F},
    vivid::srgb_t{0.50196F, 0.80392F, 0.75686F},
    vivid::srgb_t{0.00392F, 0.52157F, 0.44314F},
};

} // namespace GOOM::COLOR::COLOR_DATA
