#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BROC_17 = std::array{
    vivid::srgb_t{0.17255F, 0.10196F, 0.29804F},
    vivid::srgb_t{0.16471F, 0.19216F, 0.39216F},
    vivid::srgb_t{0.16078F, 0.29412F, 0.49020F},
    vivid::srgb_t{0.22353F, 0.40000F, 0.58431F},
    vivid::srgb_t{0.35686F, 0.50980F, 0.66275F},
    vivid::srgb_t{0.49804F, 0.61961F, 0.73725F},
    vivid::srgb_t{0.64706F, 0.73333F, 0.81569F},
    vivid::srgb_t{0.79608F, 0.84706F, 0.89412F},
    vivid::srgb_t{0.92157F, 0.93333F, 0.92549F},
    vivid::srgb_t{0.90588F, 0.90588F, 0.81176F},
    vivid::srgb_t{0.83137F, 0.83137F, 0.66667F},
    vivid::srgb_t{0.73725F, 0.73725F, 0.51373F},
    vivid::srgb_t{0.60784F, 0.60784F, 0.38431F},
    vivid::srgb_t{0.48235F, 0.48235F, 0.27843F},
    vivid::srgb_t{0.36471F, 0.36471F, 0.17647F},
    vivid::srgb_t{0.25098F, 0.25098F, 0.08627F},
    vivid::srgb_t{0.14902F, 0.14902F, 0.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
