#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BROC_11 = std::array{
    vivid::srgb_t{0.17255F, 0.10196F, 0.29804F},
    vivid::srgb_t{0.15686F, 0.25490F, 0.45490F},
    vivid::srgb_t{0.24706F, 0.41961F, 0.60000F},
    vivid::srgb_t{0.46275F, 0.59216F, 0.71765F},
    vivid::srgb_t{0.70196F, 0.77255F, 0.84314F},
    vivid::srgb_t{0.92157F, 0.93333F, 0.92549F},
    vivid::srgb_t{0.86275F, 0.85882F, 0.72157F},
    vivid::srgb_t{0.71373F, 0.71373F, 0.48627F},
    vivid::srgb_t{0.50588F, 0.50588F, 0.29804F},
    vivid::srgb_t{0.31373F, 0.31373F, 0.13725F},
    vivid::srgb_t{0.14902F, 0.14902F, 0.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
