#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> BROWNBLUE12_2
{
  {   0.20000F,   0.09804F,   0.00000F },
  {   0.00000F,   0.47843F,   0.60000F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
