#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// NOLINTNEXTLINE(cert-err58-cpp): Fix with C++20 and 'constexpr'.
inline const auto BROWNBLUE12_2 = std::vector<vivid::srgb_t>{
    {0.20000F, 0.09804F, 0.00000F},
    {0.00000F, 0.47843F, 0.60000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
