#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// NOLINTNEXTLINE(cert-err58-cpp): Fix with C++20 and 'constexpr'.
inline const auto BUDA_5 = std::vector<vivid::srgb_t>{
    {0.70196F, 0.00392F, 0.70196F},
    {0.73725F, 0.30588F, 0.56471F},
    {0.80392F, 0.52157F, 0.49412F},
    {0.85882F, 0.74118F, 0.43922F},
    {1.00000F, 1.00000F, 0.40000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
