#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BUDA_15 = std::array{
    vivid::srgb_t{0.70196F, 0.00392F, 0.70196F},
    vivid::srgb_t{0.70196F, 0.12157F, 0.64314F},
    vivid::srgb_t{0.70588F, 0.20000F, 0.60392F},
    vivid::srgb_t{0.72549F, 0.27451F, 0.57647F},
    vivid::srgb_t{0.74510F, 0.33725F, 0.55294F},
    vivid::srgb_t{0.76863F, 0.40000F, 0.53333F},
    vivid::srgb_t{0.78824F, 0.45882F, 0.51373F},
    vivid::srgb_t{0.80392F, 0.52157F, 0.49412F},
    vivid::srgb_t{0.81961F, 0.58431F, 0.47843F},
    vivid::srgb_t{0.83529F, 0.64706F, 0.46275F},
    vivid::srgb_t{0.85098F, 0.70980F, 0.44706F},
    vivid::srgb_t{0.86667F, 0.77255F, 0.43137F},
    vivid::srgb_t{0.88627F, 0.84314F, 0.41569F},
    vivid::srgb_t{0.92157F, 0.91373F, 0.40392F},
    vivid::srgb_t{1.00000F, 1.00000F, 0.40000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
