#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BUDA_11 = std::array{
    vivid::srgb_t{0.70196F, 0.00392F, 0.70196F},
    vivid::srgb_t{0.70196F, 0.15686F, 0.62353F},
    vivid::srgb_t{0.72157F, 0.25882F, 0.58039F},
    vivid::srgb_t{0.74902F, 0.34902F, 0.54902F},
    vivid::srgb_t{0.78039F, 0.43529F, 0.52157F},
    vivid::srgb_t{0.80392F, 0.52157F, 0.49412F},
    vivid::srgb_t{0.82745F, 0.60784F, 0.47451F},
    vivid::srgb_t{0.84706F, 0.69412F, 0.45098F},
    vivid::srgb_t{0.87059F, 0.78824F, 0.42745F},
    vivid::srgb_t{0.90588F, 0.88627F, 0.40784F},
    vivid::srgb_t{1.00000F, 1.00000F, 0.40000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
