#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BUGN_4 = std::array{
    vivid::srgb_t{0.92941F, 0.97255F, 0.98431F},
    vivid::srgb_t{0.69804F, 0.88627F, 0.88627F},
    vivid::srgb_t{0.40000F, 0.76078F, 0.64314F},
    vivid::srgb_t{0.13725F, 0.54510F, 0.27059F},
};

} // namespace GOOM::COLOR::COLOR_DATA
