#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BUGN_7 = std::array{
    vivid::srgb_t{0.92941F, 0.97255F, 0.98431F},
    vivid::srgb_t{0.80000F, 0.92549F, 0.90196F},
    vivid::srgb_t{0.60000F, 0.84706F, 0.78824F},
    vivid::srgb_t{0.40000F, 0.76078F, 0.64314F},
    vivid::srgb_t{0.25490F, 0.68235F, 0.46275F},
    vivid::srgb_t{0.13725F, 0.54510F, 0.27059F},
    vivid::srgb_t{0.00000F, 0.34510F, 0.14118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
