#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// NOLINTNEXTLINE(cert-err58-cpp): Fix with C++20 and 'constexpr'.
inline const auto BUPU_4 = std::vector<vivid::srgb_t>{
    {0.92941F, 0.97255F, 0.98431F},
    {0.70196F, 0.80392F, 0.89020F},
    {0.54902F, 0.58824F, 0.77647F},
    {0.53333F, 0.25490F, 0.61569F},
};

} // namespace GOOM::COLOR::COLOR_DATA
