#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BURGYL_5 = std::array{
    vivid::srgb_t{0.98431F, 0.90196F, 0.77255F},
    vivid::srgb_t{0.93333F, 0.54118F, 0.50980F},
    vivid::srgb_t{0.86275F, 0.44314F, 0.46275F},
    vivid::srgb_t{0.78431F, 0.34510F, 0.42353F},
    vivid::srgb_t{0.43922F, 0.15686F, 0.29020F},
};

} // namespace GOOM::COLOR::COLOR_DATA
