#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> BURG_2
{
  {   1.00000F,   0.77647F,   0.76863F },
  {   0.40392F,   0.12549F,   0.26667F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
