#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_BURG_3 = std::array{
    vivid::srgb_t{1.00000F, 0.77647F, 0.76863F},
    vivid::srgb_t{0.80000F, 0.37647F, 0.49020F},
    vivid::srgb_t{0.40392F, 0.12549F, 0.26667F},
};

} // namespace GOOM::COLOR::COLOR_DATA
