#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> CORK_3
{
  {   0.17255F,   0.10196F,   0.29804F },
  {   0.85882F,   0.90196F,   0.89804F },
  {   0.25882F,   0.30196F,   0.01176F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
