#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_CORK_16 = std::array{
    vivid::srgb_t{0.17255F, 0.10196F, 0.29804F},
    vivid::srgb_t{0.16471F, 0.19608F, 0.39608F},
    vivid::srgb_t{0.16863F, 0.29804F, 0.49412F},
    vivid::srgb_t{0.23922F, 0.40784F, 0.58824F},
    vivid::srgb_t{0.37255F, 0.52157F, 0.67059F},
    vivid::srgb_t{0.51765F, 0.63137F, 0.74510F},
    vivid::srgb_t{0.66667F, 0.74902F, 0.82745F},
    vivid::srgb_t{0.81176F, 0.86275F, 0.89412F},
    vivid::srgb_t{0.83922F, 0.90196F, 0.85882F},
    vivid::srgb_t{0.71765F, 0.83529F, 0.72941F},
    vivid::srgb_t{0.58431F, 0.75686F, 0.60000F},
    vivid::srgb_t{0.45098F, 0.67843F, 0.47059F},
    vivid::srgb_t{0.32549F, 0.58824F, 0.33333F},
    vivid::srgb_t{0.25490F, 0.47843F, 0.19216F},
    vivid::srgb_t{0.25490F, 0.38039F, 0.09412F},
    vivid::srgb_t{0.25882F, 0.30196F, 0.01176F},
};

} // namespace GOOM::COLOR::COLOR_DATA
