#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_CUBE1_11 = std::array{
    vivid::srgb_t{0.47059F, 0.00000F, 0.52157F},
    vivid::srgb_t{0.50588F, 0.14902F, 0.80392F},
    vivid::srgb_t{0.43137F, 0.38431F, 0.99216F},
    vivid::srgb_t{0.33725F, 0.56863F, 0.90980F},
    vivid::srgb_t{0.21961F, 0.71373F, 0.72157F},
    vivid::srgb_t{0.28627F, 0.81569F, 0.49412F},
    vivid::srgb_t{0.36078F, 0.89020F, 0.28627F},
    vivid::srgb_t{0.59608F, 0.92549F, 0.32549F},
    vivid::srgb_t{0.80000F, 0.92549F, 0.35294F},
    vivid::srgb_t{0.91765F, 0.80392F, 0.36471F},
    vivid::srgb_t{0.97647F, 0.58824F, 0.35686F},
};

} // namespace GOOM::COLOR::COLOR_DATA
