#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_CUBEYF_17 = std::array{
    vivid::srgb_t{0.48235F, 0.00784F, 0.56471F},
    vivid::srgb_t{0.52549F, 0.07451F, 0.72157F},
    vivid::srgb_t{0.51373F, 0.21569F, 0.84706F},
    vivid::srgb_t{0.46275F, 0.32549F, 0.95686F},
    vivid::srgb_t{0.41569F, 0.41569F, 0.99608F},
    vivid::srgb_t{0.37255F, 0.51373F, 0.95294F},
    vivid::srgb_t{0.31765F, 0.59216F, 0.87843F},
    vivid::srgb_t{0.25490F, 0.67059F, 0.79216F},
    vivid::srgb_t{0.22353F, 0.72941F, 0.69412F},
    vivid::srgb_t{0.25882F, 0.77647F, 0.58824F},
    vivid::srgb_t{0.29412F, 0.82353F, 0.47843F},
    vivid::srgb_t{0.33333F, 0.86275F, 0.36078F},
    vivid::srgb_t{0.37647F, 0.89804F, 0.27843F},
    vivid::srgb_t{0.49412F, 0.91373F, 0.30980F},
    vivid::srgb_t{0.63922F, 0.92549F, 0.33333F},
    vivid::srgb_t{0.72157F, 0.92549F, 0.34510F},
    vivid::srgb_t{0.81961F, 0.92157F, 0.35686F},
};

} // namespace GOOM::COLOR::COLOR_DATA
