#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_CUBEYF_10 = std::array{
    vivid::srgb_t{0.48235F, 0.00784F, 0.56471F},
    vivid::srgb_t{0.51765F, 0.18431F, 0.81569F},
    vivid::srgb_t{0.43529F, 0.37255F, 0.98824F},
    vivid::srgb_t{0.35294F, 0.53725F, 0.93333F},
    vivid::srgb_t{0.25098F, 0.67451F, 0.78431F},
    vivid::srgb_t{0.25490F, 0.77255F, 0.60000F},
    vivid::srgb_t{0.31765F, 0.84706F, 0.40000F},
    vivid::srgb_t{0.42353F, 0.90588F, 0.29020F},
    vivid::srgb_t{0.65882F, 0.92549F, 0.33725F},
    vivid::srgb_t{0.81961F, 0.92157F, 0.35686F},
};

} // namespace GOOM::COLOR::COLOR_DATA
