#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_CUBE1_17 = std::array{
    vivid::srgb_t{0.47059F, 0.00000F, 0.52157F},
    vivid::srgb_t{0.51373F, 0.04706F, 0.69804F},
    vivid::srgb_t{0.49804F, 0.23137F, 0.86275F},
    vivid::srgb_t{0.44314F, 0.36471F, 0.98824F},
    vivid::srgb_t{0.38431F, 0.49020F, 0.96471F},
    vivid::srgb_t{0.31765F, 0.59216F, 0.88627F},
    vivid::srgb_t{0.23529F, 0.68235F, 0.77255F},
    vivid::srgb_t{0.24314F, 0.75686F, 0.63922F},
    vivid::srgb_t{0.28627F, 0.81569F, 0.49412F},
    vivid::srgb_t{0.32941F, 0.86275F, 0.35294F},
    vivid::srgb_t{0.40784F, 0.90588F, 0.29020F},
    vivid::srgb_t{0.56863F, 0.92157F, 0.32157F},
    vivid::srgb_t{0.71373F, 0.92549F, 0.34118F},
    vivid::srgb_t{0.81569F, 0.92157F, 0.35294F},
    vivid::srgb_t{0.87843F, 0.84314F, 0.36078F},
    vivid::srgb_t{0.95294F, 0.73725F, 0.36863F},
    vivid::srgb_t{0.97647F, 0.58824F, 0.35686F},
};

} // namespace GOOM::COLOR::COLOR_DATA
