#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_DARKMINT_4 = std::array{
    vivid::srgb_t{0.82353F, 0.98431F, 0.83137F},
    vivid::srgb_t{0.48235F, 0.73725F, 0.69020F},
    vivid::srgb_t{0.22745F, 0.48627F, 0.53725F},
    vivid::srgb_t{0.07059F, 0.24706F, 0.35294F},
};

} // namespace GOOM::COLOR::COLOR_DATA
