#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> DARKMINT_2
{
  {   0.82353F,   0.98431F,   0.83137F },
  {   0.07059F,   0.24706F,   0.35294F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
