#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_DAVOS_18 = std::array{
    vivid::srgb_t{0.00000F, 0.01961F, 0.29020F},
    vivid::srgb_t{0.02745F, 0.10588F, 0.37647F},
    vivid::srgb_t{0.07451F, 0.18431F, 0.45490F},
    vivid::srgb_t{0.11765F, 0.26275F, 0.52549F},
    vivid::srgb_t{0.16863F, 0.33725F, 0.57647F},
    vivid::srgb_t{0.22745F, 0.40000F, 0.60784F},
    vivid::srgb_t{0.28235F, 0.45490F, 0.61569F},
    vivid::srgb_t{0.33725F, 0.49804F, 0.60784F},
    vivid::srgb_t{0.39608F, 0.53725F, 0.58824F},
    vivid::srgb_t{0.45098F, 0.57255F, 0.56471F},
    vivid::srgb_t{0.50588F, 0.61176F, 0.54118F},
    vivid::srgb_t{0.57255F, 0.65882F, 0.52941F},
    vivid::srgb_t{0.65882F, 0.72157F, 0.54510F},
    vivid::srgb_t{0.76471F, 0.80392F, 0.60000F},
    vivid::srgb_t{0.87059F, 0.89020F, 0.70196F},
    vivid::srgb_t{0.94510F, 0.94902F, 0.81176F},
    vivid::srgb_t{0.98039F, 0.98039F, 0.90980F},
    vivid::srgb_t{0.99608F, 0.99608F, 0.99608F},
};

} // namespace GOOM::COLOR::COLOR_DATA
