#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// NOLINTNEXTLINE(cert-err58-cpp): Fix with C++20 and 'constexpr'.
inline const auto DAVOS_5 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.01961F, 0.29020F},
    {0.18431F, 0.35294F, 0.58824F},
    {0.42353F, 0.55686F, 0.57647F},
    {0.73333F, 0.78039F, 0.58039F},
    {0.99608F, 0.99608F, 0.99608F},
};

} // namespace GOOM::COLOR::COLOR_DATA
