#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_DAVOS_19 = std::array{
    vivid::srgb_t{0.00000F, 0.01961F, 0.29020F},
    vivid::srgb_t{0.02745F, 0.10196F, 0.36863F},
    vivid::srgb_t{0.06667F, 0.17255F, 0.44314F},
    vivid::srgb_t{0.10980F, 0.24706F, 0.51373F},
    vivid::srgb_t{0.16078F, 0.32157F, 0.56863F},
    vivid::srgb_t{0.21176F, 0.38431F, 0.60392F},
    vivid::srgb_t{0.26275F, 0.43922F, 0.61569F},
    vivid::srgb_t{0.31765F, 0.48235F, 0.61176F},
    vivid::srgb_t{0.36863F, 0.52157F, 0.59608F},
    vivid::srgb_t{0.42353F, 0.55686F, 0.57647F},
    vivid::srgb_t{0.47451F, 0.58824F, 0.55294F},
    vivid::srgb_t{0.53333F, 0.62745F, 0.53725F},
    vivid::srgb_t{0.60000F, 0.67843F, 0.53333F},
    vivid::srgb_t{0.68235F, 0.74118F, 0.55294F},
    vivid::srgb_t{0.78824F, 0.82353F, 0.61961F},
    vivid::srgb_t{0.88235F, 0.89804F, 0.71373F},
    vivid::srgb_t{0.95294F, 0.95294F, 0.82353F},
    vivid::srgb_t{0.98431F, 0.98039F, 0.91373F},
    vivid::srgb_t{0.99608F, 0.99608F, 0.99608F},
};

} // namespace GOOM::COLOR::COLOR_DATA
