#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_DAVOS_12 = std::array{
    vivid::srgb_t{0.00000F, 0.01961F, 0.29020F},
    vivid::srgb_t{0.05490F, 0.14902F, 0.41961F},
    vivid::srgb_t{0.12157F, 0.26667F, 0.52941F},
    vivid::srgb_t{0.20784F, 0.38039F, 0.60000F},
    vivid::srgb_t{0.29412F, 0.46275F, 0.61569F},
    vivid::srgb_t{0.38039F, 0.52549F, 0.59216F},
    vivid::srgb_t{0.46275F, 0.58431F, 0.55686F},
    vivid::srgb_t{0.56078F, 0.64706F, 0.53333F},
    vivid::srgb_t{0.69020F, 0.74902F, 0.55686F},
    vivid::srgb_t{0.86667F, 0.88627F, 0.69412F},
    vivid::srgb_t{0.96471F, 0.96471F, 0.85882F},
    vivid::srgb_t{0.99608F, 0.99608F, 0.99608F},
};

} // namespace GOOM::COLOR::COLOR_DATA
