#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_DAVOS_11 = std::array{
    vivid::srgb_t{0.00000F, 0.01961F, 0.29020F},
    vivid::srgb_t{0.06275F, 0.16471F, 0.43529F},
    vivid::srgb_t{0.13725F, 0.29020F, 0.54902F},
    vivid::srgb_t{0.22745F, 0.40392F, 0.60784F},
    vivid::srgb_t{0.32941F, 0.49020F, 0.61176F},
    vivid::srgb_t{0.42353F, 0.55686F, 0.57647F},
    vivid::srgb_t{0.51765F, 0.61961F, 0.53725F},
    vivid::srgb_t{0.64314F, 0.71373F, 0.54118F},
    vivid::srgb_t{0.83137F, 0.85882F, 0.65882F},
    vivid::srgb_t{0.96078F, 0.96078F, 0.84314F},
    vivid::srgb_t{0.99608F, 0.99608F, 0.99608F},
};

} // namespace GOOM::COLOR::COLOR_DATA
