#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_DAVOS_8 = std::array{
    vivid::srgb_t{0.00000F, 0.01961F, 0.29020F},
    vivid::srgb_t{0.09020F, 0.21569F, 0.48627F},
    vivid::srgb_t{0.21961F, 0.39216F, 0.60392F},
    vivid::srgb_t{0.35294F, 0.50980F, 0.60392F},
    vivid::srgb_t{0.49020F, 0.60000F, 0.54902F},
    vivid::srgb_t{0.67059F, 0.73333F, 0.54902F},
    vivid::srgb_t{0.92157F, 0.92941F, 0.76863F},
    vivid::srgb_t{0.99608F, 0.99608F, 0.99608F},
};

} // namespace GOOM::COLOR::COLOR_DATA
