#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_DEEP_16 = std::array{
    vivid::srgb_t{0.99216F, 0.99608F, 0.80000F},
    vivid::srgb_t{0.85882F, 0.94510F, 0.72549F},
    vivid::srgb_t{0.71765F, 0.89804F, 0.67059F},
    vivid::srgb_t{0.57255F, 0.84706F, 0.64314F},
    vivid::srgb_t{0.44314F, 0.79216F, 0.63922F},
    vivid::srgb_t{0.36471F, 0.72941F, 0.64314F},
    vivid::srgb_t{0.32157F, 0.65882F, 0.63922F},
    vivid::srgb_t{0.29412F, 0.59216F, 0.62745F},
    vivid::srgb_t{0.27059F, 0.52549F, 0.61176F},
    vivid::srgb_t{0.25098F, 0.45882F, 0.59608F},
    vivid::srgb_t{0.24314F, 0.39216F, 0.58431F},
    vivid::srgb_t{0.24706F, 0.32157F, 0.56078F},
    vivid::srgb_t{0.25490F, 0.25098F, 0.48235F},
    vivid::srgb_t{0.23529F, 0.20000F, 0.37255F},
    vivid::srgb_t{0.20000F, 0.15294F, 0.26667F},
    vivid::srgb_t{0.15686F, 0.10196F, 0.17255F},
};

} // namespace GOOM::COLOR::COLOR_DATA
