#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> DEEP_3
{
  {   0.99216F,   0.99608F,   0.80000F },
  {   0.28235F,   0.55686F,   0.61961F },
  {   0.15686F,   0.10196F,   0.17255F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
