#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_DEEP_6 = std::array{
    vivid::srgb_t{0.99216F, 0.99608F, 0.80000F},
    vivid::srgb_t{0.57255F, 0.84706F, 0.64314F},
    vivid::srgb_t{0.32157F, 0.65882F, 0.63922F},
    vivid::srgb_t{0.25098F, 0.45882F, 0.59608F},
    vivid::srgb_t{0.25490F, 0.25098F, 0.48235F},
    vivid::srgb_t{0.15686F, 0.10196F, 0.17255F},
};

} // namespace GOOM::COLOR::COLOR_DATA
