#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_DEEP_19 = std::array{
    vivid::srgb_t{0.99216F, 0.99608F, 0.80000F},
    vivid::srgb_t{0.88235F, 0.95294F, 0.73725F},
    vivid::srgb_t{0.76863F, 0.91373F, 0.68627F},
    vivid::srgb_t{0.64706F, 0.87451F, 0.65490F},
    vivid::srgb_t{0.52157F, 0.82745F, 0.63922F},
    vivid::srgb_t{0.42745F, 0.78039F, 0.63922F},
    vivid::srgb_t{0.36471F, 0.72941F, 0.64314F},
    vivid::srgb_t{0.32549F, 0.67059F, 0.63922F},
    vivid::srgb_t{0.30196F, 0.61569F, 0.63137F},
    vivid::srgb_t{0.28235F, 0.55686F, 0.61961F},
    vivid::srgb_t{0.26667F, 0.50196F, 0.60784F},
    vivid::srgb_t{0.25098F, 0.44706F, 0.59608F},
    vivid::srgb_t{0.24314F, 0.39216F, 0.58431F},
    vivid::srgb_t{0.24706F, 0.33333F, 0.56471F},
    vivid::srgb_t{0.25490F, 0.27451F, 0.51765F},
    vivid::srgb_t{0.25098F, 0.22745F, 0.43137F},
    vivid::srgb_t{0.22353F, 0.18431F, 0.33333F},
    vivid::srgb_t{0.19216F, 0.14510F, 0.25098F},
    vivid::srgb_t{0.15686F, 0.10196F, 0.17255F},
};

} // namespace GOOM::COLOR::COLOR_DATA
