#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_DELTA_6 = std::array{
    vivid::srgb_t{0.06667F, 0.12549F, 0.25098F},
    vivid::srgb_t{0.13725F, 0.47059F, 0.63922F},
    vivid::srgb_t{0.67451F, 0.80784F, 0.77647F},
    vivid::srgb_t{0.84706F, 0.77255F, 0.37255F},
    vivid::srgb_t{0.19608F, 0.50196F, 0.12157F},
    vivid::srgb_t{0.09020F, 0.13725F, 0.07451F},
};

} // namespace GOOM::COLOR::COLOR_DATA
