#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> DENSE_8
{
  {   0.90196F,   0.94510F,   0.94510F },
  {   0.67059F,   0.82745F,   0.89020F },
  {   0.49412F,   0.69020F,   0.89412F },
  {   0.45490F,   0.53333F,   0.88235F },
  {   0.47451F,   0.36078F,   0.76471F },
  {   0.45098F,   0.21569F,   0.57647F },
  {   0.36471F,   0.10196F,   0.34510F },
  {   0.21176F,   0.05490F,   0.14118F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
