#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_DEVON_16 = std::array{
    vivid::srgb_t{0.17255F, 0.10196F, 0.29804F},
    vivid::srgb_t{0.16471F, 0.16078F, 0.36078F},
    vivid::srgb_t{0.15686F, 0.22353F, 0.42353F},
    vivid::srgb_t{0.15294F, 0.29020F, 0.49412F},
    vivid::srgb_t{0.16471F, 0.36078F, 0.58431F},
    vivid::srgb_t{0.21176F, 0.41176F, 0.67843F},
    vivid::srgb_t{0.29804F, 0.46667F, 0.76863F},
    vivid::srgb_t{0.42745F, 0.52941F, 0.83922F},
    vivid::srgb_t{0.55294F, 0.58431F, 0.89020F},
    vivid::srgb_t{0.65882F, 0.64706F, 0.92549F},
    vivid::srgb_t{0.72941F, 0.70196F, 0.94510F},
    vivid::srgb_t{0.78039F, 0.76078F, 0.95686F},
    vivid::srgb_t{0.83529F, 0.81961F, 0.96471F},
    vivid::srgb_t{0.89020F, 0.87843F, 0.97647F},
    vivid::srgb_t{0.94510F, 0.93725F, 0.98824F},
    vivid::srgb_t{1.00000F, 1.00000F, 1.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
