#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_DEVON_9 = std::array{
    vivid::srgb_t{0.17255F, 0.10196F, 0.29804F},
    vivid::srgb_t{0.16078F, 0.21961F, 0.41569F},
    vivid::srgb_t{0.16078F, 0.34510F, 0.56078F},
    vivid::srgb_t{0.25882F, 0.44706F, 0.73725F},
    vivid::srgb_t{0.49412F, 0.56078F, 0.86667F},
    vivid::srgb_t{0.68627F, 0.66667F, 0.93333F},
    vivid::srgb_t{0.79216F, 0.77647F, 0.95686F},
    vivid::srgb_t{0.89412F, 0.88627F, 0.98039F},
    vivid::srgb_t{1.00000F, 1.00000F, 1.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
