#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> DEVON_20
{
  {   0.17255F,   0.10196F,   0.29804F },
  {   0.16863F,   0.14902F,   0.34510F },
  {   0.16078F,   0.20000F,   0.40000F },
  {   0.15686F,   0.24706F,   0.44706F },
  {   0.15294F,   0.30588F,   0.50980F },
  {   0.16471F,   0.35686F,   0.57647F },
  {   0.19608F,   0.40000F,   0.65490F },
  {   0.24706F,   0.43922F,   0.72549F },
  {   0.33333F,   0.48627F,   0.79216F },
  {   0.44314F,   0.53333F,   0.84706F },
  {   0.54118F,   0.58039F,   0.88235F },
  {   0.63529F,   0.62745F,   0.91765F },
  {   0.69412F,   0.67451F,   0.93725F },
  {   0.74118F,   0.71765F,   0.94510F },
  {   0.78431F,   0.76471F,   0.95686F },
  {   0.82353F,   0.80784F,   0.96471F },
  {   0.87059F,   0.85882F,   0.97255F },
  {   0.90980F,   0.90196F,   0.98039F },
  {   0.95686F,   0.95294F,   0.99216F },
  {   1.00000F,   1.00000F,   1.00000F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
