#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> DEVON_3
{
  {   0.17255F,   0.10196F,   0.29804F },
  {   0.49412F,   0.56078F,   0.86667F },
  {   1.00000F,   1.00000F,   1.00000F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
