#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> EARTH_3
{
  {   0.63137F,   0.41176F,   0.15686F },
  {   0.92941F,   0.91765F,   0.76078F },
  {   0.15686F,   0.52941F,   0.63137F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
