#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> EMRLD_3
{
  {   0.82745F,   0.94902F,   0.63922F },
  {   0.29804F,   0.60784F,   0.50980F },
  {   0.02745F,   0.25098F,   0.31373F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
