#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// NOLINTNEXTLINE(cert-err58-cpp): Fix with C++20 and 'constexpr'.
inline const auto EMRLD_2 = std::vector<vivid::srgb_t>{
    {0.82745F, 0.94902F, 0.63922F},
    {0.02745F, 0.25098F, 0.31373F},
};

} // namespace GOOM::COLOR::COLOR_DATA
