#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> FANTASTICFOX1_5
{
  {   0.97647F,   0.85882F,   0.12549F },
  {   0.57647F,   0.29412F,   0.30588F },
  {   0.25882F,   0.09020F,   0.05098F },
  {   0.76078F,   0.47451F,   0.13333F },
  {   0.88627F,   0.78431F,   0.65490F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
