#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> GEYSER_2
{
  {   0.00000F,   0.50196F,   0.50196F },
  {   0.79216F,   0.33725F,   0.17255F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
