#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_GNBU_5 = std::array{
    vivid::srgb_t{0.94118F, 0.97647F, 0.90980F},
    vivid::srgb_t{0.72941F, 0.89412F, 0.73725F},
    vivid::srgb_t{0.48235F, 0.80000F, 0.76863F},
    vivid::srgb_t{0.26275F, 0.63529F, 0.79216F},
    vivid::srgb_t{0.03137F, 0.40784F, 0.67451F},
};

} // namespace GOOM::COLOR::COLOR_DATA
