#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> GNBU_9
{
  {   0.96863F,   0.98824F,   0.94118F },
  {   0.87843F,   0.95294F,   0.85882F },
  {   0.80000F,   0.92157F,   0.77255F },
  {   0.65882F,   0.86667F,   0.70980F },
  {   0.48235F,   0.80000F,   0.76863F },
  {   0.30588F,   0.70196F,   0.82745F },
  {   0.16863F,   0.54902F,   0.74510F },
  {   0.03137F,   0.40784F,   0.67451F },
  {   0.03137F,   0.25098F,   0.50588F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
