#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_GNBU_4 = std::array{
    vivid::srgb_t{0.94118F, 0.97647F, 0.90980F},
    vivid::srgb_t{0.72941F, 0.89412F, 0.73725F},
    vivid::srgb_t{0.48235F, 0.80000F, 0.76863F},
    vivid::srgb_t{0.16863F, 0.54902F, 0.74510F},
};

} // namespace GOOM::COLOR::COLOR_DATA
