#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_GRANDBUDAPEST3_6 = std::array{
    vivid::srgb_t{1.00000F, 0.86275F, 0.71373F},
    vivid::srgb_t{0.14510F, 0.21961F, 0.27059F},
    vivid::srgb_t{0.90588F, 0.67843F, 0.61569F},
    vivid::srgb_t{0.40000F, 0.45882F, 0.43137F},
    vivid::srgb_t{0.54510F, 0.24706F, 0.19216F},
    vivid::srgb_t{0.58824F, 0.42745F, 0.20784F},
};

} // namespace GOOM::COLOR::COLOR_DATA
