#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_GRAY_8 = std::array{
    vivid::srgb_t{0.00000F, 0.00000F, 0.00000F},
    vivid::srgb_t{0.11373F, 0.11373F, 0.11373F},
    vivid::srgb_t{0.24706F, 0.24706F, 0.24706F},
    vivid::srgb_t{0.37647F, 0.37255F, 0.37255F},
    vivid::srgb_t{0.51373F, 0.50980F, 0.50980F},
    vivid::srgb_t{0.65490F, 0.65490F, 0.65098F},
    vivid::srgb_t{0.81961F, 0.81961F, 0.81569F},
    vivid::srgb_t{1.00000F, 1.00000F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
