#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_GRAYC_9 = std::array{
    vivid::srgb_t{1.00000F, 1.00000F, 1.00000F},
    vivid::srgb_t{0.85882F, 0.85882F, 0.85882F},
    vivid::srgb_t{0.72157F, 0.72157F, 0.72157F},
    vivid::srgb_t{0.59216F, 0.59216F, 0.59216F},
    vivid::srgb_t{0.46275F, 0.46275F, 0.46275F},
    vivid::srgb_t{0.34902F, 0.34902F, 0.34902F},
    vivid::srgb_t{0.23529F, 0.23529F, 0.23529F},
    vivid::srgb_t{0.12941F, 0.12941F, 0.12941F},
    vivid::srgb_t{0.00000F, 0.00000F, 0.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
