#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> GRAYC_8
{
  {   1.00000F,   1.00000F,   1.00000F },
  {   0.84314F,   0.84314F,   0.84314F },
  {   0.68627F,   0.68627F,   0.68627F },
  {   0.53725F,   0.53725F,   0.53725F },
  {   0.39608F,   0.39608F,   0.39608F },
  {   0.26275F,   0.26275F,   0.26275F },
  {   0.14118F,   0.14118F,   0.14118F },
  {   0.00000F,   0.00000F,   0.00000F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
