#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_GRAYC_8 = std::array{
    vivid::srgb_t{1.00000F, 1.00000F, 1.00000F},
    vivid::srgb_t{0.84314F, 0.84314F, 0.84314F},
    vivid::srgb_t{0.68627F, 0.68627F, 0.68627F},
    vivid::srgb_t{0.53725F, 0.53725F, 0.53725F},
    vivid::srgb_t{0.39608F, 0.39608F, 0.39608F},
    vivid::srgb_t{0.26275F, 0.26275F, 0.26275F},
    vivid::srgb_t{0.14118F, 0.14118F, 0.14118F},
    vivid::srgb_t{0.00000F, 0.00000F, 0.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
