#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_GRAYC_7 = std::array{
    vivid::srgb_t{1.00000F, 1.00000F, 1.00000F},
    vivid::srgb_t{0.81569F, 0.81569F, 0.81569F},
    vivid::srgb_t{0.63529F, 0.63529F, 0.63529F},
    vivid::srgb_t{0.46275F, 0.46275F, 0.46275F},
    vivid::srgb_t{0.30588F, 0.30588F, 0.30588F},
    vivid::srgb_t{0.16471F, 0.16471F, 0.16471F},
    vivid::srgb_t{0.00000F, 0.00000F, 0.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
