#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> GRAYC_13
{
  {   1.00000F,   1.00000F,   1.00000F },
  {   0.90588F,   0.90588F,   0.90588F },
  {   0.81569F,   0.81569F,   0.81569F },
  {   0.72157F,   0.72157F,   0.72157F },
  {   0.63529F,   0.63529F,   0.63529F },
  {   0.54902F,   0.54902F,   0.54902F },
  {   0.46275F,   0.46275F,   0.46275F },
  {   0.38431F,   0.38431F,   0.38431F },
  {   0.30588F,   0.30588F,   0.30588F },
  {   0.23529F,   0.23529F,   0.23529F },
  {   0.16471F,   0.16471F,   0.16471F },
  {   0.09412F,   0.09412F,   0.09412F },
  {   0.00000F,   0.00000F,   0.00000F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
