#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// NOLINTNEXTLINE(cert-err58-cpp): Fix with C++20 and 'constexpr'.
inline const auto GRAYC_11 = std::vector<vivid::srgb_t>{
    {1.00000F, 1.00000F, 1.00000F},
    {0.88627F, 0.88627F, 0.88627F},
    {0.77647F, 0.77647F, 0.77647F},
    {0.67451F, 0.67451F, 0.67451F},
    {0.56863F, 0.56863F, 0.56863F},
    {0.46275F, 0.46275F, 0.46275F},
    {0.36863F, 0.36863F, 0.36863F},
    {0.27843F, 0.27843F, 0.27843F},
    {0.18824F, 0.18824F, 0.18824F},
    {0.10588F, 0.10588F, 0.10588F},
    {0.00000F, 0.00000F, 0.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
