#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_GREENORANGE_12 = std::array{
    vivid::srgb_t{0.19608F, 0.63529F, 0.31765F},
    vivid::srgb_t{0.67451F, 0.85098F, 0.55294F},
    vivid::srgb_t{1.00000F, 0.49804F, 0.05882F},
    vivid::srgb_t{1.00000F, 0.72549F, 0.46667F},
    vivid::srgb_t{0.23529F, 0.71765F, 0.80000F},
    vivid::srgb_t{0.59608F, 0.85098F, 0.89412F},
    vivid::srgb_t{0.72157F, 0.35294F, 0.05098F},
    vivid::srgb_t{1.00000F, 0.85098F, 0.29020F},
    vivid::srgb_t{0.22353F, 0.45098F, 0.48627F},
    vivid::srgb_t{0.52549F, 0.70588F, 0.66275F},
    vivid::srgb_t{0.50980F, 0.52157F, 0.23137F},
    vivid::srgb_t{0.80000F, 0.78824F, 0.30196F},
};

} // namespace GOOM::COLOR::COLOR_DATA
