#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> GREENORANGE_6
{
  {   0.19608F,   0.63529F,   0.31765F },
  {   1.00000F,   0.49804F,   0.05882F },
  {   0.23529F,   0.71765F,   0.80000F },
  {   1.00000F,   0.85098F,   0.29020F },
  {   0.22353F,   0.45098F,   0.48627F },
  {   0.72157F,   0.35294F,   0.05098F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
