#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_GREENORANGE_6 = std::array{
    vivid::srgb_t{0.19608F, 0.63529F, 0.31765F},
    vivid::srgb_t{1.00000F, 0.49804F, 0.05882F},
    vivid::srgb_t{0.23529F, 0.71765F, 0.80000F},
    vivid::srgb_t{1.00000F, 0.85098F, 0.29020F},
    vivid::srgb_t{0.22353F, 0.45098F, 0.48627F},
    vivid::srgb_t{0.72157F, 0.35294F, 0.05098F},
};

} // namespace GOOM::COLOR::COLOR_DATA
