#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_GREYS_3 = std::array{
    vivid::srgb_t{0.94118F, 0.94118F, 0.94118F},
    vivid::srgb_t{0.74118F, 0.74118F, 0.74118F},
    vivid::srgb_t{0.38824F, 0.38824F, 0.38824F},
};

} // namespace GOOM::COLOR::COLOR_DATA
