#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_GREYS_7 = std::array{
    vivid::srgb_t{0.96863F, 0.96863F, 0.96863F},
    vivid::srgb_t{0.85098F, 0.85098F, 0.85098F},
    vivid::srgb_t{0.74118F, 0.74118F, 0.74118F},
    vivid::srgb_t{0.58824F, 0.58824F, 0.58824F},
    vivid::srgb_t{0.45098F, 0.45098F, 0.45098F},
    vivid::srgb_t{0.32157F, 0.32157F, 0.32157F},
    vivid::srgb_t{0.14510F, 0.14510F, 0.14510F},
};

} // namespace GOOM::COLOR::COLOR_DATA
