#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_GREYS_5 = std::array{
    vivid::srgb_t{0.96863F, 0.96863F, 0.96863F},
    vivid::srgb_t{0.80000F, 0.80000F, 0.80000F},
    vivid::srgb_t{0.58824F, 0.58824F, 0.58824F},
    vivid::srgb_t{0.38824F, 0.38824F, 0.38824F},
    vivid::srgb_t{0.14510F, 0.14510F, 0.14510F},
};

} // namespace GOOM::COLOR::COLOR_DATA
