#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_HALINE_19 = std::array{
    vivid::srgb_t{0.16471F, 0.09412F, 0.42353F},
    vivid::srgb_t{0.18039F, 0.10980F, 0.55686F},
    vivid::srgb_t{0.14510F, 0.17647F, 0.63922F},
    vivid::srgb_t{0.07843F, 0.26275F, 0.61176F},
    vivid::srgb_t{0.04706F, 0.32941F, 0.57647F},
    vivid::srgb_t{0.07843F, 0.38431F, 0.55686F},
    vivid::srgb_t{0.12549F, 0.43137F, 0.54510F},
    vivid::srgb_t{0.16863F, 0.47843F, 0.53725F},
    vivid::srgb_t{0.20392F, 0.52549F, 0.53333F},
    vivid::srgb_t{0.23529F, 0.57647F, 0.52941F},
    vivid::srgb_t{0.26275F, 0.62745F, 0.51765F},
    vivid::srgb_t{0.29804F, 0.67843F, 0.50196F},
    vivid::srgb_t{0.35294F, 0.72549F, 0.47059F},
    vivid::srgb_t{0.42353F, 0.77255F, 0.43137F},
    vivid::srgb_t{0.52549F, 0.81569F, 0.38431F},
    vivid::srgb_t{0.65882F, 0.84706F, 0.36078F},
    vivid::srgb_t{0.79216F, 0.87451F, 0.41176F},
    vivid::srgb_t{0.89804F, 0.90196F, 0.50196F},
    vivid::srgb_t{0.99216F, 0.93725F, 0.60392F},
};

} // namespace GOOM::COLOR::COLOR_DATA
