#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_HALINE_11 = std::array{
    vivid::srgb_t{0.16471F, 0.09412F, 0.42353F},
    vivid::srgb_t{0.15686F, 0.16078F, 0.63922F},
    vivid::srgb_t{0.05098F, 0.30588F, 0.58824F},
    vivid::srgb_t{0.09412F, 0.40000F, 0.54902F},
    vivid::srgb_t{0.17647F, 0.48627F, 0.53725F},
    vivid::srgb_t{0.23529F, 0.57647F, 0.52941F},
    vivid::srgb_t{0.29020F, 0.66667F, 0.50588F},
    vivid::srgb_t{0.38824F, 0.75294F, 0.44706F},
    vivid::srgb_t{0.58039F, 0.82745F, 0.36471F},
    vivid::srgb_t{0.81569F, 0.87843F, 0.42745F},
    vivid::srgb_t{0.99216F, 0.93725F, 0.60392F},
};

} // namespace GOOM::COLOR::COLOR_DATA
