#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_HALINE_5 = std::array{
    vivid::srgb_t{0.16471F, 0.09412F, 0.42353F},
    vivid::srgb_t{0.05882F, 0.35686F, 0.56471F},
    vivid::srgb_t{0.23529F, 0.57647F, 0.52941F},
    vivid::srgb_t{0.47059F, 0.79608F, 0.40784F},
    vivid::srgb_t{0.99216F, 0.93725F, 0.60392F},
};

} // namespace GOOM::COLOR::COLOR_DATA
