#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_HAWAII_7 = std::array{
    vivid::srgb_t{0.54902F, 0.00784F, 0.45098F},
    vivid::srgb_t{0.58039F, 0.21961F, 0.30196F},
    vivid::srgb_t{0.60000F, 0.38824F, 0.18824F},
    vivid::srgb_t{0.61176F, 0.58824F, 0.10980F},
    vivid::srgb_t{0.50196F, 0.77255F, 0.37255F},
    vivid::srgb_t{0.37255F, 0.88627F, 0.73333F},
    vivid::srgb_t{0.70196F, 0.94902F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
