#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_HAWAII_17 = std::array{
    vivid::srgb_t{0.54902F, 0.00784F, 0.45098F},
    vivid::srgb_t{0.56471F, 0.11373F, 0.38824F},
    vivid::srgb_t{0.57255F, 0.18039F, 0.33333F},
    vivid::srgb_t{0.58431F, 0.24314F, 0.28627F},
    vivid::srgb_t{0.59216F, 0.30588F, 0.24314F},
    vivid::srgb_t{0.60000F, 0.36863F, 0.20000F},
    vivid::srgb_t{0.60784F, 0.43529F, 0.15686F},
    vivid::srgb_t{0.61569F, 0.50588F, 0.12157F},
    vivid::srgb_t{0.61176F, 0.58824F, 0.10980F},
    vivid::srgb_t{0.58824F, 0.66667F, 0.16863F},
    vivid::srgb_t{0.54118F, 0.73725F, 0.28235F},
    vivid::srgb_t{0.48235F, 0.78824F, 0.41176F},
    vivid::srgb_t{0.42353F, 0.83137F, 0.54902F},
    vivid::srgb_t{0.37647F, 0.87059F, 0.69020F},
    vivid::srgb_t{0.40000F, 0.90980F, 0.82745F},
    vivid::srgb_t{0.52941F, 0.93725F, 0.93333F},
    vivid::srgb_t{0.70196F, 0.94902F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
