#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_HAWAII_15 = std::array{
    vivid::srgb_t{0.54902F, 0.00784F, 0.45098F},
    vivid::srgb_t{0.56471F, 0.12157F, 0.38431F},
    vivid::srgb_t{0.57647F, 0.19608F, 0.32157F},
    vivid::srgb_t{0.58431F, 0.27059F, 0.26667F},
    vivid::srgb_t{0.59608F, 0.33725F, 0.21961F},
    vivid::srgb_t{0.60392F, 0.41176F, 0.17255F},
    vivid::srgb_t{0.61176F, 0.49412F, 0.12549F},
    vivid::srgb_t{0.61176F, 0.58824F, 0.10980F},
    vivid::srgb_t{0.58039F, 0.68235F, 0.18824F},
    vivid::srgb_t{0.52157F, 0.75294F, 0.32157F},
    vivid::srgb_t{0.45490F, 0.80784F, 0.47451F},
    vivid::srgb_t{0.39216F, 0.85490F, 0.62745F},
    vivid::srgb_t{0.38039F, 0.90196F, 0.79216F},
    vivid::srgb_t{0.50980F, 0.93725F, 0.92157F},
    vivid::srgb_t{0.70196F, 0.94902F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
