#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_HAWAII_13 = std::array{
    vivid::srgb_t{0.54902F, 0.00784F, 0.45098F},
    vivid::srgb_t{0.56863F, 0.13725F, 0.37255F},
    vivid::srgb_t{0.58039F, 0.21961F, 0.30196F},
    vivid::srgb_t{0.59216F, 0.30588F, 0.24314F},
    vivid::srgb_t{0.60000F, 0.38824F, 0.18824F},
    vivid::srgb_t{0.61176F, 0.47843F, 0.13333F},
    vivid::srgb_t{0.61176F, 0.58824F, 0.10980F},
    vivid::srgb_t{0.57255F, 0.69412F, 0.20784F},
    vivid::srgb_t{0.50196F, 0.77255F, 0.37255F},
    vivid::srgb_t{0.42353F, 0.83137F, 0.54902F},
    vivid::srgb_t{0.37255F, 0.88627F, 0.73333F},
    vivid::srgb_t{0.47843F, 0.93333F, 0.90588F},
    vivid::srgb_t{0.70196F, 0.94902F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
