#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> ICE_17
{
  {   0.01569F,   0.02353F,   0.07451F },
  {   0.07451F,   0.07451F,   0.16471F },
  {   0.12941F,   0.12549F,   0.25490F },
  {   0.18039F,   0.17255F,   0.35294F },
  {   0.21961F,   0.22353F,   0.45882F },
  {   0.24314F,   0.27843F,   0.56078F },
  {   0.24706F,   0.34118F,   0.63922F },
  {   0.24314F,   0.41176F,   0.69020F },
  {   0.25882F,   0.48235F,   0.71765F },
  {   0.29412F,   0.54510F,   0.74118F },
  {   0.34118F,   0.61176F,   0.76471F },
  {   0.40392F,   0.67843F,   0.78824F },
  {   0.47451F,   0.74510F,   0.81569F },
  {   0.57255F,   0.80784F,   0.84314F },
  {   0.68627F,   0.86667F,   0.88235F },
  {   0.80392F,   0.92549F,   0.93725F },
  {   0.91765F,   0.99216F,   0.99216F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
