#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_ICE_9 = std::array{
    vivid::srgb_t{0.01569F, 0.02353F, 0.07451F},
    vivid::srgb_t{0.12941F, 0.12549F, 0.25490F},
    vivid::srgb_t{0.21961F, 0.22353F, 0.45882F},
    vivid::srgb_t{0.24706F, 0.34118F, 0.63922F},
    vivid::srgb_t{0.25882F, 0.48235F, 0.71765F},
    vivid::srgb_t{0.34118F, 0.61176F, 0.76471F},
    vivid::srgb_t{0.47451F, 0.74510F, 0.81569F},
    vivid::srgb_t{0.68627F, 0.86667F, 0.88235F},
    vivid::srgb_t{0.91765F, 0.99216F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
