#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_ICE_11 = std::array{
    vivid::srgb_t{0.01569F, 0.02353F, 0.07451F},
    vivid::srgb_t{0.10980F, 0.10980F, 0.21961F},
    vivid::srgb_t{0.18824F, 0.18431F, 0.37255F},
    vivid::srgb_t{0.23922F, 0.26275F, 0.53725F},
    vivid::srgb_t{0.24314F, 0.36863F, 0.66275F},
    vivid::srgb_t{0.25882F, 0.48235F, 0.71765F},
    vivid::srgb_t{0.32157F, 0.58824F, 0.75686F},
    vivid::srgb_t{0.41569F, 0.69020F, 0.79608F},
    vivid::srgb_t{0.54902F, 0.79608F, 0.83922F},
    vivid::srgb_t{0.73725F, 0.89412F, 0.90588F},
    vivid::srgb_t{0.91765F, 0.99216F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
