#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_ICE_12 = std::array{
    vivid::srgb_t{0.01569F, 0.02353F, 0.07451F},
    vivid::srgb_t{0.09804F, 0.09804F, 0.20392F},
    vivid::srgb_t{0.17255F, 0.16863F, 0.34118F},
    vivid::srgb_t{0.23137F, 0.24314F, 0.49804F},
    vivid::srgb_t{0.24706F, 0.32941F, 0.62745F},
    vivid::srgb_t{0.24706F, 0.43137F, 0.69804F},
    vivid::srgb_t{0.28235F, 0.52941F, 0.73725F},
    vivid::srgb_t{0.35294F, 0.62353F, 0.76863F},
    vivid::srgb_t{0.44706F, 0.72157F, 0.80784F},
    vivid::srgb_t{0.58431F, 0.81569F, 0.84706F},
    vivid::srgb_t{0.75294F, 0.90196F, 0.90980F},
    vivid::srgb_t{0.91765F, 0.99216F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
