#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_ICE_17 = std::array{
    vivid::srgb_t{0.01569F, 0.02353F, 0.07451F},
    vivid::srgb_t{0.07451F, 0.07451F, 0.16471F},
    vivid::srgb_t{0.12941F, 0.12549F, 0.25490F},
    vivid::srgb_t{0.18039F, 0.17255F, 0.35294F},
    vivid::srgb_t{0.21961F, 0.22353F, 0.45882F},
    vivid::srgb_t{0.24314F, 0.27843F, 0.56078F},
    vivid::srgb_t{0.24706F, 0.34118F, 0.63922F},
    vivid::srgb_t{0.24314F, 0.41176F, 0.69020F},
    vivid::srgb_t{0.25882F, 0.48235F, 0.71765F},
    vivid::srgb_t{0.29412F, 0.54510F, 0.74118F},
    vivid::srgb_t{0.34118F, 0.61176F, 0.76471F},
    vivid::srgb_t{0.40392F, 0.67843F, 0.78824F},
    vivid::srgb_t{0.47451F, 0.74510F, 0.81569F},
    vivid::srgb_t{0.57255F, 0.80784F, 0.84314F},
    vivid::srgb_t{0.68627F, 0.86667F, 0.88235F},
    vivid::srgb_t{0.80392F, 0.92549F, 0.93725F},
    vivid::srgb_t{0.91765F, 0.99216F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
