#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> IMOLA_3
{
  {   0.10196F,   0.20000F,   0.70196F },
  {   0.32941F,   0.52549F,   0.49804F },
  {   1.00000F,   1.00000F,   0.40000F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
