#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_IMOLA_9 = std::array{
    vivid::srgb_t{0.10196F, 0.20000F, 0.70196F},
    vivid::srgb_t{0.14510F, 0.28627F, 0.65882F},
    vivid::srgb_t{0.18824F, 0.36863F, 0.61569F},
    vivid::srgb_t{0.24706F, 0.44314F, 0.55686F},
    vivid::srgb_t{0.32941F, 0.52549F, 0.49804F},
    vivid::srgb_t{0.43922F, 0.63922F, 0.46667F},
    vivid::srgb_t{0.56863F, 0.76471F, 0.43529F},
    vivid::srgb_t{0.74118F, 0.90196F, 0.40392F},
    vivid::srgb_t{1.00000F, 1.00000F, 0.40000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
