#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_INFERNO_14 = std::array{
    vivid::srgb_t{0.00000F, 0.00000F, 0.01569F},
    vivid::srgb_t{0.06275F, 0.03529F, 0.17647F},
    vivid::srgb_t{0.17647F, 0.04314F, 0.34902F},
    vivid::srgb_t{0.30980F, 0.05098F, 0.42353F},
    vivid::srgb_t{0.42745F, 0.09412F, 0.43137F},
    vivid::srgb_t{0.55294F, 0.13725F, 0.41176F},
    vivid::srgb_t{0.67843F, 0.18824F, 0.36471F},
    vivid::srgb_t{0.78431F, 0.24706F, 0.29412F},
    vivid::srgb_t{0.88235F, 0.33725F, 0.20784F},
    vivid::srgb_t{0.94902F, 0.45490F, 0.10980F},
    vivid::srgb_t{0.98431F, 0.58824F, 0.02353F},
    vivid::srgb_t{0.98431F, 0.73725F, 0.12941F},
    vivid::srgb_t{0.95686F, 0.88235F, 0.33725F},
    vivid::srgb_t{0.98824F, 1.00000F, 0.64314F},
};

} // namespace GOOM::COLOR::COLOR_DATA
