#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_INFERNO_4 = std::array{
    vivid::srgb_t{0.00000F, 0.00000F, 0.01569F},
    vivid::srgb_t{0.47059F, 0.10980F, 0.42745F},
    vivid::srgb_t{0.92941F, 0.41176F, 0.14510F},
    vivid::srgb_t{0.98824F, 1.00000F, 0.64314F},
};

} // namespace GOOM::COLOR::COLOR_DATA
