#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> ISLEOFDOGS2_6
{
  {   0.59608F,   0.42353F,   0.58824F },
  {   0.54118F,   0.12157F,   0.12157F },
  {   0.83529F,   0.67059F,   0.33333F },
  {   0.05490F,   0.04706F,   0.04706F },
  {   0.86275F,   0.76078F,   0.78824F },
  {   0.50980F,   0.44706F,   0.42353F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
