#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_JIM_SPECIAL_16 = std::array{
    vivid::srgb_t{0.00000F, 0.00000F, 0.00000F},
    vivid::srgb_t{0.08627F, 0.03922F, 0.13333F},
    vivid::srgb_t{0.14510F, 0.09804F, 0.26667F},
    vivid::srgb_t{0.18431F, 0.16863F, 0.38824F},
    vivid::srgb_t{0.20392F, 0.25490F, 0.49020F},
    vivid::srgb_t{0.21569F, 0.34510F, 0.57255F},
    vivid::srgb_t{0.23137F, 0.43922F, 0.62745F},
    vivid::srgb_t{0.25098F, 0.53725F, 0.66275F},
    vivid::srgb_t{0.29020F, 0.62745F, 0.67843F},
    vivid::srgb_t{0.34902F, 0.70980F, 0.68627F},
    vivid::srgb_t{0.42745F, 0.78039F, 0.69412F},
    vivid::srgb_t{0.52549F, 0.83922F, 0.70588F},
    vivid::srgb_t{0.63922F, 0.89020F, 0.74118F},
    vivid::srgb_t{0.76471F, 0.92941F, 0.79608F},
    vivid::srgb_t{0.88627F, 0.96471F, 0.88235F},
    vivid::srgb_t{1.00000F, 1.00000F, 1.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
