#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_LAJOLLA_3 = std::array{
    vivid::srgb_t{1.00000F, 1.00000F, 0.80000F},
    vivid::srgb_t{0.87059F, 0.45490F, 0.30980F},
    vivid::srgb_t{0.10196F, 0.10196F, 0.00392F},
};

} // namespace GOOM::COLOR::COLOR_DATA
