#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_LAPAZ_7 = std::array{
    vivid::srgb_t{0.10196F, 0.04706F, 0.39216F},
    vivid::srgb_t{0.14902F, 0.23529F, 0.52157F},
    vivid::srgb_t{0.21176F, 0.40392F, 0.61569F},
    vivid::srgb_t{0.36078F, 0.54902F, 0.63922F},
    vivid::srgb_t{0.58039F, 0.63529F, 0.59608F},
    vivid::srgb_t{0.85098F, 0.75294F, 0.65490F},
    vivid::srgb_t{0.99608F, 0.94902F, 0.95294F},
};

} // namespace GOOM::COLOR::COLOR_DATA
