#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> LAPAZ_6
{
  {   0.10196F,   0.04706F,   0.39216F },
  {   0.15686F,   0.27451F,   0.54510F },
  {   0.25882F,   0.46667F,   0.63529F },
  {   0.48627F,   0.60784F,   0.61961F },
  {   0.79216F,   0.71765F,   0.61569F },
  {   0.99608F,   0.94902F,   0.95294F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
