#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> LAPAZ_8
{
  {   0.10196F,   0.04706F,   0.39216F },
  {   0.14510F,   0.21176F,   0.50588F },
  {   0.18824F,   0.36078F,   0.59608F },
  {   0.28235F,   0.49020F,   0.63922F },
  {   0.45098F,   0.59608F,   0.62745F },
  {   0.64706F,   0.65490F,   0.58431F },
  {   0.89412F,   0.78824F,   0.69804F },
  {   0.99608F,   0.94902F,   0.95294F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
