#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> LINEARL_12
{
  {   0.01569F,   0.01569F,   0.01569F },
  {   0.16863F,   0.07451F,   0.14902F },
  {   0.17255F,   0.12549F,   0.43137F },
  {   0.10588F,   0.24706F,   0.52157F },
  {   0.01176F,   0.37647F,   0.43922F },
  {   0.00000F,   0.49804F,   0.32157F },
  {   0.00000F,   0.61569F,   0.19608F },
  {   0.23922F,   0.70588F,   0.00000F },
  {   0.58431F,   0.76863F,   0.00000F },
  {   0.85882F,   0.80784F,   0.47451F },
  {   0.96863F,   0.88627F,   0.81961F },
  {   1.00000F,   1.00000F,   1.00000F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
