#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_LINEARL_19 = std::array{
    vivid::srgb_t{0.01569F, 0.01569F, 0.01569F},
    vivid::srgb_t{0.12941F, 0.05098F, 0.11373F},
    vivid::srgb_t{0.17647F, 0.08235F, 0.21569F},
    vivid::srgb_t{0.17255F, 0.11373F, 0.39216F},
    vivid::srgb_t{0.12157F, 0.19216F, 0.47451F},
    vivid::srgb_t{0.10980F, 0.25098F, 0.52549F},
    vivid::srgb_t{0.03922F, 0.33333F, 0.47843F},
    vivid::srgb_t{0.00000F, 0.40784F, 0.41569F},
    vivid::srgb_t{0.00000F, 0.48235F, 0.33725F},
    vivid::srgb_t{0.00000F, 0.55686F, 0.24706F},
    vivid::srgb_t{0.00000F, 0.62745F, 0.17647F},
    vivid::srgb_t{0.15686F, 0.68235F, 0.00000F},
    vivid::srgb_t{0.30980F, 0.73725F, 0.00000F},
    vivid::srgb_t{0.56863F, 0.76471F, 0.00000F},
    vivid::srgb_t{0.77255F, 0.78824F, 0.00000F},
    vivid::srgb_t{0.88627F, 0.81176F, 0.54118F},
    vivid::srgb_t{0.96863F, 0.85882F, 0.76471F},
    vivid::srgb_t{0.96863F, 0.93333F, 0.90588F},
    vivid::srgb_t{1.00000F, 1.00000F, 1.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
