#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> LINEARL_3
{
  {   0.01569F,   0.01569F,   0.01569F },
  {   0.00000F,   0.55686F,   0.24706F },
  {   1.00000F,   1.00000F,   1.00000F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
