#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_LINEARL_17 = std::array{
    vivid::srgb_t{0.01569F, 0.01569F, 0.01569F},
    vivid::srgb_t{0.14118F, 0.05490F, 0.12549F},
    vivid::srgb_t{0.17647F, 0.09020F, 0.27843F},
    vivid::srgb_t{0.17255F, 0.13333F, 0.45490F},
    vivid::srgb_t{0.10588F, 0.22353F, 0.49804F},
    vivid::srgb_t{0.06667F, 0.30588F, 0.50588F},
    vivid::srgb_t{0.00000F, 0.39216F, 0.42745F},
    vivid::srgb_t{0.00000F, 0.47451F, 0.34510F},
    vivid::srgb_t{0.00000F, 0.55686F, 0.24706F},
    vivid::srgb_t{0.00000F, 0.63529F, 0.17255F},
    vivid::srgb_t{0.20392F, 0.69412F, 0.00000F},
    vivid::srgb_t{0.36078F, 0.75686F, 0.00000F},
    vivid::srgb_t{0.67451F, 0.77647F, 0.00000F},
    vivid::srgb_t{0.84314F, 0.80392F, 0.42745F},
    vivid::srgb_t{0.96078F, 0.83922F, 0.71765F},
    vivid::srgb_t{0.96863F, 0.92157F, 0.88235F},
    vivid::srgb_t{1.00000F, 1.00000F, 1.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
