#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_LISBON_19 = std::array{
    vivid::srgb_t{0.90196F, 0.89804F, 1.00000F},
    vivid::srgb_t{0.75294F, 0.79216F, 0.91373F},
    vivid::srgb_t{0.60784F, 0.68627F, 0.82745F},
    vivid::srgb_t{0.46667F, 0.58039F, 0.74118F},
    vivid::srgb_t{0.31765F, 0.46667F, 0.64314F},
    vivid::srgb_t{0.19608F, 0.36078F, 0.53333F},
    vivid::srgb_t{0.11765F, 0.26275F, 0.40784F},
    vivid::srgb_t{0.07843F, 0.18039F, 0.28235F},
    vivid::srgb_t{0.06667F, 0.11765F, 0.17255F},
    vivid::srgb_t{0.09020F, 0.09804F, 0.09804F},
    vivid::srgb_t{0.15294F, 0.14510F, 0.10196F},
    vivid::srgb_t{0.24314F, 0.22745F, 0.14510F},
    vivid::srgb_t{0.34118F, 0.31765F, 0.20392F},
    vivid::srgb_t{0.44314F, 0.41961F, 0.26667F},
    vivid::srgb_t{0.55294F, 0.52157F, 0.33725F},
    vivid::srgb_t{0.67059F, 0.63529F, 0.43137F},
    vivid::srgb_t{0.78824F, 0.76471F, 0.56471F},
    vivid::srgb_t{0.89412F, 0.88235F, 0.70588F},
    vivid::srgb_t{1.00000F, 1.00000F, 0.85098F},
};

} // namespace GOOM::COLOR::COLOR_DATA
