#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> LISBON_8
{
  {   0.90196F,   0.89804F,   1.00000F },
  {   0.52549F,   0.62745F,   0.77647F },
  {   0.18431F,   0.34902F,   0.51765F },
  {   0.06667F,   0.13333F,   0.20000F },
  {   0.17647F,   0.16863F,   0.10980F },
  {   0.42745F,   0.40392F,   0.25490F },
  {   0.72549F,   0.69412F,   0.49020F },
  {   1.00000F,   1.00000F,   0.85098F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
