#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> LISBON_3
{
  {   0.90196F,   0.89804F,   1.00000F },
  {   0.09020F,   0.09804F,   0.09804F },
  {   1.00000F,   1.00000F,   0.85098F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
