#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_LISBON_15 = std::array{
    vivid::srgb_t{0.90196F, 0.89804F, 1.00000F},
    vivid::srgb_t{0.70980F, 0.76078F, 0.88627F},
    vivid::srgb_t{0.52549F, 0.62745F, 0.77647F},
    vivid::srgb_t{0.33725F, 0.48235F, 0.65490F},
    vivid::srgb_t{0.18431F, 0.34902F, 0.51765F},
    vivid::srgb_t{0.09804F, 0.22745F, 0.35294F},
    vivid::srgb_t{0.06667F, 0.13333F, 0.20000F},
    vivid::srgb_t{0.09020F, 0.09804F, 0.09804F},
    vivid::srgb_t{0.17647F, 0.16863F, 0.10980F},
    vivid::srgb_t{0.29804F, 0.27843F, 0.17647F},
    vivid::srgb_t{0.42745F, 0.40392F, 0.25490F},
    vivid::srgb_t{0.56863F, 0.53725F, 0.34902F},
    vivid::srgb_t{0.72549F, 0.69412F, 0.49020F},
    vivid::srgb_t{0.86275F, 0.84706F, 0.66275F},
    vivid::srgb_t{1.00000F, 1.00000F, 0.85098F},
};

} // namespace GOOM::COLOR::COLOR_DATA
