#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_LISBON_3 = std::array{
    vivid::srgb_t{0.90196F, 0.89804F, 1.00000F},
    vivid::srgb_t{0.09020F, 0.09804F, 0.09804F},
    vivid::srgb_t{1.00000F, 1.00000F, 0.85098F},
};

} // namespace GOOM::COLOR::COLOR_DATA
