#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> MAGENTA_2
{
  {   0.95294F,   0.79608F,   0.82745F },
  {   0.42353F,   0.12941F,   0.40392F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
