#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_MAGENTA_4 = std::array{
    vivid::srgb_t{0.95294F, 0.79608F, 0.82745F},
    vivid::srgb_t{0.86667F, 0.53333F, 0.67451F},
    vivid::srgb_t{0.69412F, 0.30196F, 0.55686F},
    vivid::srgb_t{0.42353F, 0.12941F, 0.40392F},
};

} // namespace GOOM::COLOR::COLOR_DATA
