#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> MAGMA_16
{
  {   0.00000F,   0.00000F,   0.01569F },
  {   0.04314F,   0.03529F,   0.14118F },
  {   0.12549F,   0.06667F,   0.29412F },
  {   0.23137F,   0.05882F,   0.43922F },
  {   0.34118F,   0.08235F,   0.49412F },
  {   0.44706F,   0.12157F,   0.50588F },
  {   0.54902F,   0.16078F,   0.50588F },
  {   0.65882F,   0.19608F,   0.49020F },
  {   0.76863F,   0.23529F,   0.45882F },
  {   0.87059F,   0.28627F,   0.40784F },
  {   0.94510F,   0.37647F,   0.36471F },
  {   0.98039F,   0.49804F,   0.36863F },
  {   0.99608F,   0.62353F,   0.42745F },
  {   0.99608F,   0.74902F,   0.51765F },
  {   0.99216F,   0.87059F,   0.62745F },
  {   0.98824F,   0.99216F,   0.74902F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
