#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_MAGMA_13 = std::array{
    vivid::srgb_t{0.00000F, 0.00000F, 0.01569F},
    vivid::srgb_t{0.06275F, 0.04314F, 0.17647F},
    vivid::srgb_t{0.17255F, 0.06667F, 0.37255F},
    vivid::srgb_t{0.31765F, 0.07059F, 0.48627F},
    vivid::srgb_t{0.44706F, 0.12157F, 0.50588F},
    vivid::srgb_t{0.57647F, 0.16863F, 0.50196F},
    vivid::srgb_t{0.71765F, 0.21569F, 0.47451F},
    vivid::srgb_t{0.84706F, 0.27059F, 0.42353F},
    vivid::srgb_t{0.94510F, 0.37647F, 0.36471F},
    vivid::srgb_t{0.98431F, 0.52941F, 0.38039F},
    vivid::srgb_t{0.99608F, 0.68235F, 0.46667F},
    vivid::srgb_t{0.99608F, 0.84314F, 0.60000F},
    vivid::srgb_t{0.98824F, 0.99216F, 0.74902F},
};

} // namespace GOOM::COLOR::COLOR_DATA
