#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_MAGMA_11 = std::array{
    vivid::srgb_t{0.00000F, 0.00000F, 0.01569F},
    vivid::srgb_t{0.08235F, 0.05490F, 0.21961F},
    vivid::srgb_t{0.23137F, 0.05882F, 0.43922F},
    vivid::srgb_t{0.39216F, 0.10196F, 0.50196F},
    vivid::srgb_t{0.54902F, 0.16078F, 0.50588F},
    vivid::srgb_t{0.71765F, 0.21569F, 0.47451F},
    vivid::srgb_t{0.87059F, 0.28627F, 0.40784F},
    vivid::srgb_t{0.96471F, 0.43137F, 0.36078F},
    vivid::srgb_t{0.99608F, 0.62353F, 0.42745F},
    vivid::srgb_t{0.99608F, 0.81176F, 0.57255F},
    vivid::srgb_t{0.98824F, 0.99216F, 0.74902F},
};

} // namespace GOOM::COLOR::COLOR_DATA
