#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> MAGMA_3
{
  {   0.00000F,   0.00000F,   0.01569F },
  {   0.71765F,   0.21569F,   0.47451F },
  {   0.98824F,   0.99216F,   0.74902F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
