#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// NOLINTNEXTLINE(cert-err58-cpp): Fix with C++20 and 'constexpr'.
inline const auto MARGOT1_5 = std::vector<vivid::srgb_t>{
    {0.53725F, 0.46667F, 0.07059F},
    {0.95294F, 0.76078F, 0.64314F},
    {0.96471F, 0.62353F, 0.59216F},
    {0.99608F, 0.83922F, 0.54902F},
    {0.38431F, 0.56471F, 0.45882F},
};

} // namespace GOOM::COLOR::COLOR_DATA
