#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_MARGOT3_4 = std::array{
    vivid::srgb_t{0.52941F, 0.63529F, 0.64314F},
    vivid::srgb_t{0.79216F, 0.62745F, 0.39608F},
    vivid::srgb_t{0.83922F, 0.79216F, 0.74902F},
    vivid::srgb_t{0.83922F, 0.62745F, 0.62745F},
};

} // namespace GOOM::COLOR::COLOR_DATA
