#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_MATTER_12 = std::array{
    vivid::srgb_t{0.99608F, 0.92941F, 0.69020F},
    vivid::srgb_t{0.98039F, 0.80392F, 0.57255F},
    vivid::srgb_t{0.96471F, 0.68235F, 0.47059F},
    vivid::srgb_t{0.94118F, 0.55294F, 0.38431F},
    vivid::srgb_t{0.90588F, 0.43137F, 0.33333F},
    vivid::srgb_t{0.85098F, 0.31373F, 0.32549F},
    vivid::srgb_t{0.76471F, 0.22353F, 0.35294F},
    vivid::srgb_t{0.66275F, 0.15686F, 0.38039F},
    vivid::srgb_t{0.54902F, 0.11765F, 0.38824F},
    vivid::srgb_t{0.41961F, 0.09804F, 0.36863F},
    vivid::srgb_t{0.30196F, 0.08235F, 0.31765F},
    vivid::srgb_t{0.18431F, 0.05882F, 0.24314F},
};

} // namespace GOOM::COLOR::COLOR_DATA
