#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> MINT_4
{
  {   0.89412F,   0.94510F,   0.88235F },
  {   0.53725F,   0.75294F,   0.71373F },
  {   0.26667F,   0.54902F,   0.54118F },
  {   0.05098F,   0.34510F,   0.37255F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
