#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// NOLINTNEXTLINE(cert-err58-cpp): Fix with C++20 and 'constexpr'.
inline const auto MINT_5 = std::vector<vivid::srgb_t>{
    {0.89412F, 0.94510F, 0.88235F},
    {0.53725F, 0.75294F, 0.71373F},
    {0.38824F, 0.65098F, 0.62745F},
    {0.26667F, 0.54902F, 0.54118F},
    {0.05098F, 0.34510F, 0.37255F},
};

} // namespace GOOM::COLOR::COLOR_DATA
