#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_NUUK_16 = std::array{
    vivid::srgb_t{0.01961F, 0.34902F, 0.54902F},
    vivid::srgb_t{0.11765F, 0.36863F, 0.52549F},
    vivid::srgb_t{0.18431F, 0.39608F, 0.51373F},
    vivid::srgb_t{0.26275F, 0.43137F, 0.50980F},
    vivid::srgb_t{0.34510F, 0.47843F, 0.52549F},
    vivid::srgb_t{0.43529F, 0.52941F, 0.55294F},
    vivid::srgb_t{0.52157F, 0.58039F, 0.57647F},
    vivid::srgb_t{0.59608F, 0.62745F, 0.59216F},
    vivid::srgb_t{0.65490F, 0.66667F, 0.59216F},
    vivid::srgb_t{0.69804F, 0.69804F, 0.57647F},
    vivid::srgb_t{0.72941F, 0.72549F, 0.55294F},
    vivid::srgb_t{0.75686F, 0.75686F, 0.52941F},
    vivid::srgb_t{0.79216F, 0.79216F, 0.51373F},
    vivid::srgb_t{0.85098F, 0.85098F, 0.53333F},
    vivid::srgb_t{0.92941F, 0.92941F, 0.60392F},
    vivid::srgb_t{0.99608F, 0.99608F, 0.69804F},
};

} // namespace GOOM::COLOR::COLOR_DATA
