#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_NUUK_5 = std::array{
    vivid::srgb_t{0.01961F, 0.34902F, 0.54902F},
    vivid::srgb_t{0.32549F, 0.46667F, 0.52157F},
    vivid::srgb_t{0.63137F, 0.65098F, 0.59608F},
    vivid::srgb_t{0.76471F, 0.76078F, 0.52157F},
    vivid::srgb_t{0.99608F, 0.99608F, 0.69804F},
};

} // namespace GOOM::COLOR::COLOR_DATA
