#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> OLERON_4
{
  {   0.10196F,   0.14902F,   0.34902F },
  {   0.66667F,   0.71765F,   0.90980F },
  {   0.47843F,   0.44314F,   0.12157F },
  {   0.99216F,   0.99216F,   0.90196F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
