#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_ORANGES_7 = std::array{
    vivid::srgb_t{0.99608F, 0.92941F, 0.87059F},
    vivid::srgb_t{0.99216F, 0.81569F, 0.63529F},
    vivid::srgb_t{0.99216F, 0.68235F, 0.41961F},
    vivid::srgb_t{0.99216F, 0.55294F, 0.23529F},
    vivid::srgb_t{0.94510F, 0.41176F, 0.07451F},
    vivid::srgb_t{0.85098F, 0.28235F, 0.00392F},
    vivid::srgb_t{0.54902F, 0.17647F, 0.01569F},
};

} // namespace GOOM::COLOR::COLOR_DATA
