#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> ORANGES_7
{
  {   0.99608F,   0.92941F,   0.87059F },
  {   0.99216F,   0.81569F,   0.63529F },
  {   0.99216F,   0.68235F,   0.41961F },
  {   0.99216F,   0.55294F,   0.23529F },
  {   0.94510F,   0.41176F,   0.07451F },
  {   0.85098F,   0.28235F,   0.00392F },
  {   0.54902F,   0.17647F,   0.01569F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
