#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> ORANGES_4
{
  {   0.99608F,   0.92941F,   0.87059F },
  {   0.99216F,   0.74510F,   0.52157F },
  {   0.99216F,   0.55294F,   0.23529F },
  {   0.85098F,   0.27843F,   0.00392F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
