#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_ORANGES_5 = std::array{
    vivid::srgb_t{0.99608F, 0.92941F, 0.87059F},
    vivid::srgb_t{0.99216F, 0.74510F, 0.52157F},
    vivid::srgb_t{0.99216F, 0.55294F, 0.23529F},
    vivid::srgb_t{0.90196F, 0.33333F, 0.05098F},
    vivid::srgb_t{0.65098F, 0.21176F, 0.01176F},
};

} // namespace GOOM::COLOR::COLOR_DATA
