#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_ORRD_4 = std::array{
    vivid::srgb_t{0.99608F, 0.94118F, 0.85098F},
    vivid::srgb_t{0.99216F, 0.80000F, 0.54118F},
    vivid::srgb_t{0.98824F, 0.55294F, 0.34902F},
    vivid::srgb_t{0.84314F, 0.18824F, 0.12157F},
};

} // namespace GOOM::COLOR::COLOR_DATA
