#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_ORYEL_4 = std::array{
    vivid::srgb_t{0.92549F, 0.85490F, 0.60392F},
    vivid::srgb_t{0.95294F, 0.67843F, 0.41569F},
    vivid::srgb_t{0.97647F, 0.48235F, 0.34118F},
    vivid::srgb_t{0.93333F, 0.30196F, 0.35294F},
};

} // namespace GOOM::COLOR::COLOR_DATA
