#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_OXY_18 = std::array{
    vivid::srgb_t{0.25098F, 0.01961F, 0.01961F},
    vivid::srgb_t{0.34510F, 0.02745F, 0.04314F},
    vivid::srgb_t{0.44706F, 0.02353F, 0.05882F},
    vivid::srgb_t{0.53725F, 0.06275F, 0.03922F},
    vivid::srgb_t{0.34510F, 0.34118F, 0.34118F},
    vivid::srgb_t{0.40000F, 0.40000F, 0.39608F},
    vivid::srgb_t{0.45490F, 0.45098F, 0.45098F},
    vivid::srgb_t{0.51373F, 0.51373F, 0.50980F},
    vivid::srgb_t{0.57255F, 0.57255F, 0.56863F},
    vivid::srgb_t{0.63922F, 0.63529F, 0.63137F},
    vivid::srgb_t{0.70196F, 0.70196F, 0.69804F},
    vivid::srgb_t{0.77255F, 0.77255F, 0.76471F},
    vivid::srgb_t{0.83922F, 0.83922F, 0.83529F},
    vivid::srgb_t{0.91765F, 0.91373F, 0.90980F},
    vivid::srgb_t{0.93725F, 0.97255F, 0.34118F},
    vivid::srgb_t{0.90980F, 0.87451F, 0.19216F},
    vivid::srgb_t{0.89020F, 0.77647F, 0.13725F},
    vivid::srgb_t{0.86667F, 0.68627F, 0.09804F},
};

} // namespace GOOM::COLOR::COLOR_DATA
