#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_OXY_17 = std::array{
    vivid::srgb_t{0.25098F, 0.01961F, 0.01961F},
    vivid::srgb_t{0.35686F, 0.02745F, 0.04706F},
    vivid::srgb_t{0.46275F, 0.01961F, 0.05882F},
    vivid::srgb_t{0.55294F, 0.08235F, 0.03137F},
    vivid::srgb_t{0.36078F, 0.35686F, 0.35686F},
    vivid::srgb_t{0.41961F, 0.41569F, 0.41569F},
    vivid::srgb_t{0.47843F, 0.47843F, 0.47451F},
    vivid::srgb_t{0.54118F, 0.54118F, 0.53725F},
    vivid::srgb_t{0.60784F, 0.60392F, 0.60392F},
    vivid::srgb_t{0.67059F, 0.67059F, 0.66667F},
    vivid::srgb_t{0.74118F, 0.74118F, 0.73725F},
    vivid::srgb_t{0.81569F, 0.81569F, 0.81176F},
    vivid::srgb_t{0.89412F, 0.89412F, 0.89020F},
    vivid::srgb_t{0.95686F, 0.98824F, 0.38431F},
    vivid::srgb_t{0.91373F, 0.89020F, 0.20392F},
    vivid::srgb_t{0.89412F, 0.78431F, 0.14510F},
    vivid::srgb_t{0.86667F, 0.68627F, 0.09804F},
};

} // namespace GOOM::COLOR::COLOR_DATA
