#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_OXY_5 = std::array{
    vivid::srgb_t{0.25098F, 0.01961F, 0.01961F},
    vivid::srgb_t{0.36078F, 0.35686F, 0.35686F},
    vivid::srgb_t{0.60784F, 0.60392F, 0.60392F},
    vivid::srgb_t{0.89412F, 0.89412F, 0.89020F},
    vivid::srgb_t{0.86667F, 0.68627F, 0.09804F},
};

} // namespace GOOM::COLOR::COLOR_DATA
