#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_PASTEL1_4 = std::array{
    vivid::srgb_t{0.98431F, 0.70588F, 0.68235F},
    vivid::srgb_t{0.70196F, 0.80392F, 0.89020F},
    vivid::srgb_t{0.80000F, 0.92157F, 0.77255F},
    vivid::srgb_t{0.87059F, 0.79608F, 0.89412F},
};

} // namespace GOOM::COLOR::COLOR_DATA
