#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> PASTEL_9
{
  {   0.40000F,   0.77255F,   0.80000F },
  {   0.96471F,   0.81176F,   0.44314F },
  {   0.97255F,   0.61176F,   0.45490F },
  {   0.86275F,   0.69020F,   0.94902F },
  {   0.52941F,   0.77255F,   0.37255F },
  {   0.61961F,   0.72549F,   0.95294F },
  {   0.99608F,   0.53333F,   0.69412F },
  {   0.78824F,   0.85882F,   0.45490F },
  {   0.54510F,   0.87843F,   0.64314F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
