#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_PASTEL_3 = std::array{
    vivid::srgb_t{0.40000F, 0.77255F, 0.80000F},
    vivid::srgb_t{0.96471F, 0.81176F, 0.44314F},
    vivid::srgb_t{0.97255F, 0.61176F, 0.45490F},
};

} // namespace GOOM::COLOR::COLOR_DATA
