#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> PASTEL_3
{
  {   0.40000F,   0.77255F,   0.80000F },
  {   0.96471F,   0.81176F,   0.44314F },
  {   0.97255F,   0.61176F,   0.45490F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
