#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_PHASE_14 = std::array{
    vivid::srgb_t{0.65882F, 0.47059F, 0.05098F},
    vivid::srgb_t{0.76078F, 0.39216F, 0.18039F},
    vivid::srgb_t{0.83529F, 0.30196F, 0.31765F},
    vivid::srgb_t{0.87451F, 0.19216F, 0.51765F},
    vivid::srgb_t{0.84314F, 0.15294F, 0.74510F},
    vivid::srgb_t{0.74118F, 0.27059F, 0.90980F},
    vivid::srgb_t{0.58431F, 0.39608F, 0.95686F},
    vivid::srgb_t{0.40000F, 0.49412F, 0.90588F},
    vivid::srgb_t{0.19608F, 0.55686F, 0.76078F},
    vivid::srgb_t{0.09412F, 0.58431F, 0.60392F},
    vivid::srgb_t{0.04706F, 0.60000F, 0.45098F},
    vivid::srgb_t{0.25098F, 0.59608F, 0.22353F},
    vivid::srgb_t{0.49804F, 0.54510F, 0.05882F},
    vivid::srgb_t{0.65882F, 0.47059F, 0.05098F},
};

} // namespace GOOM::COLOR::COLOR_DATA
