#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_PHASE_19 = std::array{
    vivid::srgb_t{0.65882F, 0.47059F, 0.05098F},
    vivid::srgb_t{0.73333F, 0.41569F, 0.14510F},
    vivid::srgb_t{0.79608F, 0.35294F, 0.23529F},
    vivid::srgb_t{0.84314F, 0.28627F, 0.34118F},
    vivid::srgb_t{0.87059F, 0.20000F, 0.49412F},
    vivid::srgb_t{0.86275F, 0.14510F, 0.66275F},
    vivid::srgb_t{0.81569F, 0.18431F, 0.81569F},
    vivid::srgb_t{0.73333F, 0.27451F, 0.91373F},
    vivid::srgb_t{0.62745F, 0.36471F, 0.95686F},
    vivid::srgb_t{0.49020F, 0.45098F, 0.94118F},
    vivid::srgb_t{0.34510F, 0.51373F, 0.87451F},
    vivid::srgb_t{0.20392F, 0.55686F, 0.76863F},
    vivid::srgb_t{0.11765F, 0.57647F, 0.65882F},
    vivid::srgb_t{0.07059F, 0.59216F, 0.54902F},
    vivid::srgb_t{0.05490F, 0.60000F, 0.43137F},
    vivid::srgb_t{0.19216F, 0.60000F, 0.27451F},
    vivid::srgb_t{0.40784F, 0.56863F, 0.09804F},
    vivid::srgb_t{0.55294F, 0.52157F, 0.05098F},
    vivid::srgb_t{0.65882F, 0.47059F, 0.05098F},
};

} // namespace GOOM::COLOR::COLOR_DATA
