#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_PHASE_4 = std::array{
    vivid::srgb_t{0.65882F, 0.47059F, 0.05098F},
    vivid::srgb_t{0.81569F, 0.18431F, 0.81569F},
    vivid::srgb_t{0.11765F, 0.57647F, 0.65882F},
    vivid::srgb_t{0.65882F, 0.47059F, 0.05098F},
};

} // namespace GOOM::COLOR::COLOR_DATA
