#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_PHASE_5 = std::array{
    vivid::srgb_t{0.65882F, 0.47059F, 0.05098F},
    vivid::srgb_t{0.87451F, 0.16471F, 0.57647F},
    vivid::srgb_t{0.49020F, 0.45098F, 0.94118F},
    vivid::srgb_t{0.04706F, 0.59608F, 0.49412F},
    vivid::srgb_t{0.65882F, 0.47059F, 0.05098F},
};

} // namespace GOOM::COLOR::COLOR_DATA
