#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> PINKYL_2
{
  {   0.99608F,   0.96471F,   0.70980F },
  {   0.88235F,   0.32549F,   0.51373F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
