#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_PIYG_6 = std::array{
    vivid::srgb_t{0.77255F, 0.10588F, 0.49020F},
    vivid::srgb_t{0.91373F, 0.63922F, 0.78824F},
    vivid::srgb_t{0.99216F, 0.87843F, 0.93725F},
    vivid::srgb_t{0.90196F, 0.96078F, 0.81569F},
    vivid::srgb_t{0.63137F, 0.84314F, 0.41569F},
    vivid::srgb_t{0.30196F, 0.57255F, 0.12941F},
};

} // namespace GOOM::COLOR::COLOR_DATA
