#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_PLASMA_7 = std::array{
    vivid::srgb_t{0.05098F, 0.03137F, 0.52941F},
    vivid::srgb_t{0.36078F, 0.00392F, 0.65098F},
    vivid::srgb_t{0.61176F, 0.09020F, 0.61961F},
    vivid::srgb_t{0.80000F, 0.27843F, 0.47059F},
    vivid::srgb_t{0.92941F, 0.47451F, 0.32549F},
    vivid::srgb_t{0.99216F, 0.69804F, 0.18431F},
    vivid::srgb_t{0.94118F, 0.97647F, 0.12941F},
};

} // namespace GOOM::COLOR::COLOR_DATA
