#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_PLASMA_20 = std::array{
    vivid::srgb_t{0.05098F, 0.03137F, 0.52941F},
    vivid::srgb_t{0.17255F, 0.01961F, 0.58039F},
    vivid::srgb_t{0.26667F, 0.01176F, 0.61961F},
    vivid::srgb_t{0.34902F, 0.00392F, 0.64706F},
    vivid::srgb_t{0.43529F, 0.00000F, 0.65882F},
    vivid::srgb_t{0.51373F, 0.01961F, 0.65490F},
    vivid::srgb_t{0.58824F, 0.07451F, 0.63137F},
    vivid::srgb_t{0.65490F, 0.12941F, 0.59216F},
    vivid::srgb_t{0.71373F, 0.18824F, 0.54510F},
    vivid::srgb_t{0.77255F, 0.25098F, 0.49412F},
    vivid::srgb_t{0.81961F, 0.30588F, 0.44706F},
    vivid::srgb_t{0.86667F, 0.36863F, 0.40000F},
    vivid::srgb_t{0.90588F, 0.43137F, 0.35686F},
    vivid::srgb_t{0.93725F, 0.49412F, 0.31373F},
    vivid::srgb_t{0.96863F, 0.56471F, 0.26667F},
    vivid::srgb_t{0.98431F, 0.63529F, 0.21961F},
    vivid::srgb_t{0.99608F, 0.71765F, 0.17647F},
    vivid::srgb_t{0.99216F, 0.79608F, 0.14902F},
    vivid::srgb_t{0.96863F, 0.88627F, 0.14510F},
    vivid::srgb_t{0.94118F, 0.97647F, 0.12941F},
};

} // namespace GOOM::COLOR::COLOR_DATA
