#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_PLASMA_16 = std::array{
    vivid::srgb_t{0.05098F, 0.03137F, 0.52941F},
    vivid::srgb_t{0.20000F, 0.01961F, 0.59216F},
    vivid::srgb_t{0.31373F, 0.00784F, 0.63529F},
    vivid::srgb_t{0.41569F, 0.00000F, 0.65882F},
    vivid::srgb_t{0.51765F, 0.01961F, 0.65490F},
    vivid::srgb_t{0.61176F, 0.09020F, 0.61961F},
    vivid::srgb_t{0.69412F, 0.16471F, 0.56471F},
    vivid::srgb_t{0.76471F, 0.23922F, 0.50196F},
    vivid::srgb_t{0.82745F, 0.31765F, 0.44314F},
    vivid::srgb_t{0.88235F, 0.39216F, 0.38431F},
    vivid::srgb_t{0.92941F, 0.47451F, 0.32549F},
    vivid::srgb_t{0.96471F, 0.56078F, 0.26667F},
    vivid::srgb_t{0.98824F, 0.65098F, 0.21176F},
    vivid::srgb_t{0.99608F, 0.75294F, 0.16078F},
    vivid::srgb_t{0.97647F, 0.86275F, 0.14118F},
    vivid::srgb_t{0.94118F, 0.97647F, 0.12941F},
};

} // namespace GOOM::COLOR::COLOR_DATA
