#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> PLASMA_3
{
  {   0.05098F,   0.03137F,   0.52941F },
  {   0.80000F,   0.27843F,   0.47059F },
  {   0.94118F,   0.97647F,   0.12941F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
