#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_PRGN_6 = std::array{
    vivid::srgb_t{0.46275F, 0.16471F, 0.51373F},
    vivid::srgb_t{0.68627F, 0.55294F, 0.76471F},
    vivid::srgb_t{0.90588F, 0.83137F, 0.90980F},
    vivid::srgb_t{0.85098F, 0.94118F, 0.82745F},
    vivid::srgb_t{0.49804F, 0.74902F, 0.48235F},
    vivid::srgb_t{0.10588F, 0.47059F, 0.21569F},
};

} // namespace GOOM::COLOR::COLOR_DATA
