#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_PRGN_11 = std::array{
    vivid::srgb_t{0.25098F, 0.00000F, 0.29412F},
    vivid::srgb_t{0.46275F, 0.16471F, 0.51373F},
    vivid::srgb_t{0.60000F, 0.43922F, 0.67059F},
    vivid::srgb_t{0.76078F, 0.64706F, 0.81176F},
    vivid::srgb_t{0.90588F, 0.83137F, 0.90980F},
    vivid::srgb_t{0.96863F, 0.96863F, 0.96863F},
    vivid::srgb_t{0.85098F, 0.94118F, 0.82745F},
    vivid::srgb_t{0.65098F, 0.85882F, 0.62745F},
    vivid::srgb_t{0.35294F, 0.68235F, 0.38039F},
    vivid::srgb_t{0.10588F, 0.47059F, 0.21569F},
    vivid::srgb_t{0.00000F, 0.26667F, 0.10588F},
};

} // namespace GOOM::COLOR::COLOR_DATA
