#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_PRGN_3 = std::array{
    vivid::srgb_t{0.68627F, 0.55294F, 0.76471F},
    vivid::srgb_t{0.96863F, 0.96863F, 0.96863F},
    vivid::srgb_t{0.49804F, 0.74902F, 0.48235F},
};

} // namespace GOOM::COLOR::COLOR_DATA
