#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_PRGN_4 = std::array{
    vivid::srgb_t{0.48235F, 0.19608F, 0.58039F},
    vivid::srgb_t{0.76078F, 0.64706F, 0.81176F},
    vivid::srgb_t{0.65098F, 0.85882F, 0.62745F},
    vivid::srgb_t{0.00000F, 0.53333F, 0.21569F},
};

} // namespace GOOM::COLOR::COLOR_DATA
