#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_PRISM_3 = std::array{
    vivid::srgb_t{0.37255F, 0.27451F, 0.56471F},
    vivid::srgb_t{0.11373F, 0.41176F, 0.58824F},
    vivid::srgb_t{0.21961F, 0.65098F, 0.64706F},
};

} // namespace GOOM::COLOR::COLOR_DATA
