#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_PUBUGN_3 = std::array{
    vivid::srgb_t{0.92549F, 0.88627F, 0.94118F},
    vivid::srgb_t{0.65098F, 0.74118F, 0.85882F},
    vivid::srgb_t{0.10980F, 0.56471F, 0.60000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
