#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// NOLINTNEXTLINE(cert-err58-cpp): Fix with C++20 and 'constexpr'.
inline const auto PUBU_3 = std::vector<vivid::srgb_t>{
    {0.92549F, 0.90588F, 0.94902F},
    {0.65098F, 0.74118F, 0.85882F},
    {0.16863F, 0.54902F, 0.74510F},
};

} // namespace GOOM::COLOR::COLOR_DATA
