#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> PUOR_3
{
  {   0.94510F,   0.63922F,   0.25098F },
  {   0.96863F,   0.96863F,   0.96863F },
  {   0.60000F,   0.55686F,   0.76471F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
