#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> PURD_5
{
  {   0.94510F,   0.93333F,   0.96471F },
  {   0.84314F,   0.70980F,   0.84706F },
  {   0.87451F,   0.39608F,   0.69020F },
  {   0.86667F,   0.10980F,   0.46667F },
  {   0.59608F,   0.00000F,   0.26275F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
