#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_PURD_6 = std::array{
    vivid::srgb_t{0.94510F, 0.93333F, 0.96471F},
    vivid::srgb_t{0.83137F, 0.72549F, 0.85490F},
    vivid::srgb_t{0.78824F, 0.58039F, 0.78039F},
    vivid::srgb_t{0.87451F, 0.39608F, 0.69020F},
    vivid::srgb_t{0.86667F, 0.10980F, 0.46667F},
    vivid::srgb_t{0.59608F, 0.00000F, 0.26275F},
};

} // namespace GOOM::COLOR::COLOR_DATA
