#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_PURD_7 = std::array{
    vivid::srgb_t{0.94510F, 0.93333F, 0.96471F},
    vivid::srgb_t{0.83137F, 0.72549F, 0.85490F},
    vivid::srgb_t{0.78824F, 0.58039F, 0.78039F},
    vivid::srgb_t{0.87451F, 0.39608F, 0.69020F},
    vivid::srgb_t{0.90588F, 0.16078F, 0.54118F},
    vivid::srgb_t{0.80784F, 0.07059F, 0.33725F},
    vivid::srgb_t{0.56863F, 0.00000F, 0.24706F},
};

} // namespace GOOM::COLOR::COLOR_DATA
