#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_PURPLES_4 = std::array{
    vivid::srgb_t{0.94902F, 0.94118F, 0.96863F},
    vivid::srgb_t{0.79608F, 0.78824F, 0.88627F},
    vivid::srgb_t{0.61961F, 0.60392F, 0.78431F},
    vivid::srgb_t{0.41569F, 0.31765F, 0.63922F},
};

} // namespace GOOM::COLOR::COLOR_DATA
