#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_PURPLES_3 = std::array{
    vivid::srgb_t{0.93725F, 0.92941F, 0.96078F},
    vivid::srgb_t{0.73725F, 0.74118F, 0.86275F},
    vivid::srgb_t{0.45882F, 0.41961F, 0.69412F},
};

} // namespace GOOM::COLOR::COLOR_DATA
