#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_PURPLEGRAY_6 = std::array{
    vivid::srgb_t{0.48235F, 0.40000F, 0.82353F},
    vivid::srgb_t{0.86275F, 0.37255F, 0.74118F},
    vivid::srgb_t{0.58039F, 0.56863F, 0.48235F},
    vivid::srgb_t{0.60000F, 0.33725F, 0.53333F},
    vivid::srgb_t{0.81569F, 0.59608F, 0.93333F},
    vivid::srgb_t{0.84314F, 0.83529F, 0.77255F},
};

} // namespace GOOM::COLOR::COLOR_DATA
