#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_PURPLES_6 = std::array{
    vivid::srgb_t{0.94902F, 0.94118F, 0.96863F},
    vivid::srgb_t{0.85490F, 0.85490F, 0.92157F},
    vivid::srgb_t{0.73725F, 0.74118F, 0.86275F},
    vivid::srgb_t{0.61961F, 0.60392F, 0.78431F},
    vivid::srgb_t{0.45882F, 0.41961F, 0.69412F},
    vivid::srgb_t{0.32941F, 0.15294F, 0.56078F},
};

} // namespace GOOM::COLOR::COLOR_DATA
