#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_PURPLES_7 = std::array{
    vivid::srgb_t{0.94902F, 0.94118F, 0.96863F},
    vivid::srgb_t{0.85490F, 0.85490F, 0.92157F},
    vivid::srgb_t{0.73725F, 0.74118F, 0.86275F},
    vivid::srgb_t{0.61961F, 0.60392F, 0.78431F},
    vivid::srgb_t{0.50196F, 0.49020F, 0.72941F},
    vivid::srgb_t{0.41569F, 0.31765F, 0.63922F},
    vivid::srgb_t{0.29020F, 0.07843F, 0.52549F},
};

} // namespace GOOM::COLOR::COLOR_DATA
