#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_RDBU_6 = std::array{
    vivid::srgb_t{0.69804F, 0.09412F, 0.16863F},
    vivid::srgb_t{0.93725F, 0.54118F, 0.38431F},
    vivid::srgb_t{0.99216F, 0.85882F, 0.78039F},
    vivid::srgb_t{0.81961F, 0.89804F, 0.94118F},
    vivid::srgb_t{0.40392F, 0.66275F, 0.81176F},
    vivid::srgb_t{0.12941F, 0.40000F, 0.67451F},
};

} // namespace GOOM::COLOR::COLOR_DATA
