#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_RDGY_4 = std::array{
    vivid::srgb_t{0.79216F, 0.00000F, 0.12549F},
    vivid::srgb_t{0.95686F, 0.64706F, 0.50980F},
    vivid::srgb_t{0.72941F, 0.72941F, 0.72941F},
    vivid::srgb_t{0.25098F, 0.25098F, 0.25098F},
};

} // namespace GOOM::COLOR::COLOR_DATA
