#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> RDYLBU_3
{
  {   0.98824F,   0.55294F,   0.34902F },
  {   1.00000F,   1.00000F,   0.74902F },
  {   0.56863F,   0.74902F,   0.85882F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
