#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_RDYLGN_5 = std::array{
    vivid::srgb_t{0.84314F, 0.09804F, 0.10980F},
    vivid::srgb_t{0.99216F, 0.68235F, 0.38039F},
    vivid::srgb_t{1.00000F, 1.00000F, 0.74902F},
    vivid::srgb_t{0.65098F, 0.85098F, 0.41569F},
    vivid::srgb_t{0.10196F, 0.58824F, 0.25490F},
};

} // namespace GOOM::COLOR::COLOR_DATA
