#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> RDYLGN_4
{
  {   0.84314F,   0.09804F,   0.10980F },
  {   0.99216F,   0.68235F,   0.38039F },
  {   0.65098F,   0.85098F,   0.41569F },
  {   0.10196F,   0.58824F,   0.25490F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
