#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_RDYLGN_7 = std::array{
    vivid::srgb_t{0.84314F, 0.18824F, 0.15294F},
    vivid::srgb_t{0.98824F, 0.55294F, 0.34902F},
    vivid::srgb_t{0.99608F, 0.87843F, 0.54510F},
    vivid::srgb_t{1.00000F, 1.00000F, 0.74902F},
    vivid::srgb_t{0.85098F, 0.93725F, 0.54510F},
    vivid::srgb_t{0.56863F, 0.81176F, 0.37647F},
    vivid::srgb_t{0.10196F, 0.59608F, 0.31373F},
};

} // namespace GOOM::COLOR::COLOR_DATA
