#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_REDOR_2 = std::array{
    vivid::srgb_t{0.96471F, 0.82353F, 0.66275F},
    vivid::srgb_t{0.69412F, 0.24706F, 0.39216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
