#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> REDS_4
{
  {   0.99608F,   0.89804F,   0.85098F },
  {   0.98824F,   0.68235F,   0.56863F },
  {   0.98431F,   0.41569F,   0.29020F },
  {   0.79608F,   0.09412F,   0.11373F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
