#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> REDS_6
{
  {   0.99608F,   0.89804F,   0.85098F },
  {   0.98824F,   0.73333F,   0.63137F },
  {   0.98824F,   0.57255F,   0.44706F },
  {   0.98431F,   0.41569F,   0.29020F },
  {   0.87059F,   0.17647F,   0.14902F },
  {   0.64706F,   0.05882F,   0.08235F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
