#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// NOLINTNEXTLINE(cert-err58-cpp): Fix with C++20 and 'constexpr'.
inline const auto REDYELLOWBLUE_3 = std::vector<vivid::srgb_t>{
    {0.64706F, 0.00000F, 0.12941F},
    {1.00000F, 1.00000F, 0.74902F},
    {0.14902F, 0.29804F, 1.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
