#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_ROMA_11 = std::array{
    vivid::srgb_t{0.49804F, 0.09804F, 0.00000F},
    vivid::srgb_t{0.60784F, 0.33333F, 0.08627F},
    vivid::srgb_t{0.70196F, 0.52549F, 0.17255F},
    vivid::srgb_t{0.81176F, 0.74118F, 0.32941F},
    vivid::srgb_t{0.89020F, 0.89804F, 0.60392F},
    vivid::srgb_t{0.79216F, 0.92157F, 0.78824F},
    vivid::srgb_t{0.54118F, 0.84706F, 0.84706F},
    vivid::srgb_t{0.33333F, 0.68627F, 0.80784F},
    vivid::srgb_t{0.24314F, 0.50980F, 0.73333F},
    vivid::srgb_t{0.17647F, 0.34902F, 0.66275F},
    vivid::srgb_t{0.10196F, 0.20000F, 0.60000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
