#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_ROMA_9 = std::array{
    vivid::srgb_t{0.49804F, 0.09804F, 0.00000F},
    vivid::srgb_t{0.63137F, 0.38039F, 0.10980F},
    vivid::srgb_t{0.75686F, 0.63529F, 0.23529F},
    vivid::srgb_t{0.88235F, 0.87451F, 0.54510F},
    vivid::srgb_t{0.79216F, 0.92157F, 0.78824F},
    vivid::srgb_t{0.47843F, 0.81569F, 0.84314F},
    vivid::srgb_t{0.28235F, 0.59608F, 0.77255F},
    vivid::srgb_t{0.19608F, 0.39216F, 0.68235F},
    vivid::srgb_t{0.10196F, 0.20000F, 0.60000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
