#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_ROMA_4 = std::array{
    vivid::srgb_t{0.49804F, 0.09804F, 0.00000F},
    vivid::srgb_t{0.85098F, 0.81176F, 0.42745F},
    vivid::srgb_t{0.38039F, 0.74118F, 0.82745F},
    vivid::srgb_t{0.10196F, 0.20000F, 0.60000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
