#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_ROMA_12 = std::array{
    vivid::srgb_t{0.49804F, 0.09804F, 0.00000F},
    vivid::srgb_t{0.59608F, 0.30980F, 0.07843F},
    vivid::srgb_t{0.68235F, 0.48627F, 0.15294F},
    vivid::srgb_t{0.78431F, 0.68627F, 0.27843F},
    vivid::srgb_t{0.87843F, 0.86275F, 0.51373F},
    vivid::srgb_t{0.86275F, 0.92157F, 0.71765F},
    vivid::srgb_t{0.69412F, 0.90196F, 0.82745F},
    vivid::srgb_t{0.44706F, 0.79608F, 0.83922F},
    vivid::srgb_t{0.30196F, 0.63922F, 0.78824F},
    vivid::srgb_t{0.23137F, 0.47843F, 0.72157F},
    vivid::srgb_t{0.17255F, 0.33725F, 0.65882F},
    vivid::srgb_t{0.10196F, 0.20000F, 0.60000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
