#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_ROMA_16 = std::array{
    vivid::srgb_t{0.49804F, 0.09804F, 0.00000F},
    vivid::srgb_t{0.57255F, 0.25882F, 0.05882F},
    vivid::srgb_t{0.63922F, 0.39608F, 0.11373F},
    vivid::srgb_t{0.70196F, 0.52549F, 0.17255F},
    vivid::srgb_t{0.77255F, 0.67059F, 0.26275F},
    vivid::srgb_t{0.85098F, 0.81176F, 0.42745F},
    vivid::srgb_t{0.89020F, 0.89804F, 0.60392F},
    vivid::srgb_t{0.85098F, 0.92157F, 0.73725F},
    vivid::srgb_t{0.72157F, 0.90980F, 0.81961F},
    vivid::srgb_t{0.54118F, 0.84706F, 0.84706F},
    vivid::srgb_t{0.38039F, 0.74118F, 0.82745F},
    vivid::srgb_t{0.29412F, 0.62353F, 0.78039F},
    vivid::srgb_t{0.24314F, 0.50980F, 0.73333F},
    vivid::srgb_t{0.20000F, 0.40392F, 0.68627F},
    vivid::srgb_t{0.15686F, 0.30196F, 0.64314F},
    vivid::srgb_t{0.10196F, 0.20000F, 0.60000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
