#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_ROYAL1_4 = std::array{
    vivid::srgb_t{0.47451F, 0.64314F, 0.22745F},
    vivid::srgb_t{0.94902F, 0.83922F, 0.68627F},
    vivid::srgb_t{0.36863F, 0.28235F, 0.16078F},
    vivid::srgb_t{0.09412F, 0.07843F, 0.00392F},
};

} // namespace GOOM::COLOR::COLOR_DATA
