#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_SAFE_2 = std::array{
    vivid::srgb_t{0.53333F, 0.80000F, 0.93333F},
    vivid::srgb_t{0.80000F, 0.40000F, 0.46667F},
};

} // namespace GOOM::COLOR::COLOR_DATA
