#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// NOLINTNEXTLINE(cert-err58-cpp): Fix with C++20 and 'constexpr'.
inline const auto SAFE_8 = std::vector<vivid::srgb_t>{
    {0.53333F, 0.80000F, 0.93333F},
    {0.80000F, 0.40000F, 0.46667F},
    {0.86667F, 0.80000F, 0.46667F},
    {0.06667F, 0.46667F, 0.20000F},
    {0.20000F, 0.13333F, 0.53333F},
    {0.66667F, 0.26667F, 0.60000F},
    {0.26667F, 0.66667F, 0.60000F},
    {0.60000F, 0.60000F, 0.20000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
