#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> SET2_3
{
  {   0.40000F,   0.76078F,   0.64706F },
  {   0.98824F,   0.55294F,   0.38431F },
  {   0.55294F,   0.62745F,   0.79608F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
