#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// NOLINTNEXTLINE(cert-err58-cpp): Fix with C++20 and 'constexpr'.
inline const auto SET3_7 = std::vector<vivid::srgb_t>{
    {0.55294F, 0.82745F, 0.78039F},
    {1.00000F, 1.00000F, 0.70196F},
    {0.74510F, 0.72941F, 0.85490F},
    {0.98431F, 0.50196F, 0.44706F},
    {0.50196F, 0.69412F, 0.82745F},
    {0.99216F, 0.70588F, 0.38431F},
    {0.70196F, 0.87059F, 0.41176F},
};

} // namespace GOOM::COLOR::COLOR_DATA
