#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_SOLAR_5 = std::array{
    vivid::srgb_t{0.20000F, 0.07843F, 0.09412F},
    vivid::srgb_t{0.50980F, 0.17647F, 0.13333F},
    vivid::srgb_t{0.71373F, 0.39216F, 0.07451F},
    vivid::srgb_t{0.83137F, 0.67059F, 0.13725F},
    vivid::srgb_t{0.88235F, 0.99216F, 0.29412F},
};

} // namespace GOOM::COLOR::COLOR_DATA
