#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_SOLAR_11 = std::array{
    vivid::srgb_t{0.20000F, 0.07843F, 0.09412F},
    vivid::srgb_t{0.32941F, 0.11765F, 0.13333F},
    vivid::srgb_t{0.45098F, 0.15294F, 0.14118F},
    vivid::srgb_t{0.56078F, 0.20392F, 0.12157F},
    vivid::srgb_t{0.64706F, 0.29020F, 0.09020F},
    vivid::srgb_t{0.71373F, 0.39216F, 0.07451F},
    vivid::srgb_t{0.76863F, 0.49804F, 0.08235F},
    vivid::srgb_t{0.81176F, 0.60784F, 0.11373F},
    vivid::srgb_t{0.84706F, 0.72941F, 0.16471F},
    vivid::srgb_t{0.87059F, 0.85882F, 0.22745F},
    vivid::srgb_t{0.88235F, 0.99216F, 0.29412F},
};

} // namespace GOOM::COLOR::COLOR_DATA
