#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_SOLAR_18 = std::array{
    vivid::srgb_t{0.20000F, 0.07843F, 0.09412F},
    vivid::srgb_t{0.27451F, 0.10196F, 0.12157F},
    vivid::srgb_t{0.34902F, 0.12157F, 0.13725F},
    vivid::srgb_t{0.41961F, 0.14118F, 0.14510F},
    vivid::srgb_t{0.49412F, 0.16863F, 0.13725F},
    vivid::srgb_t{0.55686F, 0.20392F, 0.12157F},
    vivid::srgb_t{0.60784F, 0.25098F, 0.10196F},
    vivid::srgb_t{0.65490F, 0.30196F, 0.09020F},
    vivid::srgb_t{0.69412F, 0.36078F, 0.07843F},
    vivid::srgb_t{0.72941F, 0.42353F, 0.07451F},
    vivid::srgb_t{0.76078F, 0.48627F, 0.07843F},
    vivid::srgb_t{0.78824F, 0.54902F, 0.09412F},
    vivid::srgb_t{0.81569F, 0.61961F, 0.11765F},
    vivid::srgb_t{0.83529F, 0.68627F, 0.14510F},
    vivid::srgb_t{0.85098F, 0.76078F, 0.18039F},
    vivid::srgb_t{0.86667F, 0.83529F, 0.21569F},
    vivid::srgb_t{0.87451F, 0.91373F, 0.25490F},
    vivid::srgb_t{0.88235F, 0.99216F, 0.29412F},
};

} // namespace GOOM::COLOR::COLOR_DATA
