#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_SPECTRAL_3 = std::array{
    vivid::srgb_t{0.98824F, 0.55294F, 0.34902F},
    vivid::srgb_t{1.00000F, 1.00000F, 0.74902F},
    vivid::srgb_t{0.60000F, 0.83529F, 0.58039F},
};

} // namespace GOOM::COLOR::COLOR_DATA
