#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> SPECTRAL_4
{
  {   0.84314F,   0.09804F,   0.10980F },
  {   0.99216F,   0.68235F,   0.38039F },
  {   0.67059F,   0.86667F,   0.64314F },
  {   0.16863F,   0.51373F,   0.72941F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
