#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_SPECTRAL_4 = std::array{
    vivid::srgb_t{0.84314F, 0.09804F, 0.10980F},
    vivid::srgb_t{0.99216F, 0.68235F, 0.38039F},
    vivid::srgb_t{0.67059F, 0.86667F, 0.64314F},
    vivid::srgb_t{0.16863F, 0.51373F, 0.72941F},
};

} // namespace GOOM::COLOR::COLOR_DATA
