#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_SPEED_3 = std::array{
    vivid::srgb_t{1.00000F, 0.99216F, 0.80392F},
    vivid::srgb_t{0.37255F, 0.57255F, 0.04706F},
    vivid::srgb_t{0.09020F, 0.13725F, 0.07451F},
};

} // namespace GOOM::COLOR::COLOR_DATA
