#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_SPEED_17 = std::array{
    vivid::srgb_t{1.00000F, 0.99216F, 0.80392F},
    vivid::srgb_t{0.95686F, 0.91765F, 0.67059F},
    vivid::srgb_t{0.91373F, 0.84706F, 0.53725F},
    vivid::srgb_t{0.85882F, 0.78431F, 0.40000F},
    vivid::srgb_t{0.78824F, 0.72941F, 0.27059F},
    vivid::srgb_t{0.69804F, 0.68627F, 0.15686F},
    vivid::srgb_t{0.59608F, 0.64706F, 0.07059F},
    vivid::srgb_t{0.48627F, 0.61176F, 0.02353F},
    vivid::srgb_t{0.37255F, 0.57255F, 0.04706F},
    vivid::srgb_t{0.26667F, 0.53333F, 0.09412F},
    vivid::srgb_t{0.15686F, 0.48627F, 0.13725F},
    vivid::srgb_t{0.07059F, 0.43137F, 0.16471F},
    vivid::srgb_t{0.04314F, 0.37647F, 0.17647F},
    vivid::srgb_t{0.06667F, 0.31765F, 0.17255F},
    vivid::srgb_t{0.09020F, 0.25490F, 0.15294F},
    vivid::srgb_t{0.09804F, 0.19608F, 0.11765F},
    vivid::srgb_t{0.09020F, 0.13725F, 0.07451F},
};

} // namespace GOOM::COLOR::COLOR_DATA
