#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> SPEED_7
{
  {   1.00000F,   0.99216F,   0.80392F },
  {   0.88235F,   0.80392F,   0.45098F },
  {   0.66667F,   0.67451F,   0.12549F },
  {   0.37255F,   0.57255F,   0.04706F },
  {   0.09412F,   0.45098F,   0.15686F },
  {   0.07843F,   0.29804F,   0.16471F },
  {   0.09020F,   0.13725F,   0.07451F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
