#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_SPEED_7 = std::array{
    vivid::srgb_t{1.00000F, 0.99216F, 0.80392F},
    vivid::srgb_t{0.88235F, 0.80392F, 0.45098F},
    vivid::srgb_t{0.66667F, 0.67451F, 0.12549F},
    vivid::srgb_t{0.37255F, 0.57255F, 0.04706F},
    vivid::srgb_t{0.09412F, 0.45098F, 0.15686F},
    vivid::srgb_t{0.07843F, 0.29804F, 0.16471F},
    vivid::srgb_t{0.09020F, 0.13725F, 0.07451F},
};

} // namespace GOOM::COLOR::COLOR_DATA
