#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_SPEED_6 = std::array{
    vivid::srgb_t{1.00000F, 0.99216F, 0.80392F},
    vivid::srgb_t{0.84706F, 0.77255F, 0.37255F},
    vivid::srgb_t{0.55686F, 0.63529F, 0.04314F},
    vivid::srgb_t{0.19608F, 0.50196F, 0.12157F},
    vivid::srgb_t{0.06275F, 0.32941F, 0.17255F},
    vivid::srgb_t{0.09020F, 0.13725F, 0.07451F},
};

} // namespace GOOM::COLOR::COLOR_DATA
