#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_SUNSETDARK_6 = std::array{
    vivid::srgb_t{0.98824F, 0.87059F, 0.61176F},
    vivid::srgb_t{0.98039F, 0.64314F, 0.46275F},
    vivid::srgb_t{0.94118F, 0.45490F, 0.43137F},
    vivid::srgb_t{0.86275F, 0.22353F, 0.46667F},
    vivid::srgb_t{0.72549F, 0.14510F, 0.47843F},
    vivid::srgb_t{0.48627F, 0.11373F, 0.43529F},
};

} // namespace GOOM::COLOR::COLOR_DATA
