#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> SUNSET_3
{
  {   0.95294F,   0.90588F,   0.60784F },
  {   0.92157F,   0.49804F,   0.52549F },
  {   0.36078F,   0.32549F,   0.64706F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
