#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_SUNSET_3 = std::array{
    vivid::srgb_t{0.95294F, 0.90588F, 0.60784F},
    vivid::srgb_t{0.92157F, 0.49804F, 0.52549F},
    vivid::srgb_t{0.36078F, 0.32549F, 0.64706F},
};

} // namespace GOOM::COLOR::COLOR_DATA
