#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_TABLEAUMEDIUM_10 = std::array{
    vivid::srgb_t{0.44706F, 0.61961F, 0.80784F},
    vivid::srgb_t{1.00000F, 0.61961F, 0.29020F},
    vivid::srgb_t{0.40392F, 0.74902F, 0.36078F},
    vivid::srgb_t{0.92941F, 0.40000F, 0.36471F},
    vivid::srgb_t{0.67843F, 0.54510F, 0.78824F},
    vivid::srgb_t{0.65882F, 0.47059F, 0.43137F},
    vivid::srgb_t{0.92941F, 0.59216F, 0.79216F},
    vivid::srgb_t{0.63529F, 0.63529F, 0.63529F},
    vivid::srgb_t{0.80392F, 0.80000F, 0.36471F},
    vivid::srgb_t{0.42745F, 0.80000F, 0.85490F},
};

} // namespace GOOM::COLOR::COLOR_DATA
