#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_TEAL_5 = std::array{
    vivid::srgb_t{0.81961F, 0.93333F, 0.91765F},
    vivid::srgb_t{0.52157F, 0.76863F, 0.78824F},
    vivid::srgb_t{0.40784F, 0.67059F, 0.72157F},
    vivid::srgb_t{0.30980F, 0.56471F, 0.65098F},
    vivid::srgb_t{0.16471F, 0.33725F, 0.45490F},
};

} // namespace GOOM::COLOR::COLOR_DATA
