#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> TEALGRN_5
{
  {   0.69020F,   0.94902F,   0.73725F },
  {   0.40392F,   0.85882F,   0.64706F },
  {   0.29804F,   0.78431F,   0.63922F },
  {   0.21961F,   0.69804F,   0.63922F },
  {   0.14510F,   0.49020F,   0.59608F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
