#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_TEALGRN_5 = std::array{
    vivid::srgb_t{0.69020F, 0.94902F, 0.73725F},
    vivid::srgb_t{0.40392F, 0.85882F, 0.64706F},
    vivid::srgb_t{0.29804F, 0.78431F, 0.63922F},
    vivid::srgb_t{0.21961F, 0.69804F, 0.63922F},
    vivid::srgb_t{0.14510F, 0.49020F, 0.59608F},
};

} // namespace GOOM::COLOR::COLOR_DATA
