#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// NOLINTNEXTLINE(cert-err58-cpp): Fix with C++20 and 'constexpr'.
inline const auto TEALGRN_2 = std::vector<vivid::srgb_t>{
    {0.69020F, 0.94902F, 0.73725F},
    {0.14510F, 0.49020F, 0.59608F},
};

} // namespace GOOM::COLOR::COLOR_DATA
