#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_TEMPO_6 = std::array{
    vivid::srgb_t{1.00000F, 0.96471F, 0.95686F},
    vivid::srgb_t{0.71373F, 0.79608F, 0.68627F},
    vivid::srgb_t{0.36471F, 0.65490F, 0.52549F},
    vivid::srgb_t{0.06667F, 0.49020F, 0.47451F},
    vivid::srgb_t{0.10980F, 0.30196F, 0.38039F},
    vivid::srgb_t{0.08235F, 0.11373F, 0.26667F},
};

} // namespace GOOM::COLOR::COLOR_DATA
