#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// NOLINTNEXTLINE(cert-err58-cpp): Fix with C++20 and 'constexpr'.
inline const auto TEMPS_6 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.57647F, 0.57255F},
    {0.22353F, 0.69412F, 0.52157F},
    {0.61176F, 0.79608F, 0.52549F},
    {0.93333F, 0.70588F, 0.47451F},
    {0.90980F, 0.51765F, 0.44314F},
    {0.81176F, 0.34902F, 0.49412F},
};

} // namespace GOOM::COLOR::COLOR_DATA
