#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_TEMPO_9 = std::array{
    vivid::srgb_t{1.00000F, 0.96471F, 0.95686F},
    vivid::srgb_t{0.82353F, 0.85098F, 0.78039F},
    vivid::srgb_t{0.63137F, 0.75686F, 0.63137F},
    vivid::srgb_t{0.41176F, 0.67059F, 0.53725F},
    vivid::srgb_t{0.16471F, 0.57647F, 0.49804F},
    vivid::srgb_t{0.06667F, 0.46667F, 0.46667F},
    vivid::srgb_t{0.10588F, 0.34902F, 0.40784F},
    vivid::srgb_t{0.10588F, 0.23529F, 0.33725F},
    vivid::srgb_t{0.08235F, 0.11373F, 0.26667F},
};

} // namespace GOOM::COLOR::COLOR_DATA
