#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_THERMAL_5 = std::array{
    vivid::srgb_t{0.01569F, 0.13725F, 0.20000F},
    vivid::srgb_t{0.33725F, 0.23137F, 0.61176F},
    vivid::srgb_t{0.69412F, 0.37255F, 0.50980F},
    vivid::srgb_t{0.97647F, 0.57255F, 0.25882F},
    vivid::srgb_t{0.90980F, 0.98039F, 0.35686F},
};

} // namespace GOOM::COLOR::COLOR_DATA
