#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_THERMAL_17 = std::array{
    vivid::srgb_t{0.01569F, 0.13725F, 0.20000F},
    vivid::srgb_t{0.03137F, 0.18039F, 0.32941F},
    vivid::srgb_t{0.09804F, 0.20000F, 0.48627F},
    vivid::srgb_t{0.22353F, 0.20000F, 0.61961F},
    vivid::srgb_t{0.33725F, 0.23137F, 0.61176F},
    vivid::srgb_t{0.42745F, 0.27451F, 0.58039F},
    vivid::srgb_t{0.51373F, 0.31373F, 0.56078F},
    vivid::srgb_t{0.60000F, 0.34510F, 0.53725F},
    vivid::srgb_t{0.69412F, 0.37255F, 0.50980F},
    vivid::srgb_t{0.78039F, 0.40000F, 0.46275F},
    vivid::srgb_t{0.87059F, 0.43922F, 0.39608F},
    vivid::srgb_t{0.93725F, 0.49412F, 0.32157F},
    vivid::srgb_t{0.97647F, 0.57255F, 0.25882F},
    vivid::srgb_t{0.98824F, 0.66667F, 0.23529F},
    vivid::srgb_t{0.97647F, 0.76863F, 0.25490F},
    vivid::srgb_t{0.95294F, 0.87451F, 0.29804F},
    vivid::srgb_t{0.90980F, 0.98039F, 0.35686F},
};

} // namespace GOOM::COLOR::COLOR_DATA
