#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> THERMAL_3
{
  {   0.01569F,   0.13725F,   0.20000F },
  {   0.69412F,   0.37255F,   0.50980F },
  {   0.90980F,   0.98039F,   0.35686F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
