#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// NOLINTNEXTLINE(cert-err58-cpp): Fix with C++20 and 'constexpr'.
inline const auto THERMAL_3 = std::vector<vivid::srgb_t>{
    {0.01569F, 0.13725F, 0.20000F},
    {0.69412F, 0.37255F, 0.50980F},
    {0.90980F, 0.98039F, 0.35686F},
};

} // namespace GOOM::COLOR::COLOR_DATA
