#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_TOKYO_7 = std::array{
    vivid::srgb_t{0.10196F, 0.05490F, 0.20392F},
    vivid::srgb_t{0.35294F, 0.17647F, 0.34902F},
    vivid::srgb_t{0.52157F, 0.36863F, 0.47059F},
    vivid::srgb_t{0.56471F, 0.52941F, 0.52549F},
    vivid::srgb_t{0.59216F, 0.68235F, 0.56863F},
    vivid::srgb_t{0.72941F, 0.88235F, 0.66667F},
    vivid::srgb_t{0.99608F, 0.99608F, 0.84706F},
};

} // namespace GOOM::COLOR::COLOR_DATA
