#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_TOKYO_11 = std::array{
    vivid::srgb_t{0.10196F, 0.05490F, 0.20392F},
    vivid::srgb_t{0.25882F, 0.11765F, 0.29020F},
    vivid::srgb_t{0.40392F, 0.21569F, 0.38431F},
    vivid::srgb_t{0.50196F, 0.32941F, 0.45490F},
    vivid::srgb_t{0.54510F, 0.43529F, 0.49804F},
    vivid::srgb_t{0.56471F, 0.52941F, 0.52549F},
    vivid::srgb_t{0.58039F, 0.61961F, 0.54902F},
    vivid::srgb_t{0.60392F, 0.71373F, 0.57647F},
    vivid::srgb_t{0.68235F, 0.83922F, 0.63529F},
    vivid::srgb_t{0.85490F, 0.95686F, 0.74902F},
    vivid::srgb_t{0.99608F, 0.99608F, 0.84706F},
};

} // namespace GOOM::COLOR::COLOR_DATA
