#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_TURBID_17 = std::array{
    vivid::srgb_t{0.91373F, 0.96471F, 0.67059F},
    vivid::srgb_t{0.87843F, 0.89020F, 0.58039F},
    vivid::srgb_t{0.84706F, 0.81961F, 0.49412F},
    vivid::srgb_t{0.81961F, 0.74902F, 0.41176F},
    vivid::srgb_t{0.79216F, 0.68235F, 0.34510F},
    vivid::srgb_t{0.76078F, 0.61176F, 0.29020F},
    vivid::srgb_t{0.72549F, 0.54902F, 0.25882F},
    vivid::srgb_t{0.68235F, 0.49020F, 0.23922F},
    vivid::srgb_t{0.63137F, 0.43922F, 0.23137F},
    vivid::srgb_t{0.58039F, 0.39608F, 0.22745F},
    vivid::srgb_t{0.51765F, 0.35294F, 0.22353F},
    vivid::srgb_t{0.45490F, 0.30980F, 0.21569F},
    vivid::srgb_t{0.38824F, 0.27451F, 0.20392F},
    vivid::srgb_t{0.32549F, 0.23529F, 0.18431F},
    vivid::srgb_t{0.25882F, 0.20000F, 0.16078F},
    vivid::srgb_t{0.19608F, 0.16078F, 0.13725F},
    vivid::srgb_t{0.13333F, 0.12157F, 0.10588F},
};

} // namespace GOOM::COLOR::COLOR_DATA
