#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_TURKU_11 = std::array{
    vivid::srgb_t{0.00000F, 0.00000F, 0.00000F},
    vivid::srgb_t{0.13333F, 0.13333F, 0.12157F},
    vivid::srgb_t{0.23529F, 0.23529F, 0.19608F},
    vivid::srgb_t{0.33725F, 0.33725F, 0.25098F},
    vivid::srgb_t{0.44314F, 0.43922F, 0.29804F},
    vivid::srgb_t{0.57647F, 0.54902F, 0.35686F},
    vivid::srgb_t{0.72549F, 0.62745F, 0.43137F},
    vivid::srgb_t{0.84706F, 0.65490F, 0.50980F},
    vivid::srgb_t{0.93725F, 0.69412F, 0.63137F},
    vivid::srgb_t{0.99216F, 0.79608F, 0.78039F},
    vivid::srgb_t{1.00000F, 0.90196F, 0.90196F},
};

} // namespace GOOM::COLOR::COLOR_DATA
