#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_TURKU_13 = std::array{
    vivid::srgb_t{0.00000F, 0.00000F, 0.00000F},
    vivid::srgb_t{0.11373F, 0.11373F, 0.10196F},
    vivid::srgb_t{0.20000F, 0.19608F, 0.16863F},
    vivid::srgb_t{0.28627F, 0.28627F, 0.22745F},
    vivid::srgb_t{0.37255F, 0.37255F, 0.26667F},
    vivid::srgb_t{0.46275F, 0.45490F, 0.30588F},
    vivid::srgb_t{0.57647F, 0.54902F, 0.35686F},
    vivid::srgb_t{0.70196F, 0.61961F, 0.41961F},
    vivid::srgb_t{0.81176F, 0.65098F, 0.48627F},
    vivid::srgb_t{0.89412F, 0.66667F, 0.56078F},
    vivid::srgb_t{0.96078F, 0.72157F, 0.67843F},
    vivid::srgb_t{0.99608F, 0.81176F, 0.80000F},
    vivid::srgb_t{1.00000F, 0.90196F, 0.90196F},
};

} // namespace GOOM::COLOR::COLOR_DATA
