#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'dependencies/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

#if __cplusplus <= 201402L
namespace GOOM
{
namespace COLOR
{
namespace COLOR_DATA
{
#else
namespace GOOM::COLOR::COLOR_DATA
{
#endif

// clang-format off
static const std::vector<vivid::srgb_t> TURKU_12
{
  {   0.00000F,   0.00000F,   0.00000F },
  {   0.12157F,   0.12157F,   0.10980F },
  {   0.21569F,   0.21569F,   0.18039F },
  {   0.31373F,   0.30980F,   0.23922F },
  {   0.40392F,   0.40392F,   0.28235F },
  {   0.50980F,   0.49804F,   0.32549F },
  {   0.64314F,   0.58824F,   0.38824F },
  {   0.77647F,   0.64314F,   0.45882F },
  {   0.87059F,   0.65882F,   0.53725F },
  {   0.95294F,   0.70980F,   0.65882F },
  {   0.99216F,   0.80392F,   0.79216F },
  {   1.00000F,   0.90196F,   0.90196F },
};
// clang-format on

#if __cplusplus <= 201402L
} // namespace COLOR_DATA
} // namespace COLOR
} // namespace GOOM
#else
} // namespace GOOM::COLOR::COLOR_DATA
#endif
