#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_TURKU_15 = std::array{
    vivid::srgb_t{0.00000F, 0.00000F, 0.00000F},
    vivid::srgb_t{0.10196F, 0.10196F, 0.09412F},
    vivid::srgb_t{0.17255F, 0.17255F, 0.15294F},
    vivid::srgb_t{0.25098F, 0.25098F, 0.20392F},
    vivid::srgb_t{0.32549F, 0.32157F, 0.24314F},
    vivid::srgb_t{0.39608F, 0.39608F, 0.27843F},
    vivid::srgb_t{0.47451F, 0.46667F, 0.31373F},
    vivid::srgb_t{0.57647F, 0.54902F, 0.35686F},
    vivid::srgb_t{0.68627F, 0.61176F, 0.40784F},
    vivid::srgb_t{0.78431F, 0.64314F, 0.46667F},
    vivid::srgb_t{0.85882F, 0.65882F, 0.52549F},
    vivid::srgb_t{0.92549F, 0.68235F, 0.60784F},
    vivid::srgb_t{0.97647F, 0.74902F, 0.71765F},
    vivid::srgb_t{0.99608F, 0.82353F, 0.81569F},
    vivid::srgb_t{1.00000F, 0.90196F, 0.90196F},
};

} // namespace GOOM::COLOR::COLOR_DATA
