#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_TURKU_9 = std::array{
    vivid::srgb_t{0.00000F, 0.00000F, 0.00000F},
    vivid::srgb_t{0.15686F, 0.15686F, 0.13725F},
    vivid::srgb_t{0.28627F, 0.28627F, 0.22745F},
    vivid::srgb_t{0.41961F, 0.41569F, 0.28627F},
    vivid::srgb_t{0.57647F, 0.54902F, 0.35686F},
    vivid::srgb_t{0.76078F, 0.63922F, 0.45098F},
    vivid::srgb_t{0.89412F, 0.66667F, 0.56078F},
    vivid::srgb_t{0.98431F, 0.76471F, 0.74118F},
    vivid::srgb_t{1.00000F, 0.90196F, 0.90196F},
};

} // namespace GOOM::COLOR::COLOR_DATA
