#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_TURKU_12 = std::array{
    vivid::srgb_t{0.00000F, 0.00000F, 0.00000F},
    vivid::srgb_t{0.12157F, 0.12157F, 0.10980F},
    vivid::srgb_t{0.21569F, 0.21569F, 0.18039F},
    vivid::srgb_t{0.31373F, 0.30980F, 0.23922F},
    vivid::srgb_t{0.40392F, 0.40392F, 0.28235F},
    vivid::srgb_t{0.50980F, 0.49804F, 0.32549F},
    vivid::srgb_t{0.64314F, 0.58824F, 0.38824F},
    vivid::srgb_t{0.77647F, 0.64314F, 0.45882F},
    vivid::srgb_t{0.87059F, 0.65882F, 0.53725F},
    vivid::srgb_t{0.95294F, 0.70980F, 0.65882F},
    vivid::srgb_t{0.99216F, 0.80392F, 0.79216F},
    vivid::srgb_t{1.00000F, 0.90196F, 0.90196F},
};

} // namespace GOOM::COLOR::COLOR_DATA
