#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_VIK_18 = std::array{
    vivid::srgb_t{0.00000F, 0.07059F, 0.38039F},
    vivid::srgb_t{0.00784F, 0.16471F, 0.43922F},
    vivid::srgb_t{0.01176F, 0.25490F, 0.49804F},
    vivid::srgb_t{0.03137F, 0.34902F, 0.56078F},
    vivid::srgb_t{0.14510F, 0.45882F, 0.63137F},
    vivid::srgb_t{0.31765F, 0.58039F, 0.71373F},
    vivid::srgb_t{0.50196F, 0.69804F, 0.79216F},
    vivid::srgb_t{0.69020F, 0.81176F, 0.87059F},
    vivid::srgb_t{0.87059F, 0.90196F, 0.91373F},
    vivid::srgb_t{0.93333F, 0.85882F, 0.81569F},
    vivid::srgb_t{0.89412F, 0.74510F, 0.65882F},
    vivid::srgb_t{0.84314F, 0.62745F, 0.50588F},
    vivid::srgb_t{0.80000F, 0.52157F, 0.36471F},
    vivid::srgb_t{0.75294F, 0.41961F, 0.22745F},
    vivid::srgb_t{0.68627F, 0.29804F, 0.09412F},
    vivid::srgb_t{0.56078F, 0.16863F, 0.02353F},
    vivid::srgb_t{0.45098F, 0.07843F, 0.02353F},
    vivid::srgb_t{0.34902F, 0.00000F, 0.03137F},
};

} // namespace GOOM::COLOR::COLOR_DATA
