#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_VIK_19 = std::array{
    vivid::srgb_t{0.00000F, 0.07059F, 0.38039F},
    vivid::srgb_t{0.00784F, 0.15686F, 0.43529F},
    vivid::srgb_t{0.01176F, 0.24314F, 0.49020F},
    vivid::srgb_t{0.02353F, 0.32941F, 0.54510F},
    vivid::srgb_t{0.11765F, 0.43529F, 0.61569F},
    vivid::srgb_t{0.27059F, 0.54510F, 0.69020F},
    vivid::srgb_t{0.44314F, 0.65882F, 0.76863F},
    vivid::srgb_t{0.61569F, 0.76863F, 0.83922F},
    vivid::srgb_t{0.78824F, 0.86667F, 0.90588F},
    vivid::srgb_t{0.92549F, 0.89804F, 0.87843F},
    vivid::srgb_t{0.91765F, 0.80784F, 0.74118F},
    vivid::srgb_t{0.87451F, 0.69804F, 0.59608F},
    vivid::srgb_t{0.82745F, 0.59216F, 0.45490F},
    vivid::srgb_t{0.78824F, 0.49412F, 0.32549F},
    vivid::srgb_t{0.74510F, 0.39608F, 0.20000F},
    vivid::srgb_t{0.67059F, 0.28235F, 0.07843F},
    vivid::srgb_t{0.54510F, 0.15294F, 0.02353F},
    vivid::srgb_t{0.44314F, 0.07451F, 0.02745F},
    vivid::srgb_t{0.34902F, 0.00000F, 0.03137F},
};

} // namespace GOOM::COLOR::COLOR_DATA
