#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_VIK_20 = std::array{
    vivid::srgb_t{0.00000F, 0.07059F, 0.38039F},
    vivid::srgb_t{0.00784F, 0.15294F, 0.43137F},
    vivid::srgb_t{0.01176F, 0.23529F, 0.48627F},
    vivid::srgb_t{0.01961F, 0.31765F, 0.53725F},
    vivid::srgb_t{0.09020F, 0.41176F, 0.60000F},
    vivid::srgb_t{0.22353F, 0.51373F, 0.67059F},
    vivid::srgb_t{0.39216F, 0.62745F, 0.74510F},
    vivid::srgb_t{0.55294F, 0.72941F, 0.81569F},
    vivid::srgb_t{0.71373F, 0.82745F, 0.88235F},
    vivid::srgb_t{0.87843F, 0.90196F, 0.91373F},
    vivid::srgb_t{0.93333F, 0.86667F, 0.82745F},
    vivid::srgb_t{0.89804F, 0.75686F, 0.67843F},
    vivid::srgb_t{0.85882F, 0.65882F, 0.54510F},
    vivid::srgb_t{0.81569F, 0.56471F, 0.41961F},
    vivid::srgb_t{0.77647F, 0.46667F, 0.29020F},
    vivid::srgb_t{0.73333F, 0.37647F, 0.17647F},
    vivid::srgb_t{0.64706F, 0.25098F, 0.05882F},
    vivid::srgb_t{0.53725F, 0.14902F, 0.02353F},
    vivid::srgb_t{0.43529F, 0.06667F, 0.02745F},
    vivid::srgb_t{0.34902F, 0.00000F, 0.03137F},
};

} // namespace GOOM::COLOR::COLOR_DATA
