#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// NOLINTNEXTLINE(cert-err58-cpp): Fix with C++20 and 'constexpr'.
inline const auto VIK_4 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.07059F, 0.38039F},
    {0.44314F, 0.65882F, 0.76863F},
    {0.82745F, 0.59216F, 0.45490F},
    {0.34902F, 0.00000F, 0.03137F},
};

} // namespace GOOM::COLOR::COLOR_DATA
