#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_VIK_16 = std::array{
    vivid::srgb_t{0.00000F, 0.07059F, 0.38039F},
    vivid::srgb_t{0.00784F, 0.17647F, 0.44706F},
    vivid::srgb_t{0.01176F, 0.27843F, 0.51373F},
    vivid::srgb_t{0.06667F, 0.39216F, 0.58824F},
    vivid::srgb_t{0.23529F, 0.52157F, 0.67451F},
    vivid::srgb_t{0.44314F, 0.65882F, 0.76863F},
    vivid::srgb_t{0.65490F, 0.78824F, 0.85490F},
    vivid::srgb_t{0.85882F, 0.89804F, 0.91373F},
    vivid::srgb_t{0.93333F, 0.85098F, 0.80392F},
    vivid::srgb_t{0.88235F, 0.72157F, 0.62745F},
    vivid::srgb_t{0.82745F, 0.59216F, 0.45490F},
    vivid::srgb_t{0.77647F, 0.47451F, 0.29804F},
    vivid::srgb_t{0.71765F, 0.35294F, 0.14902F},
    vivid::srgb_t{0.59608F, 0.20000F, 0.02745F},
    vivid::srgb_t{0.46275F, 0.09020F, 0.02353F},
    vivid::srgb_t{0.34902F, 0.00000F, 0.03137F},
};

} // namespace GOOM::COLOR::COLOR_DATA
