#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_VIRIDIS_19 = std::array{
    vivid::srgb_t{0.26667F, 0.00392F, 0.32941F},
    vivid::srgb_t{0.28235F, 0.08627F, 0.40784F},
    vivid::srgb_t{0.28235F, 0.15686F, 0.47059F},
    vivid::srgb_t{0.26667F, 0.22353F, 0.51373F},
    vivid::srgb_t{0.24314F, 0.29020F, 0.53725F},
    vivid::srgb_t{0.21569F, 0.35294F, 0.54902F},
    vivid::srgb_t{0.19216F, 0.40784F, 0.55686F},
    vivid::srgb_t{0.16863F, 0.45882F, 0.55686F},
    vivid::srgb_t{0.14902F, 0.50980F, 0.55686F},
    vivid::srgb_t{0.12941F, 0.56863F, 0.54902F},
    vivid::srgb_t{0.12157F, 0.61961F, 0.53725F},
    vivid::srgb_t{0.14510F, 0.67059F, 0.50980F},
    vivid::srgb_t{0.20784F, 0.71765F, 0.47451F},
    vivid::srgb_t{0.30588F, 0.76471F, 0.41961F},
    vivid::srgb_t{0.42353F, 0.80392F, 0.35294F},
    vivid::srgb_t{0.55686F, 0.83922F, 0.27059F},
    vivid::srgb_t{0.70980F, 0.87059F, 0.16863F},
    vivid::srgb_t{0.85490F, 0.89020F, 0.09804F},
    vivid::srgb_t{0.99216F, 0.90588F, 0.14510F},
};

} // namespace GOOM::COLOR::COLOR_DATA
