#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_VIRIDIS_15 = std::array{
    vivid::srgb_t{0.26667F, 0.00392F, 0.32941F},
    vivid::srgb_t{0.28235F, 0.10588F, 0.42745F},
    vivid::srgb_t{0.27451F, 0.19608F, 0.49412F},
    vivid::srgb_t{0.24706F, 0.28235F, 0.53725F},
    vivid::srgb_t{0.21176F, 0.36078F, 0.55294F},
    vivid::srgb_t{0.18039F, 0.43137F, 0.55686F},
    vivid::srgb_t{0.15294F, 0.49804F, 0.55686F},
    vivid::srgb_t{0.12941F, 0.56863F, 0.54902F},
    vivid::srgb_t{0.12157F, 0.63137F, 0.52941F},
    vivid::srgb_t{0.17647F, 0.69804F, 0.49020F},
    vivid::srgb_t{0.29020F, 0.75686F, 0.42745F},
    vivid::srgb_t{0.43922F, 0.81176F, 0.34118F},
    vivid::srgb_t{0.62745F, 0.85490F, 0.22353F},
    vivid::srgb_t{0.81569F, 0.88235F, 0.10980F},
    vivid::srgb_t{0.99216F, 0.90588F, 0.14510F},
};

} // namespace GOOM::COLOR::COLOR_DATA
