#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_VIRIDIS_14 = std::array{
    vivid::srgb_t{0.26667F, 0.00392F, 0.32941F},
    vivid::srgb_t{0.28235F, 0.11373F, 0.43529F},
    vivid::srgb_t{0.27059F, 0.20784F, 0.50588F},
    vivid::srgb_t{0.23922F, 0.30196F, 0.54118F},
    vivid::srgb_t{0.20392F, 0.38039F, 0.55294F},
    vivid::srgb_t{0.16863F, 0.45490F, 0.55686F},
    vivid::srgb_t{0.14118F, 0.52941F, 0.55686F},
    vivid::srgb_t{0.12157F, 0.60000F, 0.54118F},
    vivid::srgb_t{0.14510F, 0.67451F, 0.50980F},
    vivid::srgb_t{0.25098F, 0.74118F, 0.44706F},
    vivid::srgb_t{0.40392F, 0.80000F, 0.36078F},
    vivid::srgb_t{0.59608F, 0.84706F, 0.24314F},
    vivid::srgb_t{0.79216F, 0.88235F, 0.12157F},
    vivid::srgb_t{0.99216F, 0.90588F, 0.14510F},
};

} // namespace GOOM::COLOR::COLOR_DATA
