#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// NOLINTNEXTLINE(cert-err58-cpp): Fix with C++20 and 'constexpr'.
inline const auto YLGNBU_7 = std::vector<vivid::srgb_t>{
    {1.00000F, 1.00000F, 0.80000F},
    {0.78039F, 0.91373F, 0.70588F},
    {0.49804F, 0.80392F, 0.73333F},
    {0.25490F, 0.71373F, 0.76863F},
    {0.11373F, 0.56863F, 0.75294F},
    {0.13333F, 0.36863F, 0.65882F},
    {0.04706F, 0.17255F, 0.51765F},
};

} // namespace GOOM::COLOR::COLOR_DATA
