#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_YLGNBU_3 = std::array{
    vivid::srgb_t{0.92941F, 0.97255F, 0.69412F},
    vivid::srgb_t{0.49804F, 0.80392F, 0.73333F},
    vivid::srgb_t{0.17255F, 0.49804F, 0.72157F},
};

} // namespace GOOM::COLOR::COLOR_DATA
