#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_YLGNBU_6 = std::array{
    vivid::srgb_t{1.00000F, 1.00000F, 0.80000F},
    vivid::srgb_t{0.78039F, 0.91373F, 0.70588F},
    vivid::srgb_t{0.49804F, 0.80392F, 0.73333F},
    vivid::srgb_t{0.25490F, 0.71373F, 0.76863F},
    vivid::srgb_t{0.17255F, 0.49804F, 0.72157F},
    vivid::srgb_t{0.14510F, 0.20392F, 0.58039F},
};

} // namespace GOOM::COLOR::COLOR_DATA
