#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> YLGN_4
{
  {   1.00000F,   1.00000F,   0.80000F },
  {   0.76078F,   0.90196F,   0.60000F },
  {   0.47059F,   0.77647F,   0.47451F },
  {   0.13725F,   0.51765F,   0.26275F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
