#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_YLORBR_8 = std::array{
    vivid::srgb_t{1.00000F, 1.00000F, 0.89804F},
    vivid::srgb_t{1.00000F, 0.96863F, 0.73725F},
    vivid::srgb_t{0.99608F, 0.89020F, 0.56863F},
    vivid::srgb_t{0.99608F, 0.76863F, 0.30980F},
    vivid::srgb_t{0.99608F, 0.60000F, 0.16078F},
    vivid::srgb_t{0.92549F, 0.43922F, 0.07843F},
    vivid::srgb_t{0.80000F, 0.29804F, 0.00784F},
    vivid::srgb_t{0.54902F, 0.17647F, 0.01569F},
};

} // namespace GOOM::COLOR::COLOR_DATA
