#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"
#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

// clang-format off
static const std::vector<vivid::srgb_t> YLORRD_6
{
  {   1.00000F,   1.00000F,   0.69804F },
  {   0.99608F,   0.85098F,   0.46275F },
  {   0.99608F,   0.69804F,   0.29804F },
  {   0.99216F,   0.55294F,   0.23529F },
  {   0.94118F,   0.23137F,   0.12549F },
  {   0.74118F,   0.00000F,   0.14902F },
};
// clang-format on

} // namespace GOOM::COLOR::COLOR_DATA
