#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <array>

namespace GOOM::COLOR::COLOR_DATA
{

inline constexpr auto VIV_YLORRD_5 = std::array{
    vivid::srgb_t{1.00000F, 1.00000F, 0.69804F},
    vivid::srgb_t{0.99608F, 0.80000F, 0.36078F},
    vivid::srgb_t{0.99216F, 0.55294F, 0.23529F},
    vivid::srgb_t{0.94118F, 0.23137F, 0.12549F},
    vivid::srgb_t{0.74118F, 0.00000F, 0.14902F},
};

} // namespace GOOM::COLOR::COLOR_DATA
